### ISSUE TITLE
How do custom scheduler plugins work?

### ISSUE THREAD

**Issue by peterfeifanchen** [kubernetes-sigs/scheduler-plugins#102]
Hi, I was reading Kubernetes concepts on schedulers here

https://kubernetes.io/docs/concepts/scheduling-eviction/scheduling-framework/

And at the bottom it referred to this github for more information on custom plugins to the extension points of the kubernetes scheduler.

```
In addition to default plugins, you can also implement your own scheduling plugins and get them configured along with default plugins. You can visit scheduler-plugins for more details.
```

I am curious as to how that works here, are the scheduler plugins something you add to `https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go` at compile time and then create your own scheduler or is there someway to add just custom plugins at runtime?

I am just curious about this as I have been looking into how the Kubernetes default scheduler works, but there seems to be two levels of customization: 1) write your own scheduler-controller, 2) custom plugins at the extension points. But I am a bit confused how 2) is deployed at runtime if at all? Thanks!

**Comment by seanmalloy** [comment]
I'll attempt to answer this question although I'm not a scheduling plugins expert. Some of the other project maintains may be able to give a more correct answer.

Scheduling plugins are written in Go using the new-ish scheduling framework. You compile a new kube-scheduler binary which includes your plugin(i.e. a new scoring plugin). The kube-scheduler binary that you just complied would then replace the default kube-scheduler. Run time configuration of the default kube-scheduler or custom kube-scheduler with extra plugins is controlled by [KubeSchedulerConfiguration](https://kubernetes.io/docs/reference/scheduling/config/).

Related to #89.

/kind support

**Comment by Huang-Wei** [comment]
> I am curious as to how that works here, are the scheduler plugins something you add to `https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go` at compile time and then create your own scheduler or is there someway to add just custom plugins at runtime?

It does build stuff at compile time, but atop "k8s.io/kubernetes/cmd/kube-scheduler/app":

https://github.com/kubernetes-sigs/scheduler-plugins/blob/011599fb15f2d57dbec7afa086814602d7f24664/cmd/scheduler/main.go#L39-L42

> I am just curious about this as I have been looking into how the Kubernetes default scheduler works, but there seems to be two levels of customization: 1) write your own scheduler-controller, 2) custom plugins at the extension points. But I am a bit confused how 2) is deployed at runtime if at all? Thanks!

It's not deployed at runtime. Custom plugins have to be built along with the in-tree scheduler base, and then launched as sort a "default scheduler++".

**Comment by peterfeifanchen** [comment]
I see thank you!

**Comment by lianghao208** [comment]
I can`t create KubeSchedulerConfiguration because there is no such Kind in group version kubescheduler.config.k8s.io/v1beta1. Did I miss some steps to configure my cluster? I can`t find any docs say anything about creating CRD or Apiservices to extend the apis first tho. 
@peterfeifanchen
@Huang-Wei

**Comment by Huang-Wei** [comment]
@lianghao208 I'm not following your question, and it's off this topic, right? If so, I'd suggest to describe your problem in details in a separate issue.
