### ISSUE TITLE
Create CRD failed

### ISSUE THREAD

**Issue by zhiyuone** [kubernetes-sigs/scheduler-plugins#104]
I try go apply `manifests/coscheduling/crd.yaml` then get this error. 
> error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "validation" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false

It seems `validation` field avaliable in `apiextensions/v1beta1` and removed from `apiextensions/v1`
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinitionspec-v1-apiextensions-k8s-io
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/#customresourcedefinitionspec-v1beta1-apiextensions-k8s-io

Is it the wrong way to use it?

**Comment by lianghao208** [comment]
What`s the version of your kubernetes cluster?

**Comment by Huang-Wei** [comment]
@zhiyuone Apologize for the glitch. You're right, I created #105 to fix this.
