### ISSUE TITLE
Autogen files are not updated on running `make autogen`

### ISSUE THREAD

**Issue by zorro786** [kubernetes-sigs/scheduler-plugins#116]
Using Go version (1.14 and 1.15) on OSX, I am unable to generate code gen files for types defined under `pkg/apis/config/types.go` and `pkg/apis/config/v1beta/types.go`. 

```
$: make autogen
hack/update-vendor.sh
hack/update-generated-openapi.sh
Generating Kubernetes OpenAPI
```

The command runs successfully but zz_generated* files are not updated.

**Comment by Huang-Wei** [comment]
@zorro786 please run `hack/update-codegen.sh` and ensure scheduler-plugins code are put under $GOPATH.

**Comment by zorro786** [comment]
Tried that too
```
➜  scheduler-plugins git:(real-load-plugin) ✗ hack/update-codegen.sh
Generating deepcopy funcs
Generating defaulters
Generating conversions
Generating deepcopy funcs
Generating clientset for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/clientset
Generating listers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/listers
Generating informers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/informers
```
Both from $GOPATH directory and outside that. Doesn't generate any files.

**Comment by AlexeyPerevalov** [comment]
hack/update-codegen.sh count on scheduler-plugins situated at path $HOME/go/src/sigs.k8s.io/scheduler-plugins,
where you GOPATH is $HOME/go
so if your scheduler-plugins repo outside of $GOPATH/src/sigs.k8s.io the place where generated files will be is $HOME/go/src/sigs.k8s.io/scheduler-plugins.
Are you expect it at you current directory e.g. $HOME/src/github/kubernetes-sigs/scheduler-plugins?

**Comment by zorro786** [comment]
@AlexeyPerevalov Thank you for clarification. My directory was `$GOPATH/src/github.com/k8s.io/scheduler-plugins`. It will be great if the script takes care of copying over files from `$GOPATH/src/sigs.k8s.io/scheduler-plugins`, if generated outside GOPATH.

**Comment by Huang-Wei** [comment]
@zorro786 $GOPATH/src/github.com/k8s.io/scheduler-plugins is not a legal path. As @AlexeyPerevalov mentioned, you should use `$HOME/go/src/sigs.k8s.io/scheduler-plugins`. Similarly, for Kubernetes development, you should put k8s src code in `$HOME/go/src/k8s.io/kubernetes`. `github.com` shouldn't exist.

> It will be great if the script takes care of copying over files from $GOPATH/src/sigs.k8s.io/scheduler-plugins, if generated outside GOPATH.

It's not the case. It's that the GOPATH should be legal.

**Comment by Huang-Wei** [comment]
```script
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115
⇒  echo $GOPATH
/Users/wei.huang1/gospace
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115
⇒  go version
go version go1.15 darwin/amd64
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115
⇒  make autogen
hack/update-vendor.sh
go: downloading golang.org/x/time v0.0.0-20200630173020-3af7569d3a1e
go: downloading golang.org/x/sys v0.0.0-20200826173525-f9321e4c35a6
go: downloading github.com/paypal/load-watcher v0.0.0-20201124000647-fb86845885bf
go: downloading github.com/google/go-cmp v0.5.2
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading github.com/NYTimes/gziphandler v1.0.1
go: downloading golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
go: downloading github.com/francoispqt/gojay v1.2.13
go: downloading github.com/mitchellh/mapstructure v1.3.3
go: downloading github.com/Azure/go-autorest/autorest v0.10.0
go: downloading github.com/pquerna/cachecontrol v0.0.0-20180517163645-1555304b9b35
go: downloading github.com/kr/pretty v0.2.1
go: downloading github.com/googleapis/gax-go v2.0.0+incompatible
go: downloading github.com/Azure/go-autorest/autorest/validation v0.2.0
hack/update-generated-openapi.sh
Generating Kubernetes OpenAPI
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115⚡
⇒  gst
On branch pr/115
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   go.mod

no changes added to commit (use "git add" and/or "git commit -a")
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115⚡
⇒  hack/update-codegen.sh
Generating deepcopy funcs
Generating defaulters
Generating conversions
Generating deepcopy funcs
Generating clientset for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/clientset
Generating listers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/listers
Generating informers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/informers
wei.huang1@wei-mbp:~/gospace/src/sigs.k8s.io/scheduler-plugins|pr/115⚡
⇒  gst
On branch pr/115
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   go.mod
	modified:   pkg/apis/config/v1beta1/zz_generated.conversion.go
	modified:   pkg/apis/config/v1beta1/zz_generated.deepcopy.go
	modified:   pkg/apis/config/v1beta1/zz_generated.defaults.go
	modified:   pkg/apis/config/zz_generated.deepcopy.go

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by zorro786** [comment]
@Huang-Wei I see, but isn't the point of go mod integration in K8s to allow development outside GOPATH? I just found an issue which discusses this https://github.com/kubernetes/kubernetes/issues/86753

**Comment by Huang-Wei** [comment]
That's the ultimate goal. But we're not there yet :)

**Comment by zorro786** [comment]
Got it, then if we can specify this in docs (of at least scheduler-plugins) that development should be done in valid GOPATH, it will save some trouble :)

**Comment by AlexeyPerevalov** [comment]
I think it worth extend documentation of scheduler-plugin. @Huang-Wei how do you see on this, if I'll submit patch for it?

**Comment by Huang-Wei** [comment]
@AlexeyPerevalov Yes, please. That would be very appreciable!

**Comment by zorro786** [comment]
@AlexeyPerevalov I see all files generated properly except `pkg/apis/config/v1beta1/zz_generated.defaults.go` This file does get generated as the following:

```
package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// RegisterDefaults adds defaulters functions to the given scheme.
// Public to allow building arbitrary schemes.
// All generated defaulters are covering - they call all nested defaulters.
func RegisterDefaults(scheme *runtime.Scheme) error {
	return nil
}
```

Per `pkg/apis/config/v1beta1/defaults.go` it should add functions here. Anything extra to be done for this?

**Comment by Huang-Wei** [comment]
@zorro786 The defaulter-gen doesn't work for me as well :) You have to follow the current pattern to manually register your defaulter function. But let me know if you find a better way.

**Comment by AlexeyPerevalov** [comment]
@Huang-Wei I think this issue could be closed.

**Comment by Huang-Wei** [comment]
Close this as [doc/develop.md](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/develop.md) covered this.
