### ISSUE TITLE
Concerns for potential deadlocking Issue

### ISSUE THREAD

**Issue by TomLan42** [kubernetes-sigs/scheduler-plugins#117]
I have experienced a similar problem when I am testing the coschedulnig plugin with Kubemark. 

I prepared 2 hollow-nodes, each with 8 GPU. Then I submit several dozens of jobs sequentially (i.e. 60 jobs in total, submit every 15 seconds, each job runs for around 30 seconds), each requiring 1-8 GPU cards. It would work fine when there were sufficient GPU resources and every pod in a job could get allocated without pending. 

When there were not enough GPU resources for the incoming jobs, those jobs will start pending, which is as expected. However, when the running jobs succeeded and released enough resources for the pending jobs, no pending jobs would start. All the jobs would still pending even if there were enough resources for at least one of them because 1-8 always < 16.

I suspect this is a typical deadlocking situation that happens in the 'Permit' stage. And I indeed observed the interleaving of pods of different podgroup waiting in the logs. 

It is reported in the design doc that the QueueSort Plugins ensures the Pod belonging to the same PodGroup will be placed back to back to avoid deadlock (I am not sure if this is also the method of the latest PodGroup CRD based coscheduling). However, the QueueSort Plugins only have an effect on the ActiveQ. 

Imagine the situations where some pods of a podgroup are in the Permit stage, while others may be thrown into BackoffQ or UnschedulableQ because of failed scheduling due to insufficient resources. When will the later pods be flushed back to ActiveQ is kind of 'random'. When the pods in the Permit stage expire and requeue (or thrown into BackoffQ/UnschedulableQ), they may never have the chance to 'reunite' with their peers in the ActiveQ back-to-back. The result is, there is always only a part of the pods of each podgroup are competing in the reserve stage thus deadlock happens. 

This is just suspicion based on what I observe in my experiment and what I read about the coscheudling plugins and kube-scheduler SchedulilngQueue Mechanism. I worry that the BackoffQ and UnschedulableQ mechanism will somehow invalidate some of the assumptions the coscheduling plugins implies.

_Originally posted by @TomLan42 in https://github.com/kubernetes-sigs/scheduler-plugins/issues/114#issuecomment-733449270_

**Comment by Huang-Wei** [comment]
@TomLan42 Thanks for the report. What's your workload spec in terms of their GPU request and PodGroup settings? and how many pending Pods in total?

BTW: It looks to me your case is, although not exactly the same, similar to the test case here:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/1708d81985c996ca852b2472c2e89dfa7e4f9f3a/test/integration/coscheduling_test.go#L322

**Comment by denkensk** [comment]
> Hey @TomLan42 could you resolve this issue with the plugin ? I am getting the same errors. Did increasing timeout help ?

@karanchahal  Which version are you testing?
