### ISSUE TITLE
Custom Scoring Plugin

### ISSUE THREAD

**Issue by mixalako** [kubernetes-sigs/scheduler-plugins#118]
Hello everyone, I would like to create my **own scoring plugin** , for example myallocation.go which favors nodes the widest fraction of CPU and memory. I've realized that all i have to do is register my plugin in algorithmprovider/register.go and then create my plugin integrating into the scheduling framework.Do i also have to make an myallocation_test.go before i compile the whole project and run it as a different scheduler. Is there another way? Is this a proper way? At last i would like to say that it would be very useful if there were any advises or guides on how to take the best out of the **scheduling framework** enabling and disabling plugins simple and successfully. 
Thank you in advance.

**Comment by Huang-Wei** [comment]
> I've realized that all i have to do is register my plugin in algorithmprovider/register.go and then create my plugin integrating into the scheduling framework.

That's right, but usually you don't need to manipulate that explicitly - you can use `app.WithPlugin` to get your plugin registered, which does the heavy-liftings underneath:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/1708d81985c996ca852b2472c2e89dfa7e4f9f3a/cmd/scheduler/main.go#L43-L50

> Do i also have to make an myallocation_test.go before i compile the whole project and run it as a different scheduler.

A test is optional but highly recommended. Running is a secondary scheduler may fall into resource conflicts, so it's recommended to use your customized scheduler to replace default-scheduler, esp. for production env. If you don't quite care about resource conflicts among multiple schedulers, sure, you can run it as a standalone scheduler.

> At last i would like to say that it would be very useful if there were any advises or guides on how to take the best out of the scheduling framework enabling and disabling plugins simple and successfully.

True. We're short of hands... Any help is very appreciated.

**Comment by mixalako** [comment]
Thank you for the response @Huang-Wei  , just to be clear i would like to create some new plugins , enable them and disable some of the default scheduler plugins . In order to test for differences between the two different set of plugins i would like to deploy two different schedulers. Is there any other way that you would recommend or just what i mentioned above will work just fine .(Conclusion of the above method is register through register.go or through the app.WithPlugin , make my scheduler using the frameworks interface , make a _test.go to avoid conflicts and then compile and deploy as a different custom scheduler).
Thank you in advance

**Comment by Huang-Wei** [comment]
@mixalako Running multiple schedulers is always good for testing purposes.

> Is there any other way that you would recommend or just what i mentioned above will work just fine .

As you're already attempting to exercise scheduler framework, the other option is to use multiple profiles in a **single** customized scheduler to simulate different scheduling "flavors". For example, profile "default-scheduler" for vanilla scheduling behavior, and other profiles to exercise enabling customized plugins as well as disabling some default plugins.

So it's like {multi-scheduler and each scheduler as a scheduling profile} vs. {one scheduler with multiple internal profiles}.

If you want to know more details about multi-profile scheduler, check out the doc here: https://github.com/kubernetes/kubernetes/tree/master/test/integration/scheduler_perf. Also the latest KubeCon talk covered it: https://sched.co/ekHV.

**Comment by mixalako** [comment]
Thanks again for everything @Huang-Wei  , only thing i can find at KubeCon link is a pptx. Because i am new to this , i would appreciate if you gave some advice or promp me somewhere, on how to take advantage of the framework and how to use it in general. In my case , i want to take advantage of prometheus metrics in a scoring plugin , so for testing purposes disable all resource related plugins and replace them with some custom build scoring plugin and test if some metric of the system will get better. Any help would be life saving really.

**Comment by damemi** [comment]
To write a custom plugin, you need to compile them into a custom-built scheduler like @Huang-Wei mentioned above. I would recommend the [scheduler framework enhancement](https://github.com/kubernetes/enhancements/blob/master/keps/sig-scheduling/624-scheduling-framework/README.md) for more info on this (specifically the section on "out-of-tree plugins" may be helpful).

To disable other plugins and enable your custom plugin, you'll need to pass a config file specifying the profiles you want. See https://kubernetes.io/docs/reference/scheduling/config/ for example configs there (which also shows config with multiple profiles)
