### ISSUE TITLE
Coscheduling:uninstall error

### ISSUE THREAD

**Issue by liiitleboy** [kubernetes-sigs/scheduler-plugins#123]
I want to try to use this component offline, so I need to uninstall and then install it again. But I had a problem with the uninstall process. Do I need to connect to the Internet when I unload? I push the image（acs/kube-scheduler-update && acs/kube-scheduler） to my docker warehouse. Can I use it offline?Thanks.

我想尝试离线使用这个组件，所以我需要先进行卸载，然后重新安装。但是我在卸载过程遇到了问题。卸载也需要联网吗，我把acs/kube-scheduler-update和acs/kube-scheduler镜像push到自己的docker仓库，是不是就可以离线使用了？谢谢兄弟，能说一下吗。

`./helm uninstall ack-coscheduling -n kube-system`

but get error
`Error: uninstallation completed with 1 error(s): timed out waiting for the condition`

scheduler-rollback-8dfv5          0/1     Pending

`message: '0/2 nodes are available: 1 node(s) didn''t match node selector, 1 node(s)
      didn''t match pod affinity/anti-affinity.'`

this is the scheduler-rollback-8dfv5
```spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: component
            operator: In
            values:
            - kube-scheduler
        topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/type
            operator: In
            values:
            - scheduler-rollback
        topologyKey: kubernetes.io/hostname
````

this is my master label
```Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=tjtx-90-15.58os.org
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
```

**Comment by Huang-Wei** [comment]
> `./helm uninstall ack-coscheduling -n kube-system`
> 
> but get error
> `Error: uninstallation completed with 1 error(s): timed out waiting for the condition`

Given it's using ACK helm charts. I guess raising an issue in ACK github or submitting an ACK ticket would better help you resolve this issue.
