### ISSUE TITLE
Unschedulabelable pods may cause co-scheduling group not scheduled in time

### ISSUE THREAD

**Issue by cwdsuzhou** [kubernetes-sigs/scheduler-plugins#125]
Current Pre-filter logic  may add pod to unschedulabe queue when there not enough pods having the same poggroups. There is chance that the pods in  unschedulable queue need long time to dequeue(may>60s), which may case the group can not be scheduled in time.

IMO, we can take one of following actions:
1. remove the logic about checking pod numbers
2. add a Func to framework to solve this issue absolutely, e.g. MoveUnschedulablePodsToActiveQ

/cc @denkensk @yuanchen8911 @Huang-Wei

**Comment by Huang-Wei** [comment]
> Current Pre-filter logic may add pod to unschedulabe queue when there not enough pods having the same poggroups.

The current logic is using podLister to retrieve pods belonging to the same PodGroup. Are you implying at time T, only part of the Pods are present in podLister?

**Comment by cwdsuzhou** [comment]
> > Current Pre-filter logic may add pod to unschedulabe queue when there not enough pods having the same poggroups.
> 
> The current logic is using podLister to retrieve pods belonging to the same PodGroup. Are you implying at time T, only part of the Pods are present in podLister?

Yes

**Comment by Huang-Wei** [comment]
https://github.com/kubernetes/kubernetes/pull/103383 provides a function to move pods proactively.

/milestone v1.22
/remove-lifecycle rotten

**Comment by Huang-Wei** [comment]
/remove-lifecycle stale

I'm going to provide a solution after #287 gets merged.

**Comment by Huang-Wei** [comment]
In the 0.22.6 release, with #299 in place, this should be at least mitigated a lot (although I'd think it's resolved totally).

I'd close it for now. Feel free to reopen if you see this issue on 0.22.6 or newer releases.
