### ISSUE TITLE
how to install coscheduling?

### ISSUE THREAD

**Issue by jackielyc** [kubernetes-sigs/scheduler-plugins#127]
I don‘t find any related information in this git.

**Comment by damemi** [comment]
Hi @jackielyc, to run the coscheduling plugin you'll need to compile it into a custom scheduler and deploy that scheduler in your cluster, then it will be available to enable just like any other plugin.

One option to do that is to just build this repo, which will include all the default (in-tree) scheduler plugins as well as any that are hosted here. Or, you can use this repo as an example to build your own custom scheduler and only import the plugins you need.

Hope that helps!

**Comment by Huang-Wei** [comment]
Fixed by [doc/install.md](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md).
