### ISSUE TITLE
Can I add annotations/labels to the pod during the scheduling process?

### ISSUE THREAD

**Issue by LiWeiJie** [kubernetes-sigs/scheduler-plugins#129]
I deployed a custom scheduler to implement the extension points of preFilter, Filter and QueueSort. 
Is there a way to add the annotations/labels of pod in these extension points?

**Comment by Huang-Wei** [comment]
> Is there a way to add the annotations/labels of pod in these extension points?

It's not recommended to mutate a Pod during the scheduling cycle.

**Comment by xrmzju** [comment]
> I deployed a custom scheduler to implement the extension points of preFilter, Filter and QueueSort.
> Is there a way to add the annotations/labels of pod in these extension points?

binding  api in bind plugin may help this
