### ISSUE TITLE
Proposal: a generic QueueSort plugin 

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#13]
The default priority_sort plugin sorts pods by priority and then timestamp. coscheduling's QueueSort plugin extends the default priority_sort plugin by taking into account PodGroup information to ensure pods from a same PodGroup are sorted together. The current repo also includes a simple QoS plugin that uses Pod QoS class to break a tie for pods with the same priority and timestamp. 

As only one QueueSort plugin is allowed in a single scheduler executable, multiple configurations using different QueueSort plugins and hence multiple schedulers may be required in order to meet different scheduling needs. However,  running multiple schedulers is challenging and undesirable in practice. A generic QueueSort that can meet different scheduling needs hence will be useful.

**We propose a generic QueueSort plugin with advanced sorting features that can meet different scheduling needs (regular pod scheduling, gang scheduling, etc.) and be used by multiple scheduling profiles. An implementation will adapt the current coscheduling implementation by decoupling the QueueSort plugin code  and creating a separate API and a generic QueueSort plugin.** 

1  Create a new API package for PodGroup related information, which can be extended to support other PodGroup-based scheduling enhancement, e.g., re-using and sharing the node scores among a group of pods with homogeneous resource specifications. The bottom line is that coscheduling's PodGroup QueueSort plugin is such a useful feature and can be used for other scenarios as well. Converting it to an independent and extensible plugin is beneficial. 
 
api/types.go
```
package api

type PodGroupList struct {
... 
}
type PodGroupInfo struct {
...
}

func (podGroups *PodGroupList) GetPodGroupInfo(p *framework.PodInfo) (*PodGroupInfo, int) {
...
}

func GetPodGroupLabels(p *v1.Pod) (string, int, error) {
...
}
```

2. Create a  generic QueueSort plugin that takes into account Pod  priority, timestamp, QoS class and PodGroup information in sorting. 
2.1. Compare the pods' priorities.
2.2. Compare the timestamps of the initialization time of PodGroups.
2.3 Compare the QoS classes of regular pods, i.e., the pods do not belong to any PodGroup or the minAvailable is 1.
2.4. Compare the keys of the pods' PodGroups.

pkg/queuesort
```
package queuesort
func (gs *GenericSort) Less(podInfo1 *framework.PodInfo, podInfo2 *framework.PodInfo) bool {
    pod1 := podInfo1.Pod
    pod2 := podInfo2.Pod

    // compare by priority
    priority1 := pod.GetPodPriority(pod1)
    priority2 := pod.GetPodPriority(pod2)

    if priority1 != priority2 {
        return priority1 > priority2
    }

    // compare by timestamp
    pgInfo1,  min1 := gs.podGroups.GetPodGroupInfo(podInfo1)
    pgInfo2, min2 := gs.podGroups.GetPodGroupInfo(podInfo2)
    pgName1 := pgInfo1.Name
    pgName2 := pgInfo2.Name
    time1 := pgInfo1.Timestamp
    time2 := pgInfo2.Timestamp

    if !time1.Equal(time2) {
        return time1.Before(time2)
    }

    // compare by pod QoS class between two pods that do not belong to any podgroup : Guaranteed > Burstable > BestEffort
    if (pgName1 == "" || min1 <= 1) && (pgName2 == "" || min2 <= 1) {
        qos1 := v1qos.GetPodQOS(pod1)
        qos2 := v1qos.GetPodQOS(pod2)

        if qos1 != qos2 {
            if qos1 == v1.PodQOSGuaranteed {
                return true
            } else if qos1 == v1.PodQOSBurstable {
                return qos2 != v1.PodQOSGuaranteed
            } else {
                return qos2 == v1.PodQOSBestEffort
            }
        }
    }

    // compare by podGroup key
    key1 := fmt.Sprintf("%v/%v", podInfo1.Pod.Namespace, pgInfo1.Name)
    key2 := fmt.Sprintf("%v/%v", podInfo2.Pod.Namespace, pgInfo2.Name)
    return key1 < key2
}
```

3. Modify the current coscheduling implementation by removing the PodGroup related structures and functions that are defined in the new API package and using the API to obtain the PodGroup information.

Is this something useful?  We'd really like the feedbacks and suggestions from the community. We have a prototype implementation already.

**Comment by Huang-Wei** [comment]
The idea looks generally good to me. Several questions/comments:

1. Based on the generic QueueSort plugin, are you going to re-use the other parts (non-queuesort) of the current coscheduling plugin? or have a different implementation for the co-scheduling parts?
1. Currently, the QueueSort logic in co-scheduling plugin is quite dependent on the minimum-designed PodGroup spec (not a CRD yet), so are you going to use the same PodGroup spec or propose a generic API (CRD)?
1. If we cannot make a consensus on PodGroup spec, a possible option is to define a high-level interface which the generic QueueSort plugin depends on, so that, if needed, each plugin can implement their PodGroup spec while sharing the same generic QueueSort part. In addition to that, the generic QueueSort plugin can define its argument to adapt to different requirements.
1. The name of `pkg/api` is not recommended to use, we should use `pkg/apis`. And, unless we make the PodGroup a standard CRD, we should avoid putting it to a package called "API" to avoid confusion. IMO `pkg/podgroup` is more appropriate.

**Comment by yuanchen8911** [comment]
> The idea looks generally good to me. Several questions/comments:
> 
Thanks a lot, Wei! Very appreciated it.  Please see my comments inline below.

> 1. Based on the generic QueueSort plugin, are you going to re-use the other parts (non-queuesort) of the current coscheduling plugin? or have a different implementation for the co-scheduling parts?

We will reuse the current co-scheduling implementation/code by removing QueueSort plugin and PodInfoGroup related structures and functions. There will be a few other monitor changes.  So It will be a modified version of coscheduling. 

> 2. Currently, the QueueSort logic in co-scheduling plugin is quite dependent on the minimum-designed PodGroup spec (not a CRD yet), so are you going to use the same PodGroup spec or propose a generic API (CRD)?

As the first step, we will use the same PodGroup spec. but it can be extended with additional parameters in the future. I think  a more general API or CRD will require more thoughts and discussions.

> 3. If we cannot make a consensus on PodGroup spec, a possible option is to define a high-level interface which the generic QueueSort plugin depends on, so that, if needed, each plugin can implement their PodGroup spec while sharing the same generic QueueSort part. In addition to that, the generic QueueSort plugin can define its argument to adapt to different requirements.

That's a good idea, but how about starting with a simple API using the co-scheduling's PodGroup spec.? 

> 4. The name of `pkg/api` is not recommended to use, we should use `pkg/apis`. And, unless we make the PodGroup a standard CRD, we should avoid putting it to a package called "API" to avoid confusion. IMO `pkg/podgroup` is more appropriate.

Sure, we will make the change.

**Comment by yuanchen8911** [comment]
If it makes sense, we'll submit a PR soon.

**Comment by Huang-Wei** [comment]
@yuanchen8911 Thanks. It makes sense to me.

/cc @denkensk

**Comment by wsxiaozhang** [comment]
@yuanchen8911 @Huang-Wei  by adding "2.3 Compare the QoS classes of regular pods" in the "generic queuesort", do you mean the pod QoS class is also a generic condition when dequeue pods during scheduling?  I notice K8s doc of QoS mentioning "Kubernetes uses QoS classes to make decisions about scheduling and evicting Pods." (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/). However, I don't find how QoS takes effect in current scheduler.

**Comment by denkensk** [comment]
@yuanchen8911  Thanks 
> We propose a generic QueueSort plugin with advanced sorting features that can meet different scheduling needs (regular pod scheduling, gang scheduling, etc.) and be used by multiple scheduling profiles. An implementation will adapt the current coscheduling implementation by decoupling the QueueSort plugin code and creating a separate API and a generic QueueSort plugin.

1. I am not sure if the generic `QueueSort plugin` can meet all sorting requirements in the future. If we had two `QueueSort` plugin, their comparison results for the same pods are different, how to merge them in a `QueueSort plugin`. 

2.  +1 for make the PodGroup a standard CRD for coscheduling

/cc @Huang-Wei

**Comment by yuanchen8911** [comment]
> @yuanchen8911 @Huang-Wei by adding "2.3 Compare the QoS classes of regular pods" in the "generic queuesort", do you mean the pod QoS class is also a generic condition when dequeue pods during scheduling? I notice K8s doc of QoS mentioning "Kubernetes uses QoS classes to make decisions about scheduling and evicting Pods." (https://kubernetes.io/docs/tasks/configure-pod-container/quality-service-pod/). However, I don't find how QoS takes effect in current scheduler.

Yes, it's like the simple QoS QueueSort plugin in the current repo, which uses the QoS class to determine which pod should be scheduled first if two pods have the same priority and timestamp.  The reference you provided refers to that the QoS class information is used for scheduling and evicting pods. For example, a guaranteed pod cannot be scheduled onto nodes for which the Kubelet reports a DiskPressure node condition and a burstable pod will be evicted first.

**Comment by yuanchen8911** [comment]
Thanks for the feedbacks  @denkensk  @Huang-Wei!
> 1. I am not sure if the generic `QueueSort plugin` can meet all sorting requirements in the future. If we had two `QueueSort` plugin, their comparison results for the same pods are different, how to merge them in a `QueueSort plugin`.

@denkensk I agree it may not meet all the requirements. We probably should not call it a generic QueueSort plugin. However, PodGroup is a useful notation and can have applications beyond coscheduling. Do you think it would be  useful to decouple coscheduling's QueueSort plugin from the current  implementation and make it more "generic" (at least the name:-) ) for other scheduling profiles to use? For example, when we create a custom scheduler with coscheduling and other profiles, e.g., a default scheduler for regular pods, we don't want to call the QueueSort plugin of the default scheduler "coscheduling", do we?   

> 2. +1 for make the PodGroup a standard CRD for coscheduling

We've discussed three options so far, from the simplest to the most complex.  (1) Our current proposal:  a separate API based on the current PodGroup spec. (with some extensions if needed). (2) A high level interface with implementations provided by different plugins. (3) A CRD. Before we define more use cases and reach an agreement on the spec.,  do you think (1) to (2) to (3) are logical steps to take? 

Thank you!

**Comment by Huang-Wei** [comment]
> However, I don't find how QoS takes effect in current scheduler.

@wsxiaozhang not quite in scheduler. QoS is now more respected during pod eviction in kubelet.

> 1. I am not sure if the generic QueueSort plugin can meet all sorting requirements in the future. If we had two QueueSort plugin, their comparison results for the same pods are different, how to merge them in a QueueSort plugin.

@denkensk My idea is to firstly implement the common sorting requirements. For now the reqs are a) sort by Priority b) sort by timestamp c) sort by PodGroup d) sort by QoS class.

- on one hand, if one of them (e.g., PodGroup) can and must be implemented differently, as you said, result in unstable sorting results. We should avoid hard-coding the logic in the plugin; instead define an interface and just define high-level algorithm template in the generic plugin.
- on the other hand, if we map the common req into arguments, users then can choose to craft the generic plugin by picking up the individual block - e.g., {a and b}, or {a,b and d}. In other words, the plugin behaves dynamically based on arguments.

> Before we define more use cases and reach an agreement on the spec., do you think (1) to (2) to (3) are logical steps to take?

@yuanchen8911 it makes sense to me.

**Comment by zorro786** [comment]
@yuanchen8911 Are you working on this?

**Comment by Huang-Wei** [comment]
@yuanchen8911 is this issue still valid?
