### ISSUE TITLE
Allow dynamic change of scheduler plugins in a profile

### ISSUE THREAD

**Issue by zorro786** [kubernetes-sigs/scheduler-plugins#137]
Currently the configuration of scheduler profiles and plugins within is static for the lifetime of scheduler run. This prevents dynamically changing plugins for valid reasons. For example, [score plugins](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/kep/61-Trimaran-real-load-aware-scheduling/README.md) that depend on real time metrics might need to be substituted with other plugins if metrics are not available for long time. Similarly, based on current state of a cluster, scheduler plugins could be dynamically changed for future intended state.

This can only be achieved currently with a scheduler restart after (re)configuring new plugins for the given profile, which is not a good solution. Request is to add support to do same without disruptions.

**Comment by zorro786** [comment]
@Huang-Wei @ahg-g

**Comment by denkensk** [comment]
+1 
It will be very useful if the configuration can be hot-loaded.

**Comment by zorro786** [comment]
As @ahg-g noted in scheduler SIG meeting, there are two solutions feasible to this and each has its own valid use cases:

1) Changing loaded plugins in registry from within the code.
2) Have an external controller that changes the configuration on the fly.

Since the control of "when to change" lies inside plugin code for metrics, 1) will provide better solution. We should however make it extensible to 2) for future.

**Comment by ahg-g** [comment]
Just to clarify a bit more the two options:

1) Change the set of plugins that get executed in each scheduling cycle. The idea here is to have a "skip" flag for each plugin that is initialized to false at the beginning of each cycle, the skip flag can be set to true through perhaps a PreFilter plugin or perhaps a special extension point that we add specifically for that. However, this is dangerous and will likely make it hard to debug scheduling problems when they arise.


2) Load the configuration dynamically from a ConfigMap. The scheduler would continuously watch for changes in the configmap, and applies any updates when they happen (perhaps by going through the whole initialization sequence again as if it was a restart).

**Comment by damemi** [comment]
I think the 2 options can serve different purposes. Option 1 makes sense for programmatic decisions, for example when if a developer wants to make their plugin dependent on the successful execution of another plugin (as in the case with the metrics/Trimaran plugins)

Option 2 is something that I've seen non-developers request, and I think that it just makes sense for a controller to observe changes to its own config. We have a scheduler operator that handles that in OpenShift, and a native solution would be nice as well.
