### ISSUE TITLE
Custom percentageOfNodesToScore in a PreFilter plugin 

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#14]
The scheduler option _percentageOfNodeToScore_ controls how many nodes should be checked when scheduling a pod. It has an important impact on the scheduling performance.

To better balance the scheduling performance and quality to meet different scheduling needs of diverse workloads, an idea is to introduce a _PreFilter_ plugin that updates the default global value if a  custom threshold is specified through a Pod label.

This plugin sets the value of _percentageOfNodesToScore_ according to the value associated with a label. For example,

```
parameter.scheduling.sigs.k8s.io/percentageOfNodesToScore: 10

```

We’d like to have your input and suggestions, particularly

1. Is it a valid and useful feature?

2. Is it possible to implement? A problem we notice is that the current scheduling framework does not provide a mechanism for plugins to access and update the scheduler options. Would it possible to change the plugin APIs with an additional argument, e.g. a scheduler option pointer?

Thanks a lot!

**Comment by alculquicondor** [comment]
> introduce a PreFilter plugin that updates the default global value if a custom threshold is specified through a Pod label

Given that it would affect other workloads, I don't think it's a good idea.

One approach could be to have the percentageOfNodesToScore to be part of a scheduling profile and then have pods use the profile that gives them better performance if they don't care much about scoring. But if the whole point is to have faster scheduling, there are better things to do:

- Have a faster scheduler (we have introduced several performance improvements in 1.17, 1.18 and 1.19). Have you had a chance to test it?
- If the pods actually don't care much about scoring, you could have a strip down profile that has 0 or very few scoring plugins.

**Comment by yuanchen8911** [comment]
@alculquicondor Thanks for your comment.

1. The idea is to have a  per-pod custom parameter. It should not affect other pods' scheduling performance as it only changes the thresholds for a  pod to be scheduled.   

A PreFilter plugin changes the parameter value for the pod to be scheduled before the Filter stage. When the scheduler (_pkg/scheduler/core/generic_scheduler.go_) calls the following function to calculate _numFeasibleNodesToFind_ ,  it will use the new value of _g.percentageOfNodesToScore_. We will need to save the default global value and reset it for future pods without specifying custom values.

```
// numFeasibleNodesToFind returns the number of feasible nodes that once found, the scheduler stops
// its search for more feasible nodes.
func (g *genericScheduler) numFeasibleNodesToFind(numAllNodes int32) (numNodes int32) {
    if numAllNodes < minFeasibleNodesToFind || g.percentageOfNodesToScore >= 100 {
        return numAllNodes
    }
    adaptivePercentage := g.percentageOfNodesToScore
    if adaptivePercentage <= 0 {
        basePercentageOfNodesToScore := int32(50)
        adaptivePercentage = basePercentageOfNodesToScore - numAllNodes/125
        if adaptivePercentage < minFeasibleNodesPercentageToFind {
            adaptivePercentage = minFeasibleNodesPercentageToFind
        }
    }

    numNodes = numAllNodes * adaptivePercentage / 100
    if numNodes < minFeasibleNodesToFind {
        return minFeasibleNodesToFind
    }

    return numNodes
}
```

2. The need is driven by use cases like scheduling a large number of  pods (e.g., a job/deployment with thousands of pods) in  ultra large clusters (several thousand nodes) where the scheduling performance would be an issues. Our preliminary results show that  percentageOfNodesToScore has a big impact on the scheduling performance. The difference of 10% vs.  50% in a~1k cluster is significant.

**Comment by yuanchen8911** [comment]
Belowis a possible implementation for a dummy CustomParameter PreFilterPlugin.
```
const (
    // Name is the name of the plugin used in the plugin registry and configurations.
    Name = "CustomParameter"
    // PercentageOfNodesToScore specifices how many feasible nodes to return in the filter phase
    PercentageOfNodesToScore = "parameter.scheduling.sigs.k8s.io/percentageOfNodesToScore"
)

// CustomParameters is a plugin that sets scheduling configuation parameters specified as pod labels.
// The current implementation supports PercentageOfNodesToScore only.
type CustomParameters struct {
    parameterNames []string
}

var _ framework.PreFilterPlugin = &CustomParameters{}

// Name returns the plugin's name.
func (cp *CustomParameters) Name() string {
    return Name
}

// PreFilter is a dummy plugin that sets PercentageOfNodesToScore if specified in Pod's label.
func (cp *CustomParameters) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) *framework.Status {

    for _, paramName := range cp.parameterNames {
        value := getParameterValue(pod, paramName)
        switch paramName {
        case PercentageOfNodesToScore:
            if value == "" {
                klog.Infof("Custom parameter-- Pod: %s, PercentageOfNodesToScore: <default value>", pod.Name)
            } else {
                val, err := strconv.Atoi(value)
                if err != nil {
                    return framework.NewStatus(framework.Error, "Invalid prameter value for percentageOfnodesTorScore: %v", value)
                }
                //TODO: set percentageOfNodesToScore in sched.Algorithm.percentageOfNodesToScore (Not Supported Yet)
                ...
                klog.Infof("Custom Parameter-- Pod: %s, PercentageOfNodesToScore: %d\n", pod.Name, val)
            }
        }
    }
    return framework.NewStatus(framework.Success, "")
}
```

**Comment by alculquicondor** [comment]
1. why not modify your global default?
1. Have you tested 1.18 and 1.19?

**Comment by yuanchen8911** [comment]
> * why not modify your global default?

The motivation is to customize the threshold for different workloads running  in the same cluster. For example, a long running service that cares a lot about the  scheduling quality will use a high thresholds to achieve a better scheduling quality while a large batch job that is looking for a quick turnaround may set a =lower threshold for a quicker scheduling.

> * Have you tested 1.18 and 1.19?

We use 1.18.

Again, the assumption is scheduling a large number of pods  (> 1k pods) in an ultra large cluster (>1k nodes).

**Comment by alculquicondor** [comment]
> Again, the assumption is scheduling a large number of pods (> 1k pods) in an ultra large cluster (>1k nodes).

We run such big clusters as well, except that we only target 100 pods/s

You could consider using [multiple profiles](https://github.com/kubernetes/enhancements/issues/1451) and disabling some (or all) plugins in one of them. Then, your jobs use the optimized profile. And you can pair that with a percentage of nodes to score that makes sense for both types of workloads, such as 30%. Note that we use the percentage in a windowed fashion, so eventually all nodes are tested for a big enough deployment.
If that's not enough, we can make a case for adding percentage of nodes to score to a profile.

Making a pod directly affect scheduler configuration might not be the best API. Scheduling profiles is a much better way.

**Comment by yuanchen8911** [comment]
Thanks,  per profile threshold will be certainly helpful, but the values will  be set statistically. A PreFilter plugin can support dynamic and adaptive threshold at single pod level. I agree we need to think more about the use cases and tradeoff.

**Comment by Huang-Wei** [comment]
Atm `PercentageOfNodesToScore` is a [global parameter](https://github.com/kubernetes/kubernetes/blob/66ff1ae53659fea7885f954510676430cc318b68/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L75), I'm not a fan of changing it in PreFilter or other places.

Given that `PercentageOfNodesToScorec` is used in `numFeasibleNodesToFind()`, which is called in every scheduling cycle, so it makes more sense to me to change it to be a profile-level parameter, so that users just configure different thresholds to filter/score in each profile.

**Comment by Huang-Wei** [comment]
A bit surprising fact:`PercentageOfNodesToScore` has nothing to do with Scoring... I _thought_ it impacts both Filter and Score, but it does nothing in Score ([g.prioritizeNodes](https://github.com/kubernetes/kubernetes/blob/66ff1ae53659fea7885f954510676430cc318b68/pkg/scheduler/core/generic_scheduler.go#L645)).

**Comment by yuanchen8911** [comment]
> A side note:`PercentageOfNodesToScore` has nothing to do with Scoring... I _thought_ it impacts both Filter and Score, but it does nothing in Score ([g.prioritizeNodes](https://github.com/kubernetes/kubernetes/blob/66ff1ae53659fea7885f954510676430cc318b68/pkg/scheduler/core/generic_scheduler.go#L645)).
> 
> 
> 
> Anyway, if we read it as "the eventual percentage of nodes to score", then it's not that misleading.

It controls the number of feasible nodes to find by the filter stage and hence affects how many nodes will be scored and ranked in the score stage. It hence affects the scoring stage’s  performance, which can be the bottleneck.

**Comment by yuanchen8911** [comment]
> Atm `PercentageOfNodesToScore` is a [global parameter](https://github.com/kubernetes/kubernetes/blob/66ff1ae53659fea7885f954510676430cc318b68/staging/src/k8s.io/kube-scheduler/config/v1beta1/types.go#L75), I'm not a fan of changing it in PreFilter or other places.
> 
> 
> 
> Given that `PercentageOfNodesToScorec` is used in `numFeasibleNodesToFind()`, which is called in every scheduling cycle, so it makes more sense to me to change it to be a profile-level parameter, so that users just configure different thresholds to filter/score in each profile. 

Thanks, we will explore this option.

**Comment by yuanchen8911** [comment]
Opened an issue: support per scheduling profile configuration to kube-scheduler https://github.com/kubernetes/kubernetes/issues/93270

**Comment by alculquicondor** [comment]
/close

discussion moved to kubernetes/kubernetes#93270
