### ISSUE TITLE
Write scheduler plugin in python

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes-sigs/scheduler-plugins#140]
Hi,
I would like to write a plugin for  extension points, like "Filter", "Permit", "PreBind" in python.

I expect that this should be feasible.

Can someone please point me to the relevant doc and a sample ?

Thank you in advance!
--Renuka

**Comment by Huang-Wei** [comment]
@renukamanavalan Given that the plugins need to be compiled with the scheduler base, so unfortunately it's not applicable to write plugins using non-Go languages.

**Comment by AlexeyPerevalov** [comment]
@renukamanavalan 
Probably the way of calling python code will be as follows GO -> CGO -> PYTHON code, or GO -> RPC -> PYTHON, but it's looks like over-engineering.
From my point of view, if you just want to assign node to pod (IOW to track down new pods and set nodeName into it and then patch) it's better just to use official python client: https://github.com/kubernetes-client/python
For reference how to do it(in case of scheduling) you can see: https://github.com/Viasat/nhd.git.
In this case it's up to you follow or not current scheduler's plugin architecture (I mean Filter, .., Bind callbacks) or design you own internal architecture.

**Comment by renukamanavalan** [comment]
Thanks Alexey!
This is very helpful.
