### ISSUE TITLE
Consultation request: Need to add a custom steps in scheduling

### ISSUE THREAD

**Issue by renukamanavalan** [kubernetes-sigs/scheduler-plugins#141]
Hi all,
**Requirement:** 
Install a daemonset across all matching nodes. When kubernetes is ready to create a pod for a node, I would like to do few things.

a) **Limit concurrent updates to N**,
     Say kubernetes is about to deploy to 100 nodes, say N=2, I would like to streamline updates as 2 at a time.
     Create pods for 2 node, wait for them to go running/timwout and create next two. Repeat this till all 100 are done.

b) **Set failing limit as N**
     Say Kubernetes is about to deploy for 100 nodes, limiting concurrent updates to a configured value (point above), if N count
     or perentage of pods fail to come up, abort this schedule completely, which includes reverting the updates that are done.

c) **Pre-check by an external-resource**:
For each node, just before creating a pod, invoke an external resource, to do some pre-check. Upon external resource    returning "OK", proceed to create a pod
   
d) **Post-check by an external-resource**
Upon successful creation of pod, call an external resource for a post-check. If post-check is good, proceed, else abort this deployment.

I was planning to use plugins for extension points.

**Request:**:
1) Can you please give me suggestions/guidelines on how to accomplish the above ?
2) If there are any samples for reference, please provide.

**Comment by damemi** [comment]
a) and b) sound similar to coscheduling or batch scheduling to me. c) could be an extender, or maybe some kind of bind/post-bind plugin? (depending on what kind of external resource you're referring to).

for d), I think that is out of scope of the scheduler, since once a pod is created we don't care about it anymore. This is probably more like a readiness/liveness check or perhaps a deployment hook...

@Huang-Wei wdyt?

**Comment by Huang-Wei** [comment]
Hmm... Given that you want to control the **creation** behavior (sequence or pre/post check) of Pods, IMO it's more favorable to be accomplished using a customized controller or admission webhook instead of scheduler.

**Comment by denkensk** [comment]
> Hmm... Given that you want to control the **creation** behavior (sequence or pre/post check) of Pods, IMO it's more favorable to be accomplished using a customized controller or admission webhook instead of scheduler.

+1  
a) b) c) is to control the behavior of pod creation. I think an independent operator is more favorable. 
Webhook is better than prefilter for c). ^_^ But Prefilter is also a choice.
