### ISSUE TITLE
Support Trimaran Plugins to run independently in clusters with pre-installed monitoring stack

### ISSUE THREAD

**Issue by wangchen615** [kubernetes-sigs/scheduler-plugins#144]
Right now, trimaran plugins rely on an external data service [`load-watcher`](https://github.com/paypal/load-watcher) to be running in the same cluster to expose real-time node metrics.

We want to add support in Trimaran to also use `load-watcher` as in a library mode. 

In this way, `load-watcher` libs can be directly imported into trimaran plugins. `load-watcher` libraries can retrieve data directly from various monitoring stacks, including Kubernetes metric client, Prometheus Client, and SignalFx Client. So when clusters are pre-installed with the above monitoring stack, Trimaran plugins can run independently without deploying an additional `load-watcher` service in the cluster.

**Comment by seanmalloy** [comment]
@wangchen615 can this be closed now that #152 is merged?

**Comment by wangchen615** [comment]
> @wangchen615 can this be closed now that #152 is merged?

I thought it would be automatically be closed. But yes, definitely. Thanks.
