### ISSUE TITLE
Script to verify incorrect CRD yaml

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#151]
Per https://github.com/kubernetes-sigs/scheduler-plugins/pull/148#issuecomment-783950924, it's favorable to have a script verifying incorrect/missing specs in individual CRD yaml, and automate this in CI.

/kind feature
/assign @penglei

**Comment by Huang-Wei** [comment]
@penglei I cannot assign it to you. But you can `/assign` to get it self-assigned.

**Comment by pravarag** [comment]
@Huang-Wei I'd like to work on this issue

/assign

**Comment by pravarag** [comment]
@Huang-Wei I'm guessing these are the steps I can take while trying to write a script for verifying CRD yamls as mentioned here: https://github.com/kubernetes-sigs/scheduler-plugins/pull/148#issuecomment-783950924

**Comment by Huang-Wei** [comment]
@pravarag yes, that's correct. Moreover, you can also get inspiring ideas from the ["hack"](https://github.com/kubernetes/kubernetes/tree/master/hack) scripts under the k/k repo.

**Comment by pravarag** [comment]
@Huang-Wei @damemi I've created a WIP PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/222 though I'm still looking for ways to test the script. Kindly suggest if any changes/updates are required in the code.

**Comment by Huang-Wei** [comment]
Fixed by #222.
