### ISSUE TITLE
CapacityScheduling plugin enhancements 

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#154]
@denkensk and I had a discussion about new features to the current CapacityScheduling plugin. Comments and feedback will be appreciated. 

1. Per PriorityClass ElasticQuota

   Extend the current ElasticQuota to support per PriorityClass min and max quotas. A namespace's PriorityClass quotas can  only be shared with the same PriorityClass quotas of other namespaces.  

   We will need to extend ElasticQuota CRD and the plugin implementation. Code contributions are higly welcome. 

2. ElasticQuotas within a group of namespaces

    Instead of sharing quotas among all namespace, users can define a group of namespaces (e.g., namespaces belonging to a team) that can share resource quotas with each other. In general,  a hierarchical tree structure can be constructed for more flexible resource quota between namespaces.  

   We will prepare and submit a KEP.

3. ElasticQuota for resource limits

   Current resource quotas define min and max for resource requests only. Should we generalize it to resource limits? 

@Huang-Wei @xujyan

**Comment by yingjianwu199868** [comment]
Hi all,

Quick question:
Is there any update about any of these three implementations?

Thanks,
Steven

**Comment by denkensk** [comment]
@yuanchen8911 
The discussion about the CapacityScheduling plugin is initial discussion. All of these have not yet been determined whether they need to be implemented. Do you have any other ideas or feedback about these？

**Comment by denkensk** [comment]
@yingjianwu199868 
The discussion about the CapacityScheduling plugin is initial discussion. All of these have not yet been determined whether they need to be implemented. Do you have any other ideas or feedback about these？

**Comment by yingjianwu199868** [comment]
@denkensk 

Sorry for the late reply.
I am currently looking into the second point mentioned previously, which is related to allowing one namespace to borrow unused resources from a subset of the namespacecs.

I see that there is another SIG project called Hierarchical Namespace, which might be helpful, and I have attached the link below.
https://github.com/kubernetes-sigs/hierarchical-namespaces

I wonder what's your opinion for integrating capacity scheduler with this SIG project.

My current high-level thought is:
1. For people who want to enable the sharing feature only to a subset of the namespace, they need to deploy hierarchical namespace themselves.
2. I believe for the capacity scheduler project, we only need to use the code generator to generate lister and informer for one of the crd, and let our scheduler watch any changes for this crd.
https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/config/crd/bases/hnc.x-k8s.io_hierarchyconfigurations.yaml

Feel free to share your thought.
I am pretty new to Kubernetes Open Source Code so I may be wrong.

Thanks,
Steven

**Comment by charleszheng44** [comment]
@yuanchen8911 have you submitted the KEP for elastic quota? If yes, could you share the link? Thanks

**Comment by denkensk** [comment]
@yingjianwu199868 
I'm really sorry. I seem to have missed your reply.
We have also discussed this issue internally recently about integrating capacity scheduler with hierarchical-namespaces.
Do you have time to write a KEP for it？

FYI: This is a version of our internal implementation without hierarchical-namespaces. https://www.alibabacloud.com/help/doc-detail/213695.htm?spm=a3c0i.23458820.2359477120.1.61bb6e9bahlRqb （Different languages can be switched in the upper right corner）

**Comment by denkensk** [comment]
@charleszheng44  
Nice to meet you. Do you have the same needs? Can you share your ideas?

**Comment by charleszheng44** [comment]
> @charleszheng44 Nice to meet you. Do you have the same needs? Can you share your ideas?

Hi @denkensk, Yes. We need to calculate the quota of multiple namespaces belonging to the same user.

**Comment by charleszheng44** [comment]
@denkensk We need to handle the 1-to-m case and we are using the [VirtualCluster](https://github.com/kubernetes-sigs/cluster-api-provider-nested/tree/main/virtualcluster) to manage multiple namespaces for each user.

**Comment by yuanchen8911** [comment]
@yuanchen8911 test check http://badguy.com
