### ISSUE TITLE
Release 0.19.x

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/scheduler-plugins#161]
It's been a while since the last release. The master branch has been updated to be compatible with k8s v1.19. I'm proposing that a scheduler-plugins v0.19.x release be created.

Here is my rough checklist of items to complete for this effort.

- [x] update end user install docs #150 
- [x] update end user install docs for new ARM64 container images
- [x] do the [release process](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/release-guide.md) to create branches and tag

**Comment by seanmalloy** [comment]
@Huang-Wei and @denkensk does this sound reasonable? Am I missing any critical items that must be finished before another release is created?

I can submit a PR soon-ish to update the end user docs with the ARM64 container image details. @xq2005 would you be willing to handle the doc updates to resolve #150?

**Comment by Huang-Wei** [comment]
@seanmalloy Thanks for driving this. The process looks pretty decent.

I just cut a `release-1.19` release and created a tag `v0.19.8`. I suppose the tag push would automatically create a staging image, right? But seems nothing gets generated at gcr.io/k8s-staging-scheduler-plugins/kube-scheduler. Did I miss something?

**Comment by seanmalloy** [comment]
> @seanmalloy Thanks for driving this. The process looks pretty decent.
> 
> I just cut a `release-1.19` release and created a tag `v0.19.8`. I suppose the tag push would automatically create a staging image, right? But seems nothing gets generated at gcr.io/k8s-staging-scheduler-plugins/kube-scheduler. Did I miss something?

@Huang-Wei I'll check it tomorrow.

**Comment by seanmalloy** [comment]
I see the kube-scheduler images is in the staging repo:
<img width="425" alt="Screen Shot 2021-03-11 at 9 13 08 AM" src="https://user-images.githubusercontent.com/685221/110808949-17989b00-824a-11eb-8303-741456478a6b.png">

https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/kube-scheduler?gcrImageListsize=30


I see the controller images is in the staging repo:
<img width="369" alt="Screen Shot 2021-03-11 at 9 14 53 AM" src="https://user-images.githubusercontent.com/685221/110809158-43b41c00-824a-11eb-8ac2-5475532a373b.png">


https://console.cloud.google.com/gcr/images/k8s-staging-scheduler-plugins/GLOBAL/controller?gcrImageListsize=30

**Comment by seanmalloy** [comment]
I'll submit the image promotion PR soon.

**Comment by seanmalloy** [comment]
Here is the image promotion PR: https://github.com/kubernetes/k8s.io/pull/1780

**Comment by seanmalloy** [comment]
First docs PR: https://github.com/kubernetes-sigs/scheduler-plugins/pull/162

**Comment by seanmalloy** [comment]
I confirmed the container images are now available. Just need to finish off the end user docs now.

```
docker pull k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.19.8
docker pull k8s.gcr.io/scheduler-plugins/controller:v0.19.8
```

**Comment by seanmalloy** [comment]
Last PR before I consider this closed, https://github.com/kubernetes-sigs/scheduler-plugins/pull/167.

**Comment by seanmalloy** [comment]
Everything is completed. Closing.

**Comment by Huang-Wei** [comment]
Thanks @seanmalloy !
