### ISSUE TITLE
controller should reconcile the status of PodGroup

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#166]
In the latest code, the controller doesn't quite reconcile the status of PodGroup:

- [x] Field `status.Scheduled` not displayed - fixed by #166

    If a PodGroup is created, we'd expect all [status fields](https://github.com/kubernetes-sigs/scheduler-plugins/blob/e7ca5ee3ba91f98af11c176f7fec2e2ab9e9cc0c/pkg/apis/scheduling/v1alpha1/types.go#L155-L174) to display properly. But for now it's only `status.phase`.
    
    ```
    $ k get pg pg1 -o yaml 
    ...
    status:
      phase: pending
    ```

- [ ] `status.phase` not reconciled well

    If a PodGroup doesn't have any associated Pods, it should stay in `Pending` state. However, it sometimes stays in `Running` (or other state). We's expect status to be always reconciled.

/kind bug

**Comment by Huang-Wei** [comment]
@cwdsuzhou @denkensk could you take some time to look into the above 2 issues?

**Comment by cwdsuzhou** [comment]
I will open a PR to resolve these issues

**Comment by cwdsuzhou** [comment]
@Huang-Wei  

to  resolve the `1st` issue, we just need remove `omitempty` of these fields.

about the 2nd issue, I have different opinions. If a group has been `Running` , it should not go back to `Pending` again. IMO, we should covert it to `Success`, `Failed` or `Unknown`. If no associated Pods exist, `Unknown` would be better. For other status, conversion should be similar.

WDYT?

**Comment by Huang-Wei** [comment]
> to resolve the `1st` issue, we just need remove `omitempty` of these fields.

Thanks. Please raise a PR fixing that.

> IMO, we should covert it to `Success`, `Failed` or `Unknown`. If no associated Pods exist, `Unknown` would be better. For other status, conversion should be similar.

It sounds strange to use different states to show whether a PodGroup has been scheduled successfully **once** or not. Shouldn't the state just stick to its actual state, in a "stateless" manner?

**Comment by cwdsuzhou** [comment]
> > to resolve the `1st` issue, we just need remove `omitempty` of these fields.
> 
> Thanks. Please raise a PR fixing that.

This does not work. I raise a PR, just add default value to status

**Comment by cwdsuzhou** [comment]
> It sounds strange to use different states to show whether a PodGroup has been scheduled successfully **once** or not. Shouldn't the state just stick to its actual state, in a "stateless" manner?
 

Usually, a PG would be related to a job, from the perspective of a job, job status should not be from `Running` to `Pending`

**Comment by Huang-Wei** [comment]
/reopen
as the 2nd item hasn't been resolved.

I think the workflow of how status changes need to rethink a bit. Probably it should be accompanied by informational messages, so that users can know what phase a PodGropu is in, for what reason.

**Comment by JaneLiuL** [comment]
Is it scenario as below is correct? Actually I am really confuse about the PodGroup status. If my understand is correct, I would like to create a doc to describe first.
@Huang-Wei 

Case 1: 
Create podGroup minMember=2    , podGroup.status.Phase=pending
PodNum=0                                      , podGroup.status.Phase=pending
PodNum=2 (Pod all success)           , podGroup.status.Phase=pending-->PreScheduling-->Scheduling-->Finished-->Scheduled
PodNum=1 (Pod all success)           , podGroup.status.Phase=Scheduled-->Failed
PodNum=0                                      , podGroup.status.Phase=Failed-->Pending

Case 2:
Create podGroup minMember=2    , podGroup.status.Phase=pending
PodNum=0                                      , podGroup.status.Phase=pending
PodNum=2 (Pod all fail to start, like imagePullFail)  , podGroup.status.Phase=pending--->PreScheduling-->Scheduling-->Failed
PodNum=2 (Pod all success)           , podGroup.status.Phase=Failed--->PreScheduling-->Scheduling-->Scheduled
PodNum=0                                      , podGroup.status.Phase=Scheduled-->Pending
