### ISSUE TITLE
Update Dependencies to k8s v1.20

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/scheduler-plugins#171]
Now that the scheduler-plugins v0.19.x(k8s v1.19) release and branch have been created I believe the master branch could now be updated for k8s v1.20.

/kind feature

**Comment by seanmalloy** [comment]
Looks like @Huang-Wei has a wip PR #177 

/unassign

**Comment by Huang-Wei** [comment]
> I'd like to attempt this one.

Apologize that I didn't see your comment... I'd like to hold #177 for a while until we have a v0.19.9 release.

My plan is to include #143 in the new v0.19.9 release, and bump the master branch to v1.20 (#177).

@seanmalloy are you interested in cutting a v0.19.9 release?

**Comment by seanmalloy** [comment]
> > I'd like to attempt this one.
> 
> Apologize that I didn't see your comment... I'd like to hold #177 for a while until we have a v0.19.9 release.
> 
> My plan is to include #143 in the new v0.19.9 release, and bump the master branch to v1.20 (#177).
> 
> @seanmalloy are you interested in cutting a v0.19.9 release?

@Huang-Wei yes I can bump the dependencies to k8s v1.19.9 to prepare for a scheduler-plugins v0.19.9 release.

**Comment by Huang-Wei** [comment]
It's already completed.
