### ISSUE TITLE
test: reuse upstream integration framework utilities

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#178]
I'm wondering if we can reuse the upstream integration framework utilities, to create apiExtensionClient ([integration/framework/test_server.go](https://github.com/kubernetes/kubernetes/blob/v1.19.9/test/integration/framework/test_server.go)), instead of duplicating them in our repo:

- test/util/apiserver.go
- test/util/extension.go
- ...

/kind cleanup

**Comment by Huang-Wei** [comment]
@cwdsuzhou what's the intention when you originally duplicated those files?

**Comment by yuchen-sun** [comment]
hello @Huang-Wei Do you already know his intention for doing so ?
When I was doing cleanup work, I ran into 2 problems.
1. apiextensions.k8s.io not found in TestFramework api server. 
2. Why not process it here instead of refactoring it in the upstream https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/util/scheduler.go#L31

**Comment by cwdsuzhou** [comment]
Sorry for delay.

as @yuchen-sun  told, extension api server is not supported it the framework. That is may initial intension.


> hello @Huang-Wei Do you already know his intention for doing so ?
> When I was doing cleanup work, I ran into 2 problems.
> 
> 1. apiextensions.k8s.io not found in TestFramework api server.
> 2. Why not process it here instead of refactoring it in the upstream https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/util/scheduler.go#L31

**Comment by pravarag** [comment]
I would like to work on this issue @Huang-Wei , will post the related queries here.

**Comment by Huang-Wei** [comment]
Sure, you can /assign to yourself.

**Comment by pravarag** [comment]
Hi @Huang-Wei @cwdsuzhou @yuanchen8911 from the discussions in this comment: https://github.com/kubernetes-sigs/scheduler-plugins/issues/178#issuecomment-873551331 and https://github.com/kubernetes-sigs/scheduler-plugins/issues/178#issuecomment-879537151, my understanding is we want to move the functionality in `test/util/apiserver.go` and `/test/util/extension.go` to mabye in this file: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/util/scheduler.go#L31 ? or we want to totally implement the utilities from here: https://github.com/kubernetes/kubernetes/blob/v1.19.9/test/integration/framework/test_server.go ?

**Comment by Huang-Wei** [comment]
@pravarag I partially implemented this in #287, but that approach has to do some tricks to import static testdata files. And that aspect can be optimized.

You can work on the optimization, along with removing the files like test/util/apiserver.go.

**Comment by pravarag** [comment]
Hi @Huang-Wei thanks for mentioning the implementations done in #287. I went through [kubernetes/testserver.go](https://github.com/kubernetes/kubernetes/blob/v1.19.9/test/integration/framework/test_server.go) and I found that [this](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/util/apiserver.go) test is an exact copy of it. So apart from removing it, as you have mentioned [here](https://github.com/kubernetes-sigs/scheduler-plugins/issues/178#issuecomment-937305173) - if possible could you please direct me towards the upstream logic which you have mentioned in k/k apart from that in k/testserver.go.

Also, regarding this [cert-generation](https://github.com/kubernetes-sigs/scheduler-plugins/pull/287#discussion_r746853916) - is this going to be a part of CI job or maybe a separate setup-script?

**Comment by Huang-Wei** [comment]
> I went through [kubernetes/testserver.go](https://github.com/kubernetes/kubernetes/blob/v1.19.9/test/integration/framework/test_server.go) and I found that [this](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/util/apiserver.go) test is an exact copy of it.

Yes, a "dated" copy actually :) Now this file along with others (like fixtures.go, aggregator.go, extension.go) are not needed.

> if possible could you please direct me towards the upstream logic which you have mentioned in k/k apart from that in k/testserver.go.

The upstream testapiserver logic used testdata files, which cannot be easily vendored. (currently I used a symbolic trick to achieve this)

> Also, regarding this cert-generation - is this going to be a part of CI job or maybe a separate setup-script?

Nope, I'd like this to be part of the go code. This is why I left the aforementioned dated files there - some of the code there can be leveraged.

**Comment by pravarag** [comment]
Thanks @Huang-Wei, I've started working on the optimization of the changes as you suggested for the integration tests and removal of files (like apiserver.go, fixtures.go, aggregator.go etc). Also for the generation of cert, just wanted to know if that's something which is being used under kubernetes/kubernetes that I can take reference from? Otherwise the only way I can think of is using the `cfssl` via go get like:

```
go get -u github.com/cloudflare/cfssl/cmd/cfssl
```
And then create rest of the configuration jsons?

**Comment by Huang-Wei** [comment]
@pravarag can you refer to the logic like:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/455cb8a6536e8bf8b1d856812851c545255295b4/test/util/apiserver.go#L63-L81

**Comment by pravarag** [comment]
@Huang-Wei  I've created a draft PR, currently working on adding more changes and will update the PR.

**Comment by Huang-Wei** [comment]
I'm going to track integration test improvement in #339.
