### ISSUE TITLE
helm support and doc update

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#189]
Add helm support to ease the installation of scheduler-plugins:

- [ ] helm chart to run scheduler-plugin as a single scheduler (i.e., replacing the vanilla scheduler). This may need some extra manual steps
- [ ] help chart to run scheduler-plugin as a second scheduler

Also, we should update the doc:

- [ ] update the doc specifying the steps to use helm chart

**Comment by FingerLiu** [comment]
Would like to help.
/assign
@Huang-Wei please check if the following  task split is OK:
1. add two helm chart in manifests dir
2. add helm chart install guide in `doc/install.md`

**Comment by Huang-Wei** [comment]
Looks good. Thanks for offering the help!

**Comment by FingerLiu** [comment]
> Add helm support to ease the installation of scheduler-plugins:
> 
> * [ ]  helm chart to run scheduler-plugin as a single scheduler (i.e., replacing the vanilla scheduler). This may need some extra manual steps
> * [ ]  help chart to run scheduler-plugin as a second scheduler
> 
> Also, we should update the doc:
> 
> * [ ]  update the doc specifying the steps to use helm chart

@Huang-Wei Hi, I found it a like complex to add a generic helm chart to run scheduler-plugin as a single scheduler since it depends on how the default scheduler is deployed. So I just added a chart to run it as a second scheduler in this PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/193.

**Comment by seanmalloy** [comment]
A helm chart and docs have been added for running the scheduler plugins as second scheduler.

Still need to figure out how to have a helm chart deploy the scheduler plugins as a single scheduler. As mentioned by @FingerLiu this is tricky. It might not even be reasonable to do this with helm.

/remove-lifecycle stale
