### ISSUE TITLE
Does noderesource plugin support GPU? 

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#191]
If not,  how hard would it be to extend the plugin to include GPU resources? 

https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/noderesources

@Huang-Wei

**Comment by yuanchen8911** [comment]
If I'm understanding it correctly, it should work for GPU. GPU fits in the  category (`IsExtendedResourceName`)

```
	default:
		if schedutil.IsScalarResourceName(resource) {
			return nodeInfo.Allocatable.ScalarResources[resource], (nodeInfo.Requested.ScalarResources[resource] + podRequest)
		}
	}
```

https://github.com/kubernetes-sigs/scheduler-plugins/blob/7d969ada99a1af04e48b646c7770a261d8761f39/pkg/noderesources/resource_allocation.go#L108

**Comment by Huang-Wei** [comment]
> If I'm understanding it correctly, it should work for GPU.

Yes.

**Comment by yuanchen8911** [comment]
Thanks.
