### ISSUE TITLE
About NodeResourcesAllocatable

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#192]
It looks like [noderesources plugin](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/noderesources)  actually provides a general framework (template) for facilitating the implementations of different scoring functions. The plugin defines a scorer function variable  `func(requested, allocatable resourceToValueMap, includeVolumes bool, requestedVolumes int, allocatableVolumes int) int64` with  `resource requested`, `allocatable` and `volume` as parameters.  

Though the current scorer function only uses the absolute number of allocatable to score a node as described in the [KEP](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/48-node-resources-allocatable-scoring),  Most/LeastAllocated and other variations can be easily implemented by simply providing a different scoring function. 

Current KEP and README are very specific for the case that uses the absolute number of Allocatable in scoring. I was wondering if we should update the docs to reflect the scope of the code and implementation. Or do we you have a plan to use it as a template to implement more scoring plugins?

```
type resourceAllocationScorer struct {
	Name                string
	scorer              func(requested, allocatable resourceToValueMap, includeVolumes bool, requestedVolumes int, allocatableVolumes int) int64
	resourceToWeightMap resourceToWeightMap
}
 func(resourceToValueMap, resourceToValueMap, bool, int, int) int64 {
	return func(requested, allocable resourceToValueMap, includeVolumes bool, requestedVolumes int, allocatableVolumes int) int64 {
		// TODO: consider volumes in scoring.
		var nodeScore, weightSum int64
		for resource, weight := range resToWeightMap {
			resourceScore := score(allocable[resource], mode)
			nodeScore += resourceScore * weight
			weightSum += weight
		}
		return nodeScore / weightSum
	}
}
```
@Huang-Wei

**Comment by Huang-Wei** [comment]
@yuanchen8911 in k8s 1.22, a new noderesources Score plugin (https://github.com/kubernetes/kubernetes/pull/101822) unified old individual resource scoring plugins by providing a "ScoringStrategy".

If @patricklundquist is interested, a PR is welcome to merge NodeResourcesAllocatable plugin to the upstream.

But please note that, with current noderesources Score plugin implementation, only one "ScoringStrategy" can be specified.

**Comment by patricklundquist** [comment]
/reopen

Still planning to take a look at this. Haven't had a chance yet...
