### ISSUE TITLE
coscheduling: check minAvailable of all pods in a PodGroup

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#20]
I think we should check minAvailable value of each pod in a PodGroup and make sure the values of the same PodGroup are the same. Also, minAvailable can be part of PodGroupInfo as the KEP does. WDYT? @Huang-Wei @denkensk

**Comment by denkensk** [comment]
Thanks @yuanchen8911  It's make sense to me.  
This's the weakness to define `PodGroup` by the label of Pod. We can only assume that minAvailable value of each pod in a PodGroup are same. I agree to check minAvailable value in `PreFilter`.  But how to deal with these pods with different value of the same PodGroup? Maybe we can reject it in `PreFilter` but it will reschedule later.

**Comment by yuanchen8911** [comment]
> Thanks @yuanchen8911  It's make sense to me.  
> 
> This's the weakness to define `PodGroup` by the label of Pod. We can only assume that minAvailable value of each pod in a PodGroup are same. I agree to check minAvailable value in `PreFilter`.  But how to deal with these pods with different value of the same PodGroup? Maybe we can reject it in `PreFilter` but it will reschedule later.

A simpler solution is to (1) set the number according to the first pod’s label value in getPodGroupInfo (2) ignore the other pods’ label values inPreFilter  (can check and report a warning if different in log). This should be consistent with the future CRD implementation. @denkensk

**Comment by yuanchen8911** [comment]
> > Thanks @yuanchen8911  It's make sense to me.  
> > 
> > This's the weakness to define `PodGroup` by the label of Pod. We can only assume that minAvailable value of each pod in a PodGroup are same. I agree to check minAvailable value in `PreFilter`.  But how to deal with these pods with different value of the same PodGroup? Maybe we can reject it in `PreFilter` but it will reschedule later.
> 
> A simple solution is to (1) set the number according to the first pod’s label value in getPodGroupInfo (2) ignore the other pods’ label values inPreFilter  (can check and report a warning if different in log). This should be consistent with the future CRD implementation. @denkensk 

The changes required are more complex than what I thought earlier. 

How about considering a regular pod as a PodGroup with a single pod (stored in the PodGroupInfo map). We hence will have a uniform way to compare and process both regular pods and pod groups. For a  regular pod, we can just use its pod name as the group name. 

It will introduce additional overhead for scheduling regular pods (hope not much), but the design and implementation would be improved and more extendable. 

The generic sort plugin discussed in another thread can be considered  a generic PodGroup based QueueSort plugin. 

WDYT @denkensk @Huang-Wei ?

**Comment by yuanchen8911** [comment]
I did a refactoring of the coscheduling code.  Please review the PR #21. Thanks.

**Comment by denkensk** [comment]
Can we close this issue because this is finished in https://github.com/kubernetes-sigs/scheduler-plugins/pull/24 ？
@yuanchen8911

**Comment by seanmalloy** [comment]
> Can we close this issue because this is fixed in #24 ？
> @yuanchen8911

@yuanchen8911 can this issue be closed or is there some outstanding work that still needs to be done?

**Comment by yuanchen8911** [comment]
Yes, let's close it.
