### ISSUE TITLE
Integration tests are falling 

### ISSUE THREAD

**Issue by Tal-or** [kubernetes-sigs/scheduler-plugins#201]
**What happened:**
Calling ```make integration-test``` on a fresh clone of the repo end up with failure.

**What you expected to happen:**
The integration test should pass.

**How to reproduce:** 
1. Clone a fresh copy using git 
2. Execute integration-test using ```make integration-test```

The log can be found [here](https://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_scheduler-plugins/198/pull-scheduler-plugins-integration-test-master/1401448322803175424/build-log.txt )

This log was taken from the failure of the integration test of [PR#198](https://github.com/kubernetes-sigs/scheduler-plugins/pull/198)
But the same log with the same error reproduces on a fresh copy of the repo as well.

**Comment by Huang-Wei** [comment]
@Tal-or it's a known timeout issue, and seems https://github.com/kubernetes/test-infra/pull/22212 didn't resolve it.

I'm pinging the test-infra expert to dig why it doesn't work, and update there.

**Comment by Huang-Wei** [comment]
Found the root cause, we should set a go test timeout flag. #202 is working on it.

**Comment by Tal-or** [comment]
Tested it, Everything looks ok.
Closing the issue.
Thanks!
