### ISSUE TITLE
Synchronising with upstream kubernetes

### ISSUE THREAD

**Issue by pawankumar94** [kubernetes-sigs/scheduler-plugins#216]
Hello,

We are working on designing a custom Kubernetes scheduler based on the scheduling framework.
We needed to know the best methodology we can adopt to keep in sync with the latest release of Kubernetes so that we can check for the inconsistencies and modifications to be made after each release on our end.

Any suggestion is highly appreciated 

Thanks 
Pawan Kumar

**Comment by denkensk** [comment]
There seems to be no particularly good way. I usually update the version to the latest Kubernetes version、build and run the some e2e test to check if inconsistencies. 
You may need to make some changes to ensure that the compilation is successful.
