### ISSUE TITLE
Integration of custom plugin in the kubernetes Scheduling framework

### ISSUE THREAD

**Issue by pawankumar94** [kubernetes-sigs/scheduler-plugins#221]
Hello,

Greetings for the day!

I am looking here for suggestions/steps to follow for registering a custom plugin working according to my functionality for the Kubernetes cluster.

I am unable to find elaborative official documentation for creating a custom scheduler plugin and compiling the same for the cluster

I would be grateful if someone could help me on this

**Comment by Huang-Wei** [comment]
To compile a local docker image, you can clone this repo and compose your plugin, and then run `make local-image` - this is documented in [develop.md](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/develop.md).

Once you have the custom image, it depends on how you'd like to run it - replace the default scheduler, or run it as a secondary scheduler. [install.md](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md) gives detailed instructions on both options.

**Comment by pawankumar94** [comment]
Hello ,

I have been trying to followup the mentioned steps  but I am facing a very strange issue, just, for example, I am using a custom plugin named foobar,  created this under "/usr/local/go/src/sigs.k8s.io/scheduler-plugins/pkg/foobar" and registered the plugin in scheduler-plugins/main.go . Now when I try to make local- image , I get the error as below 👍 

```
make: *** [Makefile:107: update-vendor] Error 1
The command '/bin/sh -c RELEASE_VERSION=${RELEASE_VERSION} make build-scheduler.$ARCH' returned a non-zero code: 2
Makefile:76: recipe for target 'local-image' failed
make: *** [local-image] Error 2
vagrant@k8s-head2:/usr/local/go/src/sigs.k8s.io/scheduler-plugins$ 
```

**Comment by Huang-Wei** [comment]
@pawankumar94 If you want to just test in development, ensure the changes gets tested in unit tests or integration tests.

Regarding the building speed up, can you check the speed to run the `go build` command on your host machine (instead of inside a docker container)? BTW: you can also exclude the `controller` building part for plugin tests.
