### ISSUE TITLE
--leader-elect-resource-name flag not work

### ISSUE THREAD

**Issue by shuoshadow** [kubernetes-sigs/scheduler-plugins#225]
I set --leader-elect-resource-name="trimaran"  
![image](https://user-images.githubusercontent.com/10016360/129338823-505eaba1-68ac-44a2-a156-8d9ac964210c.png)

![image](https://user-images.githubusercontent.com/10016360/129338937-6297539b-7f51-4f5a-845a-63e4154516e3.png)

**Comment by lianghao208** [comment]
Have the trimaran configmap been created as your scheduler starting?

**Comment by shuoshadow** [comment]
> Have the trimaran configmap been created as your scheduler starting?

Yes, I had create  configmap, now i set resourceName and resourceNamespace, it's ok now, Thanks very much.
