### ISSUE TITLE
 Unable to decode an event from the watch stream

### ISSUE THREAD

**Issue by shuoshadow** [kubernetes-sigs/scheduler-plugins#229]
![image](https://user-images.githubusercontent.com/10016360/129827091-b72a8055-edd3-45a6-a6e9-db1cea7793bb.png)

![image](https://user-images.githubusercontent.com/10016360/129827252-ab63974f-167f-41cc-97a9-dac24e291ed0.png)

![image](https://user-images.githubusercontent.com/10016360/129827351-6f505db1-1fbc-4173-bedd-d937604f339e.png)
the image build from master
how can i resolve this error?

**Comment by Huang-Wei** [comment]
Could you provide the detailed steps to reproduce this issue? It's hard to help with just a couple of snapshots.

**Comment by seanmalloy** [comment]
@shuoshadow please provide some additional details when you have a chance. Thanks!

/kind bug
