### ISSUE TITLE
include /vendor directory in the src code

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#233]
Followup of https://github.com/kubernetes-sigs/scheduler-plugins/pull/222#issuecomment-902788190:

> From Mike: I would be +1 to start committing the vendor directory here. The original argument against it was that this was meant to be more of a toolbox of plugins, but now that this repo is being published as its own scheduler I think committing an up-to-date vendor directory is important (eg, for development, offline builds, and now trying to generate CRDs from vendored api packages).

There is always a debate on whether or not to commit the /vendor directory to a project's source code repo. Some projects (like k/k) do but some (like kind) don't.

As time goes, more and more questions regarding how to configure a compatible dev env or perform local build surface, so I'm planning to include the /vendor directory in the latest master branch, but still leave /vendor absent in other branches.

Please let me know your thoughts.

**Comment by damemi** [comment]
my thoughts are already shared :) but I support this

**Comment by denkensk** [comment]
I think we still need to include /vender in the src code. It will help people configure dev env easily.
