### ISSUE TITLE
Missing scheme_test.go

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#236]
We have main_test.go to ensure the plugins are instantiated properly, but we didn't cover whether other portions such as plugin arguments are decoded as expected.

We need a pkg/apis/config/scheme/scheme_test.go to cover this. Sample can be found in k/k: https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/apis/config/scheme/scheme_test.go.

**Comment by lianghao208** [comment]
/assign
I can fix this.

**Comment by Huang-Wei** [comment]
Fixed by #237.
