### ISSUE TITLE
Release v0.21.4

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#252]
`go.mod` is already on v0.21.4. Can we have v0.21.4 released?

**Comment by Huang-Wei** [comment]
May I know are there any specified fixes/features in v0.21.X you're interested? If so, I can give cut a release this week. If it's not urgent, I'll wait for some fixes (like #213) to be ready.

**Comment by Huang-Wei** [comment]
Closed by https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.21.6.
