### ISSUE TITLE
Issue With Latest Release 0.20.10

### ISSUE THREAD

**Issue by pawankumar94** [kubernetes-sigs/scheduler-plugins#254]
I have observed a Issue with latest release of the scheduler plugins. After Building the latest image using `make local-image ` I see the following error :
`E0907 11:25:19.528001 1 reflector.go:138] k8s.io/client-go/informers/factory.go:134: Failed to watch v1.PodDisruptionBudget: failed to list v1.PodDisruptionBudget: the server could not find the requested resource`

Wherease If I am using the version /release-1.19 , I don't see the above error.

**Comment by Huang-Wei** [comment]
I cannot reproduce the problem. Did you try to update the vendor before running `make local-image`? (by `go mod vendor` and `hack/update-generated-openapi.sh`)?

**Comment by pawankumar94** [comment]
Hello Huang Wei,

I can see that make local-image the step 7 runs the hack/updated-generated-openai.sh  below can be found :

**Comment by pawankumar94** [comment]
Step 7/11 : RUN RELEASE_VERSION=${RELEASE_VERSION} make build-scheduler.$ARCH
```
 ---> Running in 07726b08b02b
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading go.uber.org/tools v0.0.0-20190618225709-2cfd321de3ee
go: downloading github.com/cockroachdb/datadriven v0.0.0-20190809214429-80d97fb3cbaa
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/stretchr/objx v0.2.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: downloading github.com/jmespath/go-jmespath/internal/testify v1.5.1
go: downloading github.com/Azure/go-autorest/autorest/validation v0.1.0
go: downloading github.com/dnaeon/go-vcr v1.0.1
go: downloading github.com/satori/go.uuid v1.2.0
warning: ignoring symlink /go/src/sigs.k8s.io/scheduler-plugins/manifests/install/charts/as-a-second-scheduler/templates/crds
hack/update-generated-openapi.sh
Generating Kubernetes OpenAPI
```
I get the following error when I am trying to build with creating a customplugin : 

```
sigs.k8s.io/scheduler-plugins/pkg/customplugin imports
        k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1: module k8s.io/kubernetes@latest found (v1.22.2, replaced by k8s.io/kubernetes@v1.21.4), but does not contain package k8s.io/kubernetes/pkg/scheduler/framework/v1alpha1
```

**Comment by Huang-Wei** [comment]
it shouldn't be `module k8s.io/kubernetes@latest`, the k8s version is pinned properly:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/go.mod#L25

Did you manually modify the go.mod?

**Comment by Huang-Wei** [comment]
Could you run the following commands under the folder `/usr/local/go/src/sigs.k8s.io/scheduler-plugins`, and show me the output?

- go mod vendor
- go install k8s.io/kube-openapi/cmd/openapi-gen
- ls $GOPATH/bin/openapi-gen

**Comment by Huang-Wei** [comment]
I've no idea where goes wrong on your end... Can you  fix the errors and retry?

- go: could not create module cache: mkdir /usr/local/go/pkg/mod: permission denied
- go install k8s.io/kube-openapi/cmd/openapi-gen: copying /tmp/go-build4278881303/b001/exe/a.out: open /usr/local/go/bin/openapi-gen: permission denied

**Comment by Huang-Wei** [comment]
Can you verify if the output of `kubectl get clusterrole system:kube-scheduler -o yaml` contains the following content:

```yaml
...
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - get
  - list
  - watch
...
- apiGroups:
  - storage.k8s.io
  resources:
  - csinodes
  verbs:
  - get
  - list
  - watch
...
```
