### ISSUE TITLE
How to know inner logic is the leader scheduler itself?

### ISSUE THREAD

**Issue by slaysd** [kubernetes-sigs/scheduler-plugins#257]
I had a logic that is executed when the pod is changed (I add event hander in `handle.SharedInformerFactory().Core().V1().Pods().Informer().AddEventHandler(func)`).

```go
handle.SharedInformerFactory().Core().V1().Pods().Informer().AddEventHandler(cache.FilteringResourceEventHandler{
	FilterFunc: func(obj interface{}) bool {
		switch t := obj.(type) {
		case *corev1.Pod:
			return isManagedPod(t)
		case cache.DeletedFinalStateUnknown:
			if pod, ok := t.Obj.(*corev1.Pod); ok {
				return isManagedPod(pod)
			}
			return false
		default:
			return false
		}
	},
	Handler: cache.ResourceEventHandlerFuncs{
		DeleteFunc: mgr.PodDeleteFunc,
	},
})
```

this logic should execute logic when it is the leader scheduler, not others. The scheduler only works as a leader, but it is not an event handler. (it executes event handling s simultaneously.)

but it seems to the scheduler framework does not support Leader context in plugins. or is it support other solutions about it?

**Comment by lianghao208** [comment]
You can refer to this: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/cmd/controller/app/server.go#L94

**Comment by Huang-Wei** [comment]
If the scheduler replica is not the leader, it won't even [start]: 

```go
	// If leader election is enabled, runCommand via LeaderElector until done and exit.
	if cc.LeaderElection != nil {
		cc.LeaderElection.Callbacks = leaderelection.LeaderCallbacks{
			OnStartedLeading: func(ctx context.Context) {
				close(waitingForLeader)
				sched.Run(ctx)
			},
```

So if you wrap the event handling logic in your plugin, it only works when your scheduler replica becomes the leader.

[start]: https://github.com/kubernetes/kubernetes/blob/50865679b9aa60c19528f0396e7243d0f5fb15b9/cmd/kube-scheduler/app/server.go#L203-L206

**Comment by slaysd** [comment]
@lianghao208 

> You can refer to this: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/cmd/controller/app/server.go#L94

I read the link you liked. My scheduler does not implement `controller` (like `scheduler-plugins/cmd/controller`), but `scheduler` (like `scheduler-plugins/cmd/scheduler`). I think the lock is locking another leader for my logic if I use the Kubernetes lease. Am I wrong understand?

---

@Huang-Wei 

Oh, I think it does not work because I add event handler when plugin initialize(`func New(_ runtime.Object, handle framework.Handle) (faramework.Plugin, error)`). Is the scheduler framework support any `Initialize` func?

**Comment by Huang-Wei** [comment]
I see your point. For now, plugin instantiations happen before leader checking. So surfacing isLeader() to plugins doesn't even work unless the leader checking happens first. But that involves a lot of logic and I don't think it's easy to change.

However, the leaderelector entrypoint is standardized and thus obtainable from any client (as Kuberentes doesn't have hidden API). So in your plugin, you can try to build your own leaderelector check, and act on when the current replica becomes the leader. Basically you can watch on the leaderelector lease API object via`k get lease -n kube-system`:

```
$ k get lease -n kube-system
NAME                      HOLDER                                                    AGE
kube-controller-manager   kind-control-plane_019005f3-b934-432c-904f-22c1b707eb5f   4m28s
kube-scheduler            kind-control-plane_c118b0f8-bc93-4de0-a02b-65fd10329056   4m27s
```

The lease object's `spec.holderIdentity` or other programmic API should be able to tell you whether the current replica is the leader.

```
$ k get lease kube-scheduler -n kube-system -o yaml | grep "holderIdentity"
        f:holderIdentity: {}
  holderIdentity: kind-control-plane_c118b0f8-bc93-4de0-a02b-65fd10329056
```

**Comment by Huang-Wei** [comment]
BTW: may I know why you don't want the event handlers to start in non-leader replicas?

**Comment by slaysd** [comment]
@Huang-Wei 

Oh, In fact, it seemed necessary to equalize the lifecycle with scheduler and pod event handler logic. I need to implement a logic to update scheduling information internally to specific resources and erase the information when the Pod is deleted.

**Comment by Huang-Wei** [comment]
If I understand your case correctly, it's more appropriate to always keep the resource-specific cache up-to-date, in all replicas. Otherwise, the replica that obtains the leader role will have to replay all resource events to build the cache from scratch, which will result in a non-negligible cold-start time.

**Comment by slaysd** [comment]
@Huang-Wei 

Oh I see. I will try to change the logic to your advice. Thank you for kindness reply.  🙇‍♂️
