### ISSUE TITLE
Release scheduler plugins with 1.22

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#270]
1.22 contains https://github.com/kubernetes/kubernetes/pull/103383 which should help significantly with starvation / convergence issues when using coscheduling.

**Comment by zorro786** [comment]
Is this release simple @Huang-Wei?

**Comment by Huang-Wei** [comment]
The 0.22.6 release is out: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.22.6.

Close it.
