### ISSUE TITLE
coscheduling: .status.nominatedNodeName is not cleared when pod group fails to schedule and node resources are reserved indefinitely

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#293]
Consider following scenario:

1. PodGroup `a` has two pods `a-0`, `a-1`.
2. `a-0` preempts some pods on a node `N` and has `.status.nominatedNodeName` set to `N`.
3. `a-1` fails to schedule, e.g. there are not enough resources in the cluster.
4. PodGroup `a` fails to schedule indefinitely, e.g. as long as there are not enough resources in the cluster for both `a-0` and `a-1`.
5. `a-0` will have `.status.nominatedNodeName` set to `N` indefinitely and other pods cannot schedule on `N`.

Because `.status.nominatedNodeName` is never cleared resources are being held until pod `a-0` is scheduled or deleted.

Main purpose of coscheduling is to reserve resources only if enough pods of a pod group can be scheduled, but in this example node resources are reserved indefinitely even though pod group cannot be scheduled.

IMHO expected behavior should be to clear non empty `.status.nominatedNodeName` for all pod group pods when pod group fails to schedule.

**Comment by Huang-Wei** [comment]
I agree that it's an upstream bug. When a waiting pod gets rejected, the `.status.nominatedNodeName` it carries should be cleared.

I will work on a fix, while also considering issue [#85677 ](https://github.com/kubernetes/kubernetes/issues/85677)

**Comment by mateuszlitwin** [comment]
I wonder if `.status.nominatedNodeName` should be cleared during `assume(...)`: https://github.com/kubernetes/kubernetes/blob/51b94de68f0889e4e9bd5bc7673041f1275ca175/pkg/scheduler/scheduler.go#L366

**Comment by Huang-Wei** [comment]
This issue is resolved in k8s v1.23.3 (https://github.com/kubernetes/kubernetes/pull/107109), which is [vendored](https://github.com/kubernetes-sigs/scheduler-plugins/blob/9ed1891abcd07dc6d8cc9631cc57e548e2250865/go.mod#L27) in the latest `master` branch.

Close this issue.
