### ISSUE TITLE
scheduler-plugins-scheduler crashloop: no kind "KubeSchedulerConfiguration"

### ISSUE THREAD

**Issue by howardjohn** [kubernetes-sigs/scheduler-plugins#296]
```
no kind "KubeSchedulerConfiguration" is registered for version "kubescheduler.config.k8s.io/v1beta2" in scheme "k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30"
```

Following https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler

On kind v1.22.0 and GKE v1.21 I tested. Image is k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.21.6

**Comment by howardjohn** [comment]
Running templates from `v0.21.6` works actually. Just not from `master`. So probably just old image ..?

**Comment by Huang-Wei** [comment]
@howardjohn thanks for pointing it out. Yes, I shouldn't have updated the chart's [version](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml) to v1beta2 - it should point to the latest stable image instead of master.

**Comment by Huang-Wei** [comment]
BTW: note that the image compiles all plugins in this repo along with default scheduler plugins. The default scheduler plugins are enabled by default, but all plugins in this repo are **disabled by default**. So you have to enable them per your requirements. In other words, [configmap.yaml](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml) here only enables the coscheduling plugin.
