### ISSUE TITLE
coscheduling: prefilter should return `UnschedulableAndUnresolvable` status when pod group is denied

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#300]
https://github.com/kubernetes-sigs/scheduler-plugins/blob/455cb8a6536e8bf8b1d856812851c545255295b4/pkg/coscheduling/coscheduling.go#L145

When pod group was recently denied (`pgMgr.lastDenied`), pre-filter should return `UnschedulableAndUnresolvable` code (instead of `Unschedulable`) in order to prevent preemption. 

Similar when number of pods < minAvailable then pre-filter should also return `UnschedulableAndUnresolvable`. In both cases preemption does not make sense.

**Comment by Huang-Wei** [comment]
Makes sense to me. Could you open a PR fixing this?

**Comment by mateuszlitwin** [comment]
I will prepare a PR.
