### ISSUE TITLE
eliminate the "versioned" import in pkg/apis/config

### ISSUE THREAD

**Issue by everpeace** [kubernetes-sigs/scheduler-plugins#309]
Currently, we're using _versioned_ import in `pkg/apis/config/types.go`:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/apis/config/types.go#L22

This should be eliminated.

ref: https://github.com/kubernetes-sigs/scheduler-plugins/pull/224#discussion_r712521093, https://github.com/kubernetes-sigs/scheduler-plugins/pull/224#discussion_r767310629

**Comment by Xaving** [comment]
Could you explain what is versioned import and what would be a suitable solution for these issue (remove L22, replace L22 and assess the impact ....)?

**Comment by everpeace** [comment]
I think https://github.com/kubernetes-sigs/scheduler-plugins/pull/334 already resolved the issue. See: https://github.com/kubernetes-sigs/scheduler-plugins/pull/334/files#diff-a18720136db46ef660133ca97a9e1962a52e8219d3eb688daa5a9a81c64deb2fL22-L25

**Comment by ArangoGutierrez** [comment]
> I think #334 already resolved the issue. See: https://github.com/kubernetes-sigs/scheduler-plugins/pull/334/files#diff-a18720136db46ef660133ca97a9e1962a52e8219d3eb688daa5a9a81c64deb2fL22-L25

This is correct, this issue can be closed

**Comment by everpeace** [comment]
Thanks for the conformation. I'm closing this.
