### ISSUE TITLE
Installation of Scheduler Plugin as a second scheduler not working

### ISSUE THREAD

**Issue by vasa47** [kubernetes-sigs/scheduler-plugins#316]
Tested the install with minikube cluster , microk8s cluster too. 

Step 1: After the minikube start followed the steps in the current doc to install it as second scheduler
                          $ git clone git@github.com:kubernetes-sigs/scheduler-plugins.git
                          $ cd scheduler-plugins/manifests/install/charts
                          $ helm install scheduler-plugins as-a-second-scheduler/
                          NAME: scheduler-plugins
                          LAST DEPLOYED: Tue May  4 17:32:58 2021
                          NAMESPACE: default
                          STATUS: deployed
                          REVISION: 1
                          TEST SUITE: None

Verified scheduler-plugin 

$ kubectl get deploy -n scheduler-plugins
NAME                           READY   UP-TO-DATE   AVAILABLE   AGE
scheduler-plugins-controller   1/1     1            1           7s
scheduler-plugins-scheduler    1/1     1            1           7s

This is working too.

To Test coscheduling 

followed this https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#test-coscheduling

and also named 
spec.schedulerName: scheduler-plugins-scheduler

but it showing the current pods in pending state they never run

![image](https://user-images.githubusercontent.com/4268699/148887264-6023ac46-4a76-4911-aa84-f4a0d8330caf.png)

And also please help with detail steps to install capacityscheduling elastic quota with an example the current example is not sufficient as I am new to k8s. since  
the step here don't specify how to pass it the example config and also the path. 
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/capacityscheduling/README.md#tutorial

Help is much appreciated and willing to write the blog for the same for Capacity Scheduling tutorial.

**Comment by denkensk** [comment]
> but it showing the current pods in pending state they never run

Can you describe these pods and check if there are any events for these pods?

**Comment by denkensk** [comment]
> And also please help with detail steps to install capacityscheduling elastic quota with an example the current example is not sufficient as I am new to k8s. since the step here don't specify how to pass it the example config and also the path.

If you deploy the scheduler as second scheduler, the `KubeSchedulerConfiguration` is provided in the `configmap` https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml. 

You need to update the `configmap` and patch the config for `capacityscheduling`.  Then restart the plugins-scheduler.

> Help is much appreciated and willing to write the blog for the same for Capacity Scheduling tutorial.

Thanks. I will help you for  `Capacity Scheduling`. @vasa47

**Comment by vasa47** [comment]
> > but it showing the current pods in pending state they never run
> 
> Can you describe these pods and check if there are any events for these pods? If there are no events in these pods, you need to check the logs of scheduler-plugins-scheduler to find out if there are some errors.
[scheduler.log](https://github.com/kubernetes-sigs/scheduler-plugins/files/7852440/scheduler.log)

Attached is the log of the scheduler-plugins-scheduler
There is some errors .. and also i checked describe pod thing .. there are no events.

**Comment by vasa47** [comment]
> 

Yes please do help me for capacity scheduling rather than coscheduling.

**Comment by denkensk** [comment]
> Attached is the log of the scheduler-plugins-scheduler
There is some errors .. and also i checked describe pod thing .. there are no events.

Which version of k8s are you using?  The error comes from an inconsistency between the scheduler version and the cluster version. @vasa47

**Comment by vasa47** [comment]
> okay server version is Server Version: v1.22.3 

let me reinstall and check the process accordingly here
![image](https://user-images.githubusercontent.com/4268699/149083412-69f1777e-8c98-4ef6-a51e-5513afa5f915.png)

**Comment by vasa47** [comment]
start with 1.21.6 version got apparently while testing coscheduling described here 
https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#test-coscheduling

when created with replicas 2. Pods are in running state (expected is pending) but when i describe i guess events show it is scheduled from default -scheduler rather than coscheduling.

![image](https://user-images.githubusercontent.com/4268699/149085580-fc2f6d08-9e58-4f7d-bee6-924963ead8d3.png)


![image](https://user-images.githubusercontent.com/4268699/149085309-b4fff891-d121-4af0-bae2-471999db5a1d.png)


log screenshot with new version 
![image](https://user-images.githubusercontent.com/4268699/149085881-c2f09786-766c-4374-958c-7b96f248d282.png)

**Comment by denkensk** [comment]
1.  Did you deploy the scheduler by this chart `https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/manifests/install/charts/as-a-second-scheduler` ？

2. You also need to update the `spec.schedulerName: scheduler-plugins-scheduler` in the pause pod.

**Comment by vasa47** [comment]
> 1. Did you deploy the scheduler by this chart `https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/manifests/install/charts/as-a-second-scheduler` ？

Firstly I appreciate you help. 

Yes   scheduler-plugins-scheduler pod is up and running (see the screenshot)
![image](https://user-images.githubusercontent.com/4268699/149088817-0a806849-d70d-446d-9795-1c5e61405a8f.png)

> 2. You also need to update the `spec.schedulerName: scheduler-plugins-scheduler` in the pause pod.

I have changed it again and redepolyed with spec.schedulerName but now even 3 pods are also pending state. 
Sorry for earlier post didn't specify spec.scheduler thats why it went to default scheduler.. 
but yes even after specify its not working .. 
![image](https://user-images.githubusercontent.com/4268699/149088639-f24c5456-6b5a-457e-b5f8-2532641d7ded.png)

**Comment by denkensk** [comment]
> but yes even after specify its not working ..

It means that the scheduler doesn't have the role to list `configmap` and `csi*`. You can add this role in the ClusterRole 
of scheduler-plugins-scheduler.
```
Kubectl edit ClusterRole scheduler-plugins-scheduler 
```

**Comment by vasa47** [comment]
> 

can you please help me out to do this and also if you show how to do it for capacity scheduling its very helpfull.

**Comment by denkensk** [comment]
The error comes from an inconsistency between the scheduler version and the cluster.
Your cluster is 1.22 but you used the 1.21 scheduler. There will be some inconsistency here.

1. update the cluster role
```bash
kubectl edit clusterRole scheduler-plugins-scheduler
```
add this two lines
![image](https://user-images.githubusercontent.com/8958057/149121269-f3df4042-8a1a-40c5-8387-f7ea10084271.png)

2. update the configmap 
```bash
kubectl edit configmap -n scheduler-plugins scheduler-config
```
Here is an example.
```yaml
apiVersion: v1
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: scheduler-plugins-scheduler
      plugins:
        queueSort:
          enabled:
          - name: Coscheduling
          disabled:
          - name: "*"
        preFilter:
          enabled:
          - name: Coscheduling
          - name: CapacityScheduling
        postFilter:
          enabled:
          - name: CapacityScheduling
          - name: Coscheduling
          disabled:
          - name: "*"
        permit:
          enabled:
          - name: Coscheduling
        reserve:
          enabled:
          - name: Coscheduling
          - name: CapacityScheduling
        postBind:
          enabled:
          - name: Coscheduling
      pluginConfig:
      - name: Coscheduling
        args:
          permitWaitingTimeSeconds: 10
          deniedPGExpirationTimeSeconds: 3
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: scheduler-plugins
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2022-01-12T10:02:42Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: scheduler-config
  namespace: scheduler-plugins
  resourceVersion: "9716"
  uid: 1e8dfbae-cefb-468d-93bb-e19100d805d0
```
3. restart the scheduler

**Comment by vasa47** [comment]
I edited both and restarted but still same problem. I can still see logs saying same csi* problem 
and ofcourse in configmap i tested both kube-system namespace and default namespace too . same problem 

kubectl server version is now 1.21.6 
and scheduler version is also 0.21.6

![image](https://user-images.githubusercontent.com/4268699/149133111-0d38b481-4268-4bde-a33f-9d47c34bd83c.png)
![image](https://user-images.githubusercontent.com/4268699/149133223-fce5155b-2135-4733-9da1-50510cd14ca0.png)

[2configmap.txt](https://github.com/kubernetes-sigs/scheduler-plugins/files/7854205/2configmap.txt)
[clusterrol.txt](https://github.com/kubernetes-sigs/scheduler-plugins/files/7854206/clusterrol.txt)

**Comment by denkensk** [comment]
![image](https://user-images.githubusercontent.com/8958057/149156643-3084bb3d-865b-4113-8bcd-6a313e353ab8.png)
This means you didn't change the file.

**Comment by vasa47** [comment]
working perfectly fine GKE cluster now. Just one thing I wanted to clear off before closing this issue. 
Isn't the Hierarchal resource quota of Gke and this is same or is it different.?

**Comment by denkensk** [comment]
> working perfectly fine GKE cluster now.

Great!  Can you help to write a guide to the new users to teach them how to setup the CapacityScheduling？

> Isn't the Hierarchal resource quota of Gke and this is same or is it different.?

ElasticQuota is different with ResourceQuota.  For your information https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/9-capacity-scheduling#relationship-with-resourcequota

**Comment by vasa47** [comment]
Thanks closing the issue. Really appreciate the help from @denkensk

**Comment by jewelzqiu** [comment]
@denkensk hi，I‘m also testing CapacityScheduling as a second scheduler (installed using https://github.com/kubernetes-sigs/scheduler-plugins/tree/release-1.21/manifests/install/charts/as-a-second-scheduler).
using default configmap (Coscheduling only)，scheduler logs seems ok:
```
I0627 07:43:44.658097       1 serving.go:331] Generated self-signed cert in-memory
W0627 07:43:44.906563       1 options.go:330] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.
W0627 07:43:44.920124       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
W0627 07:43:45.022073       1 authorization.go:47] Authorization is disabled
W0627 07:43:45.022085       1 authentication.go:40] Authentication is disabled
I0627 07:43:45.022093       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I0627 07:43:45.028217       1 requestheader_controller.go:169] Starting RequestHeaderAuthRequestController
I0627 07:43:45.028228       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0627 07:43:45.028237       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0627 07:43:45.028243       1 shared_informer.go:240] Waiting for caches to sync for RequestHeaderAuthRequestController
I0627 07:43:45.028245       1 configmap_cafile_content.go:202] Starting client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0627 07:43:45.028257       1 shared_informer.go:240] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0627 07:43:45.028444       1 secure_serving.go:197] Serving securely on [::]:10259
I0627 07:43:45.028479       1 tlsconfig.go:240] Starting DynamicServingCertificateController
I0627 07:43:45.128368       1 shared_informer.go:247] Caches are synced for RequestHeaderAuthRequestController
I0627 07:43:45.128377       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0627 07:43:45.128409       1 shared_informer.go:247] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
```
but after I changed configmap to test CapacityScheduling:
``` yaml
apiVersion: v1
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: scheduler-plugins-scheduler
      plugins:
        preFilter:
          enabled:
          - name: CapacityScheduling
        postFilter:
          enabled:
          - name: CapacityScheduling
          disabled:
          - name: "*"
        reserve:
          enabled:
          - name: CapacityScheduling
kind: ConfigMap
```
the scheduler failed to run:
```
I0627 07:40:57.451287       1 serving.go:331] Generated self-signed cert in-memory
W0627 07:40:57.706455       1 options.go:330] Neither --kubeconfig nor --master was specified. Using default API client. This might not work.
couldn't create scheduler using provider "DefaultProvider": initializing profiles: creating profile for scheduler name scheduler-plugins-scheduler: initializing plugin "CapacityScheduling": stat /etc/kubernetes/scheduler.conf: no such file or directory
```
I noticed that at first (Coscheduling only config)，3rd line of log says `Using the inClusterConfig`
but now it tries to access `/etc/kubernetes/scheduler.conf`
Can CapacityScheduling also use in-cluster config?
