### ISSUE TITLE
How to add a new scheduler profile

### ISSUE THREAD

**Issue by cmisale** [kubernetes-sigs/scheduler-plugins#321]
Hi,
is it possible to add documentation on how to add new scheduler, scheduler profile and integrate it into the deployment with Helm?
When I look at `manifests` folder, I see that every profile has a folder with at least a `scheduler-config.yaml`, but I don't understand how and where to customize the various charts so that I can include my scheduler plugin in the build+deploy pipeline.
Also, my scheduler plugin pod needs a sidecar container and I would also provide a `deploy.yaml`, which I guess should go in `manifests/the-new-plugin` folder along with the `scheduler-config.yaml`.
Any help is appreciated.

Thanks

**Comment by Huang-Wei** [comment]
> is it possible to add documentation on how to add new scheduler, scheduler profile and integrate it into the deployment with Helm?

The current doc is at: [install.md#as-a-second-scheduler](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler).

> When I look at manifests folder, I see that every profile has a folder with at least a scheduler-config.yaml, but I don't understand how and where to customize the various charts so that I can include my scheduler plugin in the build+deploy pipeline.

You're right, for now, the Helm chart doesn't support an easy way to parameterize/customize the scheduler config, which is one area we should improve. @helayoty

Currently the manifests only hold the workable config for that specific plugin.

> Also, my scheduler plugin pod needs a sidecar container and I would also provide a deploy.yaml, which I guess should go in manifests/the-new-plugin folder along with the scheduler-config.yaml.

May I know the specific use case? Is that you'd like to spin up a controller-alike sidecar container?

**Comment by cmisale** [comment]
> The current doc is at: [install.md#as-a-second-scheduler](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler).
>

This doesn't tell me how to add a new one, though.. 


> You're right, for now, the Helm chart doesn't support an easy way to parameterize/customize the scheduler config, which is one area we should improve. @helayoty
> 

That would be very helpful!


> May I know the specific use case? Is that you'd like to spin up a controller-alike sidecar container?

My plugin pods is composed of the scheduler plugin container and a sidecar, which is accessed only by the scheduler plugin.
Therefore I need a specific yaml file to deploy it, which I added in the `manifests/my-plugin` folder.

I would like a way to build my plugin so that it's easy to deploy it within the entire second-scheduler infrastructure, because we would like to open a PR towards the main repository at some point in the near future.
