### ISSUE TITLE
Migrate scheduler plugins to use controller-runtime

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/scheduler-plugins#327]
This is to track the effort to migrate all scheduler plugins to use `controller-runtime` aka `Kubebuilder` instead of the custom framework.

The main motivation is to enhance the ability of users to use and/or extend the project.

- [x] ~~Create new APIs~~ Migrate APIs to use `controller-runtime` (#340 )
- [ ] Migrate Capacity Scheduling
- [ ] Migrate Coscheduling
- [ ] Migrate Node Resources
- [ ] Migrate Node Resource Topology
- [ ] Migrate Preemption Toleration
- [ ] Migrate Trimaran 
- [ ] Migrate samples
  - [ ] Cross Node Preemption
  - [ ] Pod State
  - [ ] Quality of Service
- [ ] Update Documentaion 
- [ ] Remove old implementation

**Comment by Huang-Wei** [comment]
@helayoty thanks for driving this. What do you mean by "Create new APIs"?

**Comment by helayoty** [comment]
> @helayoty thanks for driving this. What do you mean by "Create new APIs"?

I'd like to have a separate PR first with all APIs created and all generated code using `kubebuilder` to make sure we agree on them. So I can go and use them in the plugins, wdyt?

**Comment by Huang-Wei** [comment]
No matter the codegen tool is kubebuilder or vanilla codegen, isn't the generated content _almost_ the same? I don't get the point to create APIs - even they're just alias-like APIs.

**Comment by helayoty** [comment]
> No matter the codegen tool is kubebuilder or vanilla codegen, isn't the generated content _almost_ the same? I don't get the point to create APIs - even they're just alias-like APIs.

It should be the exact same, just wanted to have the base point separate

**Comment by Huang-Wei** [comment]
> It should be the exact same, just wanted to have the base point separate

Then the first PR can be merged directly to `master` - replace the raw codegen tags with kubebuilder ones, and update the codegen scripts. The expected result is that the current plugins function the same.

After that, you can start migrating the plugin impls.

**Comment by Huang-Wei** [comment]
BTW: I'm going to cut a 0.22.X release and bump the master to vendor k8s 1.23 soon (within one week).

**Comment by helayoty** [comment]
> > It should be the exact same, just wanted to have the base point separate
> 
> Then the first PR can be merged directly to `master` - replace the raw codegen tags with kubebuilder ones, and update the codegen scripts. The expected result is that the current plugins function the same.
> 
> After that, you can start migrating the plugin impls.

Yes, this is my intend, thanks for clarification.



> BTW: I'm going to cut a 0.22.X release and bump the master to vendor k8s 1.23 soon (within one week).

Do you think it's better to wait until you update the master?

**Comment by Huang-Wei** [comment]
> Do you think it's better to wait until you update the master?

I think so. That'd save you efforts :)
