### ISSUE TITLE
Polish integration tests

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#339]
The current integration test relies on the upstream apiservertesting package, and due to that, we had to bear with some extra work/hack:

- add `update-generated-openapi.sh`
- introduce `hack/testdata` folder and a hack to [soft-link ](https://github.com/kubernetes-sigs/scheduler-plugins/blob/9ed1891abcd07dc6d8cc9631cc57e548e2250865/hack/integration-test.sh#L50) to the vendor folder

I'm proposing to leverage [setup-envtest](https://pkg.go.dev/sigs.k8s.io/controller-runtime/tools/setup-envtest) to achieve the same goal, while simplifying the the codebase as well as Makefile entries.

**Comment by Huang-Wei** [comment]
Related items: #339 #178

**Comment by yibozhuang** [comment]
I can take a stab at this.

/assign
