### ISSUE TITLE
We need  a filter to limit a kind of label pod within a certain count in a node

### ISSUE THREAD

**Issue by aawuliliaa** [kubernetes-sigs/scheduler-plugins#345]
Background:
In our live business,pod is running at a special kind node, we call this kind of node is "video-trans",there is one  "fpga" card in this kind of node, pod mainly use "fpga" card to transcode, use less cpu(100m) and memory(200Mi).

When buy this kind of node ,we can only choose 100Cores and 200Gi,these resource can support  a lot of pod, but "fpga" card can support 60 pods, so there is a lot of cpu and memory waste.

So we want a scheduler filter to support " limit a kind of label pod within a certain count in a node"

In this way,we can use the left cpu and memory resource to run other business pod,i have asked,this kind of node support also running normal business pod.

**Comment by denkensk** [comment]
Let me summarize：She wants to limit the count of the same style(Maybe belongs to the same deployments / Using the same resource like fpga ) on one node.

**Comment by Huang-Wei** [comment]
@aawuliliaa I need to understand why your current solution wastes the cpu/mem resources: are you tainting the sparse nodes that have FPGA cards, and schedule the specific FPGA-related pods with corresponding tolerations?

If so, did you try to model the FPGA cards via extended resources to each node? (like xyz.com/fpga=<num>) Then you can schedule the specific FPGA-related pods as expected, to the nodes with FPGA cards. Meanwhile, for the regular pods, they are also legal to be scheduled to the FPGA cards to consume the cpu/mem resources. It's just if you may need to tweak some score plugins like `RequestedToCapacityRatio` to ensure the cpu/mem are not used that much by regular pods. Or, give the FPGA workloads high priority so it can preempt other pods that consume excessive cpu/mem resources.

**Comment by aawuliliaa** [comment]
thank you very much,i will have a try @Huang-Wei ,you said "give the FPGA workloads high priority",do you mean PriorityClass??

**Comment by Huang-Wei** [comment]
> do you mean PriorityClass??

yes, that can ensure the sparse resource always get utilized.

**Comment by aawuliliaa** [comment]
OK
