### ISSUE TITLE
Spring boot Scheduling

### ISSUE THREAD

**Issue by DaspawnW** [kubernetes-sigs/scheduler-plugins#350]
Dear Kubernetes Scheduling SIG,

it seems quiet interesting what you are working on :-)
I know Github issues are not the place for raising questions, but we are currently at the point where we see now light at the end of the tunnel :-(

99% of our applications in our clusters are Spring Boot applications. If you have worked with spring boot applications, then you know that they have a very strange behaviour in case of CPU usage. For them you can implement a limit, then the startup time increases up to multiple minutes; or you have none, in such a case the CPU usage at the beginning goes dramatically up (1-3 CPU cores) and throttles all other pods running there. After startup the CPU usage goes down to 0.1 CPU cores.

Currently this causes in our clusters when we perform automated patching and in case of parallel deployment of multiple applications a very high number of pod restarts and even failing applications already under traffic by our customers due to the high CPU utilization.

Is there a plugin, which could throttle the scheduled pods being scheduled at once based on a label and then wait for their healthiness?

Thank you in advance!
Björn

**Comment by helayoty** [comment]
From a Java point of view, JVM is immutable. You may go around it if you set the heap to the max so the pod can go up/down this limit only.

Now, back to the CPU problem, you may try to do some performance labs to try one of the following:
- Small VMs with more replicas
- Large VMs with fewer replicas

The research found that gives you different latency vs throughput.

**Comment by s7an-it** [comment]
@DaspawnW, have you found a solution, I can perhaps help you with my custom one if not.
