### ISSUE TITLE
noderesourcetopology: improve the test coverage

### ISSUE THREAD

**Issue by fromanirh** [kubernetes-sigs/scheduler-plugins#351]
Improve the test coverage of the noderesourcetopology filter (and later, score) plugin.
This was also suggested in https://github.com/kubernetes-sigs/scheduler-plugins/pull/347#discussion_r822111156

A improved coverage will allow to perform internal cleanups, as suggested in https://github.com/kubernetes-sigs/scheduler-plugins/pull/347#discussion_r821926236 and following

**Comment by Huang-Wei** [comment]
To clarify the two followups:

1. Mix NUMA and non-NUMA nodes in the tests
2. Return `false` (instead of `true`) in `resMatchNUMANodes()` to indicate it's a mismatch.
