### ISSUE TITLE
Modification of pod spec during binding

### ISSUE THREAD

**Issue by mikenorgate** [kubernetes-sigs/scheduler-plugins#352]
I'm looking for a way to dynamically set a pods `HostPort` when it is scheduled. My thinking is that during the binding cycle I could find available ports on the node and update the pod spec. Is it possible to edit the pod spec from within a plugin?

**Comment by Huang-Wei** [comment]
In terms of separation of concern, I don't think a scheduler plugin should update a Pod in any ways. Scheduler should be responsible for placing the pod only. There are more suitable ways to update the Pod's spec before or after the pod's scheduling.

**Comment by mikenorgate** [comment]
@Huang-Wei can you recommend some more suitable ways, I've been searching for places that I could hook into that would allow changing the spec after scheduling but couldn't find anything which is why I ended up at the scheduler

**Comment by Huang-Wei** [comment]
You can have an admission webhook to check Pod's update on `.spec.nodeName`, and then set the HostPort. However, I'm wondering if [HostPort](https://github.com/kubernetes/kubernetes/blob/86ad8fc58638b3e48db78a55478e645c4c3d8055/staging/src/k8s.io/api/core/v1/types.go#L1900) is mutable after pod gets created.

**Comment by mikenorgate** [comment]
I've just done some testing using a mutating admission webhook and it works perfectly, I'm able to update the host port as needed, thank you

**Comment by mikenorgate** [comment]
I was too eager on my testing and missed that I could only set it before it's assigned to a node rather than after
