### ISSUE TITLE
add Readme to the current helm chart

### ISSUE THREAD

**Issue by helayoty** [kubernetes-sigs/scheduler-plugins#353]
The helm chart lacks documentation and how to install/customize it.

- [ ] Add [Readme](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/README.md) to the helm
- [ ] Update the [doc](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler) specifying the steps to use helm chart -if any other place other than the above-

/good-first-issue
/kind-documentation

**Comment by mkr1481** [comment]
hi @helayoty 
As a new contributor, i would like to look ino this issue. Can you please help by adding more details on description which helm-chars you would want README.md

**Comment by helayoty** [comment]
> hi @helayoty As a new contributor, i would like to look ino this issue. Can you please help by adding more details on description which helm-chars you would want README.md

@mkr1481 Thanks for being interested to contribute. The helm chart for the project can be found [here](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/manifests/install/charts/as-a-second-scheduler).

Also, [Here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver) is a sample of how we expect the documentation to be. Please let me know if you need more details and happy to help anytime.

**Comment by chetak123** [comment]
Hey @helayoty I would like to take this issue, Also I wanted to ask that how do find all the parameters that this helm chart provides, Should I install it and test it out first ?
/assign @chetak123

**Comment by helayoty** [comment]
> Should I install it and test it out first ?

@chetak123 Thanks for offering to help. You can find all parameters [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/values.yaml). 

Also, [Here](https://github.com/kubernetes-sigs/secrets-store-csi-driver/tree/main/charts/secrets-store-csi-driver) is a sample of how we expect the documentation to be. Please let me know if you need more details and happy to help anytime.

**Comment by chetak123** [comment]
Hey @helayoty I have made a pr for this issue, also can you please specify a little more about the task 2 like what exactly I have to add there ?
Thanks

**Comment by helayoty** [comment]
>also can you please specify a little more about the task 2 like what exactly I have to add there ?

@chetak123 Not much, just make sure (this)[https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#as-a-second-scheduler] section is up-to-date and if you can add a link to the helm  README you are working on.
