### ISSUE TITLE
using k8s extended resources makes the pod unschedulable at noderesourcetopology filtering

### ISSUE THREAD

**Issue by uniemimu** [kubernetes-sigs/scheduler-plugins#355]
The logic in the nrt filter.go resMatchNUMANodes function considers kubernetes extended resources as if they would all have some numa relevance. Since some of the extended resources may not be part of the createNUMANodeList results at all in case they are not registered device plugin resources, the end result is that any (not-best-effort) pod which uses such extended resources, will be considered as unschedulable by nrt.

It would make sense that if the check for numa resources shows that the extended resource isn't numa-related (map returns not-ok), then that resource would be considered to be ok for any numa.

Kubernetes extended resource creation with curl is described here: https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/ and the extended resource can then be used in the pod spec resource limits and requests.

A unit test which fails on the issue can be found here: https://github.com/uniemimu/scheduler-plugins/commit/42cb4264dfc8aa9710385fb76223aefd868176c1

**Comment by Huang-Wei** [comment]
cc @fromanirh

**Comment by fromanirh** [comment]
Sorry for the delay. I will work on this.
