### ISSUE TITLE
Overcommitment aware scheduler plugin KEP

### ISSUE THREAD

**Issue by atantawi** [kubernetes-sigs/scheduler-plugins#357]
Though containers are allowed to specify resource limit values beyond the requested (guaranteed) values, most schedulers are only concerned with the requested values. This may result in a cluster where some (or all) nodes are overcommitted, thus leading to potential CPU congestion and performance degradation and/or memory OOM situations and pod evictions. A scheduler which takes into consideration (1) the resource limit values of pods (limit-aware) and (2) the actual load (utilization) on the nodes (load-aware) could provide a low risk environment for pods and alleviate issues with overcommitment, while allowing pods to use their limits.

This proposal describes a scheduler (score) plugin which evaluates the performance risk of overcommitment and selects the node with lowest risk. It achieves this goal by combining two risk factors: limit risk and load risk. The limit risk is based on requests and limits values. And, the load risk is based on observed load. Thus, the proposed scheduler is risk-aware as well as load-aware. The outcome is that burstable and best effort pods are placed on nodes where the chance of being impacted by overcommitment is minimized, while providing them a chance to burst up to their full limits.

[Presentation](https://docs.google.com/presentation/d/1u4SJxN_tRq8qT-G5mkh5omhXmgrFIbV865zBdMVCFps/edit?usp=sharing)

[Documentation](https://docs.google.com/document/d/15XPacVfK0EapUtTUX6JcKt014YEOrxQMflV2M8PN2PY/edit?usp=sharing)

**Comment by atantawi** [comment]
https://github.com/atantawi/357-kep-trimaran-3

**Comment by Huang-Wei** [comment]
@atantawi Just realized there is no PR raised in this repo...

/remove-lifecycle stale

**Comment by atantawi** [comment]
Demonstration of plugin under 

1. Spring Boot scenario, and
2. compute-intensive burstable workload (used PARSEC workbench).

[Demo](https://github.com/atantawi/357-kep-trimaran-3/blob/main/demos/trimaran-3-demo.pdf) shows an improvement of a factor of two in job run time.
