### ISSUE TITLE
How to use scheduler-plugins in Trimaran Scheduler?

### ISSUE THREAD

**Issue by Chenhait** [kubernetes-sigs/scheduler-plugins#363]
I followed the tutorial
https://medium.com/paypal-tech/real-load-aware-scheduling-in-kubernetes-with-trimaran-a8efe14d51e2
the first step is build a kube-scheduler image as follows:

git clone https://github.com/kubernetes-sigs/scheduler-plugins.git
git checkout
cd scheduler-plugins
env GOARCH=amd64 GOOS=linux go build -o kube-scheduler main.go

however, when i run env GOARCH=amd64 GOOS=linux go build -o kube-scheduler main.go
it shows
![image](https://user-images.githubusercontent.com/68895932/160534569-6a7b8586-dc6a-41cb-a052-e60fcbd8f0a4.png)

Thank you very much if any advance!!!

**Comment by husky-parul** [comment]
@Chenhait that's because `main.go` is located in `cmd/scheduler/main.go`

**Comment by wang-xiaowu** [comment]
> @Chenhait that's because `main.go` is located in `cmd/scheduler/main.go`

so real cmd is `env GOARCH=amd64 GOOS=linux go build -o kube-scheduler cmd/scheduler/main.go`?
i think the document of the scheduler-plugins is too easy to let people do not understand it clearly
