### ISSUE TITLE
Coscheduling: perfilter always reject the newly created pods in podGroup

### ISSUE THREAD

**Issue by NoicFank** [kubernetes-sigs/scheduler-plugins#364]
when I start the coscheduling for the first time, and I want 5 pods in same podGroup be scheduled together. But it always reject for the first time in `perFilter`, although they could be scheduled successfully at the end. 
- scheduler log
```
"PreFilter failed" err="pre-filter pod mysql-0 cannot find enough sibling pods, current pods number: 1, minMember of group: 5" pod="test/mysql-0"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-1"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-0"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-1"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-2"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-2"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-3"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-4"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-3"
"PreFilter failed" err="pod with pgName: test/pod-group-8pvf2 last failed in 3s, deny" pod="test/mysql-4"
```
- kubectl get pods -n test -w
```
NAME           READY   STATUS    RESTARTS   AGE
mysql-0        0/1     Pending             0          0s     
mysql-1        0/1     Pending             0          0s      
mysql-0        0/1     Pending             0          0s     
mysql-2        0/1     Pending             0          0s      
mysql-3        0/1     Pending             0          0s     
mysql-1        0/1     Pending             0          0s     
mysql-4        0/1     Pending             0          0s      
mysql-0        0/1     Pending             0          0s      
mysql-2        0/1     Pending             0          0s     
mysql-3        0/1     Pending             0          0s      
mysql-4        0/1     Pending             0          0s     
mysql-3        0/1     Pending             0          79s     
mysql-1        0/1     Pending             0          79s     
mysql-2        0/1     Pending             0          79s     
mysql-4        0/1     Pending             0          79s    
mysql-0        0/1     Pending             0          79s     
mysql-3        0/1     ContainerCreating   0          79s    
mysql-1        0/1     ContainerCreating   0          79s     
mysql-2        0/1     ContainerCreating   0          80s    
mysql-4        0/1     ContainerCreating   0          80s    
mysql-0        0/1     ContainerCreating   0          81s    
mysql-3        0/1     ContainerCreating   0          98s   
mysql-3        1/1     Running             0          99s  
mysql-4        0/1     ContainerCreating   0          2m26s  
mysql-4        1/1     Running             0          2m26s 
mysql-2        0/1     ContainerCreating   0          2m27s   
mysql-2        1/1     Running             0          2m27s 
mysql-0        0/1     ContainerCreating   0          2m44s   
mysql-0        1/1     Running             0          2m45s  
mysql-1        0/1     ContainerCreating   0          4m29s   
mysql-1        1/1     Running             0          4m30s   
```
For the reasons, those 5 pod belong to same podsGroup are created serially, then when the first pod reaches per-filter, there is big chance that some pods are not created, which means the number of pods belong to this podGroup are less than 5 currently (although the rest of them are created rapidly, maybe within 1s). Then the podGroup will be rejected, which leads them wait too long for scheduling.

Thus, is it necessary for the newly created pod(maybe within 3s) to pass `perFilter` quickly, where they escape for the pod number check. 
@denkensk @Huang-Wei PTAL, thanks.

**Comment by denkensk** [comment]
> Thus, is it necessary for the newly created pod(maybe within 3s) to pass perFilter quickly, where they escape for the pod number check.

Yes. It's meaningful to let the newly created pods to pass pre-filter at least the first time to schedule.

**Comment by NoicFank** [comment]
``` 
$ ./hack/update-codegen.sh
go: creating new go.mod: module fake/mod
Generating deepcopy funcs
Generating defaulters
Generating conversions
E0331 21:37:44.597293   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
E0331 21:37:44.597383   82328 conversion.go:756]   the following fields need manual conversion:
E0331 21:37:44.597387   82328 conversion.go:758]       - ScoringStrategy
E0331 21:37:44.597468   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs
E0331 21:37:44.597473   82328 conversion.go:756]   the following fields need manual conversion:
E0331 21:37:44.597476   82328 conversion.go:758]       - ScoringStrategy
E0331 21:37:44.758421   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
E0331 21:37:44.758438   82328 conversion.go:756]   the following fields need manual conversion:
E0331 21:37:44.758443   82328 conversion.go:758]       - ScoringStrategy
E0331 21:37:44.758555   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs
E0331 21:37:44.758564   82328 conversion.go:756]   the following fields need manual conversion:
E0331 21:37:44.758570   82328 conversion.go:758]       - ScoringStrategy
```
@denkensk tanks for your reply. I am little confused when I run ./hack/update-codegen.sh. I found the internal type is `ScoringStrategy` and v1beta2, v1beta3 is `*ScoringStrategy`, which leads this error.  Could you please help me to solve this error?

**Comment by Huang-Wei** [comment]
Per offline discussion with @yibozhuang, given we have a logic that can proactively move a pod's sibling pods back, it may be possible to eliminate the whole "lastDeniedPodGroup" optimization, without losing functionality's correctness, while also make scheduling more performant.

@yibozhuang is evaluating it thoroughly and will come up with a refactor.

**Comment by Lan-ce-lot** [comment]
> ```
> $ ./hack/update-codegen.sh
> go: creating new go.mod: module fake/mod
> Generating deepcopy funcs
> Generating defaulters
> Generating conversions
> E0331 21:37:44.597293   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
> E0331 21:37:44.597383   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.597387   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.597468   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs
> E0331 21:37:44.597473   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.597476   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.758421   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
> E0331 21:37:44.758438   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.758443   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.758555   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs
> E0331 21:37:44.758564   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.758570   82328 conversion.go:758]       - ScoringStrategy
> ```
> 
> @denkensk坦克为您的答复。当我运行 ./hack/update-codegen.sh 时，我有点困惑。我发现内部类型是`ScoringStrategy`and v1beta2, v1beta3 is `*ScoringStrategy`，这导致了这个错误。你能帮我避免这个错误吗？



> ```
> $ ./hack/update-codegen.sh
> go: creating new go.mod: module fake/mod
> Generating deepcopy funcs
> Generating defaulters
> Generating conversions
> E0331 21:37:44.597293   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
> E0331 21:37:44.597383   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.597387   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.597468   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta2.NodeResourceTopologyMatchArgs
> E0331 21:37:44.597473   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.597476   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.758421   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs
> E0331 21:37:44.758438   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.758443   82328 conversion.go:758]       - ScoringStrategy
> E0331 21:37:44.758555   82328 conversion.go:755] Warning: could not find nor generate a final Conversion function for sigs.k8s.io/scheduler-plugins/apis/config.NodeResourceTopologyMatchArgs -> sigs.k8s.io/scheduler-plugins/apis/config/v1beta3.NodeResourceTopologyMatchArgs
> E0331 21:37:44.758564   82328 conversion.go:756]   the following fields need manual conversion:
> E0331 21:37:44.758570   82328 conversion.go:758]       - ScoringStrategy
> ```
> 
> @denkensk tanks for your reply. I am little confused when I run ./hack/update-codegen.sh. I found the internal type is `ScoringStrategy` and v1beta2, v1beta3 is `*ScoringStrategy`, which leads this error. Could you please help me to avoid this error?

I also have this problem, and then solve it?

**Comment by Huang-Wei** [comment]
> I also have this problem, and then solve it?

Could you open a new issue, with necessary repro steps and version info?
