### ISSUE TITLE
no matches for kind "KubeSchedulerConfiguration" in version "kubescheduler.config.k8s.io/v1beta2"

### ISSUE THREAD

**Issue by Chenhait** [kubernetes-sigs/scheduler-plugins#365]
i tried 
![image](https://user-images.githubusercontent.com/68895932/160610743-30bb8d92-881a-4578-bf56-0407d4924707.png)

however, there is a error

![image](https://user-images.githubusercontent.com/68895932/160610889-9d4057ac-06b7-423f-8ced-204752e90506.png)

thank you so so much if any advance!!!

**Comment by denkensk** [comment]
It's not a public api. It's just a config for scheduler.

**Comment by Chenhait** [comment]
thank you very much for your reply!

**Comment by husky-parul** [comment]
@Chenhait It is because the version of kubernetes is not matching with the k8s api. try using `v1beta1` 
Curious were you able to run trimaran plugin?
