### ISSUE TITLE
Co-Scheduling:  it's better to use the time of first pod in pg arrived SchedulingQueue

### ISSUE THREAD

**Issue by NoicFank** [kubernetes-sigs/scheduler-plugins#368]
Instead of using `CreationTimestamp` of pg, it's better to use the time of first pod in pg arrived SchedulingQueue?  as creating podGroup and creating pod to schedule is async.
```
// GetCreationTimestamp returns the creation time of a podGroup or a pod.
func (pgMgr *PodGroupManager) GetCreationTimestamp(pod *corev1.Pod, ts time.Time) time.Time {
	pgName := util.GetPodGroupLabel(pod)
	if len(pgName) == 0 {
		return ts
	}
	pg, err := pgMgr.pgLister.PodGroups(pod.Namespace).Get(pgName)
	if err != nil {
		return ts
	}
	return pg.CreationTimestamp.Time
}
```

In the following example:
- `pg1` is created before `pg2`
- there are `pod1-0`, `pod1-1` in pogGroup `pg1`, and `pod2-0`,`pod2-1` in `pg2`, then:

1. firstly: `pod2-0` &  `pod2-1` arrived.
- Queue: `pod2-1`,`pod2-0`
   ---------> priority
2. then: consume first pod in queue `pod2-0`
- Queue: `pod2-1`
- Processing: `pod2-0`
3. then: `pod1-0`,`pod1-1` arrived
- Queue: `pod2-1`,`pod1-1`,`pod1-0`  (since `pg1` is created before `pg2`)
- Processing: `pod2-0`
4. then: consume first pod in queue `pod1-0`, where we expect its `pod2-1`.
- Queue: `pod2-1`,`pod1-1`
- Processing: `pod1-0`

where we expect the situation is:
- Queue: `pod1-1`,`pod1-0`
- Processing: `pod2-1`

**Comment by Huang-Wei** [comment]
Theoretically, I think your proposal is only better in _some_ case. It's not necessarily the PodGroup that has early-arriving pod should be always prioritized than a PodGroup that has later-arriving pod.

A good solution is to impose extra semantics to the PodGroup, like queue. I'm proposing a refined PodGroup API in https://docs.google.com/document/d/16yLngEOd6x3IS6ejkclrCdmkDYfxtTyr97a7uNug_wA/view, and pursuing to make it available in k/k.

**Comment by NoicFank** [comment]
> 

yeah, for sure. Access to the document is denied. Please apply through my access request, thanks.

**Comment by yuanchen8911** [comment]
Before the proposed PodGroup semantics are available,  I think custom and configurable sorting strategies, including the proposed one here, might be helpful. It can be configured via `coscheduling` plugin config. 

- Default sorting
- Sorting based on the first pod's timestamp
- Prioritize pods in a pod group that has reservation and is waiting for additional pods.

**Comment by NoicFank** [comment]
> 

Thanks for the advices, I will see about this.
