### ISSUE TITLE
the images from "make local-image" is same with k8s.gcr.io/scheduler-plugins/kube-scheduler and controller?

### ISSUE THREAD

**Issue by mymlzz** [kubernetes-sigs/scheduler-plugins#374]
Hi

My k8s is v1.22.6 and "git clone git@github.com:kubernetes-sigs/scheduler-plugins.git" on "$GOPATH/src/sigs.k8s.io".

After "make local-image" I get two images "localhost:5000/scheduler-plugins/kube-scheduler:latest" and "localhost:5000/scheduler-plugins/controller:latest"

I "docker tag" these two images to "k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.22.6" and "k8s.gcr.io/scheduler-plugins/controller:v0.22.6".

Now I follow install.md to install and test Coscheduling.

However, it fail and three pause pod all pending.

Could you give me some help to tell me how could I make local-image successful?

Thank you very much.
![Screenshot 2022-05-13 175002](https://user-images.githubusercontent.com/105040475/168405187-b3e99781-c082-422c-8bbf-3e1e63cc9d93.png)
![Screenshot 2022-05-13 175052](https://user-images.githubusercontent.com/105040475/168405190-249a65f3-7e7a-4d89-b4b0-72c016a0e0b3.png)

**Comment by Huang-Wei** [comment]
> My k8s is v1.22.6 and "git clone [git@github.com](mailto:git@github.com):kubernetes-sigs/scheduler-plugins.git" on "$GOPATH/src/sigs.k8s.io".

Given your k8s is at v1.22.6, it's recommended to compile your scheduler-plugins at v1.22.X as well. I suppose you're running scheduler-plugins at `master`?

> However, it fail and three pause pod all pending.

Can you `k describe pod <pending pod>`?

> Could you give me some help to tell me how could I make local-image successful?

I suppose you've already built the image, no?

**Comment by mymlzz** [comment]
Hi

Thank you for your patient reply.

However, After I "git clone --branch v0.22.6 git@github.com:kubernetes-sigs/scheduler-plugins.git".
It show 👍 scheduler-plugins v0.22.6 are available at kube-scheduler:v0.22.6 and controller:v0.22.6.
![image](https://user-images.githubusercontent.com/105040475/168515718-5e27dd76-6ff9-45be-abf4-9ea58cbf419e.png)

However, In "/manifest/install/all-for-one.yaml" of scheduler-plugins v0.22.6. It shows scheduler-plugins v0.22.6 are available at controller:v0.21.6
![image](https://user-images.githubusercontent.com/105040475/168515854-c5ccbec3-1fbe-4de4-9e0b-7e7f4c901173.png)

If possible, Could you give me some help to tell me which version of scheduler-plugins should I to git clone on my v1.22.6 k8s. 

Thank you very much
Sincerely
