### ISSUE TITLE
Coscheduling: Add a Sort Condition to QueueSort

### ISSUE THREAD

**Issue by caohe** [kubernetes-sigs/scheduler-plugins#387]
In the early [implementation](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/2-lightweight-coscheduling) of Coscheduling, it mentioned 

> If their InitialAttemptTimestamp is identical, **order by their UID of PodGroup**: a Pod with lexicographically greater UID is scheduled ahead of the other Pod. (The purpose is to **tease different PodGroups with the same InitialAttemptTimestamp apart**, while also **keeping Pods belonging to the same PodGroup back-to-back**)

However, I found that in the new [implementation](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/42-podgroup-coscheduling) of Coscheduling, this condition is replaced by comparing the `namespace/name` strings of two **Pods**, which I think may be not reliable.
https://github.com/kubernetes-sigs/scheduler-plugins/blob/84d3e79188fcbf11f0e7bfdf1a261116ef7f12c9/pkg/coscheduling/coscheduling.go#L108-L124

I am wondering whether we should add a sort condition:
- If the `CreationTimestamp` of two PodGroup are equal, then compare the `namespace/name` strings of two **PodGroups**.
- If the `namespace/name` strings of two **PodGroups** are equal, then compare the `namespace/name` strings of two **Pods** (**As it used to be**).

**Comment by Huang-Wei** [comment]
@caohe when the creationTime are equal, it usually implies the two pods belong to the same PodGroup, and thus comparing with the two pods's namespaceName is reasonable and stable. Your suggestion on comparing two PodGroups won't differentiate the two pods IMO.

cc @denkensk

**Comment by caohe** [comment]
> when the creationTime are equal, it usually implies the two pods belong to the same PodGroup

@Huang-Wei Thanks for your reply. I think in most cases, this is true. However, in some special cases, two PodGroups may be created at the same time. So just comparing two pods's namespaceName may be not reliable.

**Comment by Huang-Wei** [comment]
Hmm... are you sure in the real world, the nano/milliseconds of two PodGroup's creationTime are identical?

**Comment by caohe** [comment]
Aha, actually I am not sure. I agree with you on the point that it's very unlikely to happen.

**Comment by Huang-Wei** [comment]
This issue is related with #110. Basically we should come up with heuristic mechanics to sort the group of pods smartly. This may not each to achieve without a proper PreQueue extension point in the scheduler framework.

Working on a KEP, and then will get back here to come up with a design to ensure regular Pods and PodGroup-associated pods are sorted fairly.
