### ISSUE TITLE
Capacity Scheduling could get stuck in a loop

### ISSUE THREAD

**Issue by zhiyxu** [kubernetes-sigs/scheduler-plugins#391]
Is it possible for capacity scheduling to get stuck in a loop:

Pod1 in ElasticQuota1 is currently unschedulable, and EQ1.Used < EQ1.Min, while Pod2 running in ElasticQuota2 and EQ2.Used > EQ2.Min, so Pod1 can preempt Pod2 in EQ2 and running successfully. 

But after preemption, EQ1.Used > EQ1.Min, EQ2.Used < EQ2.Min, then Pod2 can preempt Pod1... 

I'm not sure if this will happen.
@denkensk

**Comment by denkensk** [comment]
No. It will add the resource of preemptor to prevent the loop infinite preempt.

Pls take a look:
https://github.com/kubernetes-sigs/scheduler-plugins/blob/1550aa8419628b7d0520ee594fec7718444426d4/pkg/capacityscheduling/capacity_scheduling.go#L519
