### ISSUE TITLE
kube-scheduler failed to start with k8s v1.24.2

### ISSUE THREAD

**Issue by riyazhakki** [kubernetes-sigs/scheduler-plugins#394]
My k8s version is v1.24.2, compiled my scheduler-plugins at master.

while starting the kube-scheduler container throwing following error.

$` kubectl logs pod/kube-scheduler-c7-master-vm2 -n kube-system`
Flag --port has been deprecated, This flag has no effect now and will be removed in v1.24. You can use --secure-port instead.
I0627 15:15:46.623770       1 serving.go:348] Generated self-signed cert in-memory
E0627 15:15:46.624607       1 run.go:74] "command failed" err="no kind \"KubeSchedulerConfiguration\" is registered for version \"kubescheduler.config.k8s.io/v1beta1\" in scheme \"k8s.io/kubernetes/pkg/scheduler/apis/config/scheme/scheme.go:30\""

**Comment by Huang-Wei** [comment]
@riyazhakki given the master branch is still at 1.23, that behavior is as expected:

https://github.com/kubernetes-sigs/scheduler-plugins/blob/1550aa8419628b7d0520ee594fec7718444426d4/go.mod#L24

We will soon cut an official 1.23 image, along with bumping master to 1.24.

@fromanirh @Tal-or please let me know which ongoing PRs are disired to be merged before we bump to 1.24.

**Comment by Huang-Wei** [comment]
/close

Duplicated with #430.

**Comment by Huang-Wei** [comment]
@zffocussss you should use at least v1beta2 (which is also deprecated though) in v1.24 - v1beta1 has been removed entirely in v1.24.
