### ISSUE TITLE
How to add own plugin to helm chart

### ISSUE THREAD

**Issue by JulianTS** [kubernetes-sigs/scheduler-plugins#396]
Hey,

I wondered how I add a simple scoring plugin without any args, like the pod state sample, to the helm chart for an easy deployment as second scheduler on all kinds of clusters(most likely kind or k3d).

Which manifest files etc do I have to modify?
Or is there a better way?

plugin is located in
`/pkg/energy/energy.go
`

Writing my BA thesis about a plugin and would appreciate some help!

**Comment by autumn0207** [comment]
> helm chart for an easy deployment as second scheduler on all kinds of clusters(most likely kind or k3d).

You need to compile your code into image first, then replace the image info in the helm chart.

**Comment by JulianTS** [comment]
replace the scheduler image in `manifests/install/charts/as-a-second-scheduler/values.yaml` ?

and probably add the name in there to the plugins as well?

**Comment by seanmalloy** [comment]
To change the container image you would change this line: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/values.yaml#L8

The second part would be the configuration for the scheduler which in this helm chart is a `ConfigMap`. You need to take a look that this template: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml. The relevant helm values for controlling the contents of the ConfigMap are here: https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/manifests/install/charts/as-a-second-scheduler/templates/configmap.yaml.

I hope that helps.
