### ISSUE TITLE
Coscheduling:  PodGroup completion progress check in PreFilter extension

### ISSUE THREAD

**Issue by chenxi-seu** [kubernetes-sigs/scheduler-plugins#410]
Hi 
I noticed that there is a description of podGroups' completion process in `PreFilter` extension. But I haven't found the relevant code logic in the `Prefilter` extension point. Is it a `todo` to be implemented later ? 

Reference: [Kep Prefilter](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/42-podgroup-coscheduling#prefilter)
kep/42-podgroup-coscheduling/README.md

![image](https://user-images.githubusercontent.com/78208999/180355852-157390bd-d688-4fcf-b6ca-187199f48cbc.png)

**Comment by Chenxi-Seu** [comment]
@wadecai  Could you please share some ideas, as I see you are the author of this kep :)

**Comment by Chenxi-Seu** [comment]
@Huang-Wei  Could you please share any ideas about this ~
