### ISSUE TITLE
Flaky test in TestLoadVariationRiskBalancingPlugin

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#415]
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_scheduler-plugins/414/pull-scheduler-plugins-integration-test-master/1560681107773460480
- https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_scheduler-plugins/414/pull-scheduler-plugins-integration-test-master/1560692216433741824

**Comment by Huang-Wei** [comment]
@atantawi it seems https://github.com/kubernetes-sigs/scheduler-plugins/pull/401 introduced some flakyness? Could you take a look? This is now blocking PR's merge like https://github.com/kubernetes-sigs/scheduler-plugins/pull/414#issuecomment-1220974861.

/assign @atantawi

**Comment by Huang-Wei** [comment]
cc @wangchen615

**Comment by atantawi** [comment]
@Huang-Wei @wangchen615 

The one change that I see could have made a difference in moving the block 

>     ns := fmt.Sprintf("integration-test-%v", string(uuid.NewUUID()))
>     createNamespace(t, testCtx, ns)

down after initializing the test. I will move it back up and submit a PR associated with this issue.
I tested the change in my local environment and seems to be working OK.

**Comment by Huang-Wei** [comment]
Thanks @atantawi for looking into it. Please raise a PR.

**Comment by atantawi** [comment]
I am also filling the `Window` and `Timestamp` fields in `watcher.WatcherMetrics` in the test.
