### ISSUE TITLE
[Helm] support customizing pluginConfig

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#419]
Follow up of https://github.com/kubernetes-sigs/scheduler-plugins/issues/379#issuecomment-1227798395:

> the recent Helm chart refactoring PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/326 doesn't support pluginConfig's customization. And in recent refactoring to leverage v1beta3, this support isn't added either. I will create an issue to track on this.

It'd be nice to add support for customizing pluginConfig in `as-a-second-scheduler/templates/configmap.yaml`.

**Comment by lianghao208** [comment]
For now, I think only coscheduling, noderesources, noderesourcetopology and trimaran have their onw pluginConfig. I'll work on pluginConfig's customization of these 4 plugins. @Huang-Wei

**Comment by Huang-Wei** [comment]
@lianghao208 could you help cherry-pick this to `release-1.23`?

**Comment by lianghao208** [comment]
> @lianghao208 could you help cherry-pick this to `release-1.23`?

@Huang-Wei Sure, working on it.
