### ISSUE TITLE
[Trimaran] Support GPU resource

### ISSUE THREAD

**Issue by Telemaco019** [kubernetes-sigs/scheduler-plugins#422]
Hello everyone, 

It would be nice if Trimaran supported load-aware scheduling based on GPU utilization. 

The [load-watcher](https://github.com/paypal/load-watcher) service supports Prometheus sources, so the metrics exposed by the NVIDIA DCGM Exporter (described [here](https://docs.nvidia.com/datacenter/dcgm/latest/user-guide/feature-overview.html#metrics)) could be used for determining GPU usage. 

The feature could either be implemented as additional plugins (e.g. something like `GPUTargetLoadPacking` and `GPULoadVariationRiskBalancing`) or as an extension of the existing ones. 

### Example
The following is a simple use case I would like Trimaran to support.

**Scenario**: 
- two nodes (**Node A** and **Node B**)
- each node has a single NVIDIA GPU
- the NVIDIA k8s-device-plugin is configured for partitioning the GPUs of the two nodes using [time-slicing](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/gpu-sharing.html) (thus the compute resources of the GPUs are shared among multiple Pods). 
- **Node A** and **Node B** both expose the resource `nvidia.com/gpu=3`
- **Node A** and **Node B** are both running a Pod requesting `nvidia.com/gpu=1`

**Use case**:
- overall average GPU usage of **Node A** is 10%
- overall average GPU usage of **Node B** is 80%
- a new Pod requesting `nvidia.com/gpu=1` is created
- the Pod could be hosted by both **Node A** and **Node B**, but _the scheduler should prefer Node A since its average GPU usage is lower_

**Comment by Huang-Wei** [comment]
cc @atantawi @zorro786 @wangchen615

**Comment by wangchen615** [comment]
@Huang-Wei , thanks for tagging us. We will take a look.

**Comment by wangchen615** [comment]
@Telemaco019, thanks for raising this issue. If you are interested in contributing, let's have a follow-up discussion on k8s slack.
