### ISSUE TITLE
[Coscheduling] Repetitive preemption on low-priority Pods

### ISSUE THREAD

**Issue by zhiyxu** [kubernetes-sigs/scheduler-plugins#431]
The test scenario is as follows, currently running 2 low-priority tasks, then submitting a distributed task of 2 instances, each instance requires 3GPU, and priority=100.

| Node  | Resource | Running Instance           |
| ----- | -------- | -------------------------- |
| node1 | 5GPU     | task-0（priority=0，3GPU） |
| node2 | 5GPU     | task-1（priority=0，3GPU） |
| node3 | 2GPU     |                            |

Distributed instances will preempt low-priority tasks, and `spec.nominatedNode` added.

After the low-priority tasks are terminated and resources are released, newly created low-priority tasks are Running again, resulting in distributed instances preempt low-priority tasks continuously, but they still cannot get started.

Any suggestions to solve this issue?

**Comment by zhiyxu** [comment]
@Huang-Wei Do you have any suggestion on how to fix this issue, thanks in advance :-)

**Comment by Huang-Wei** [comment]
The current scheduler framework's design offers extensions based on a single pod's scheduling. So the issue you mentioned could happen, as preemption/reservation is accomplished per-pod.

Adding a backoff in co-scheduling (https://github.com/kubernetes-sigs/scheduler-plugins/issues/429#issuecomment-1254515086) helps but cannot resolve it entirely.

Some ideas like [reservation-like API](https://docs.google.com/document/d/1sbFUA_9qWtorJkcukNULr12FKX6lMvISiINxAURHNFo/edit) may be the right way. The user sends a `reservation` request to hold a chunk of resources, and the PodGroup pods get scheduled only when the `reservation` request is satisfied.

BTW: would you mind retitling to "[Coscheduling] Repetitive preemption on low-priority Pods"
