### ISSUE TITLE
Failed to install scheduler via helm, if namespace already exists

### ISSUE THREAD

**Issue by 0xff-dev** [kubernetes-sigs/scheduler-plugins#433]
If the namespace scheduler-plugins is created in advance, the installation will fail through the steps in [README](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/manifests/install/charts/as-a-second-scheduler).
```shell
helm -nscheduler-plugins install plugin .
```

**Comment by Huang-Wei** [comment]
I'd expect some Helm options like force install would work. 

(This is more of a Helm usage issue)
/close
