### ISSUE TITLE
[Trimaran] Potential misleading log output "Missing utilization for node"

### ISSUE THREAD

**Issue by wintersolutions** [kubernetes-sigs/scheduler-plugins#435]
I've tried Trimaran with TargetLoadPacking plugin with `KubernetesMetricsServer` and `Prometheus` metrics provider. No matter what I do I always see the log entry:

```
"Missing utilization for node" nodeName="somebox.example.com" missingCPUUtilMillis=1000
```

After looking at the code (as a complete Go amateur) I highly suspect that this log line is printed every time. No matter if `CPUUtilMillis` has a value and if its used for the calculation.

https://github.com/kubernetes-sigs/scheduler-plugins/blob/81fb4607af1d45ebf76eb7fbd0eb7ddba7abc959/pkg/trimaran/targetloadpacking/targetloadpacking.go#L165

Since this log entry is pretty central to any config debugging efforts it would be nice if sb. looks over this and puts it in a proper conditional if its indeed misleading.

**Comment by wangchen615** [comment]
@wintersolutions , thanks for raising this. Yes, it is showing every time to indicate if the score should be derived based on some newly arrived pods whose usage has not been obtained.

I believe the word "missing utilization" would be somewhat misleading. We still want to show this utilization value, but probably need a better logging message. What do you think?

**Comment by wintersolutions** [comment]
@wangchen615 I'm not sure if we are talking about the same issue here. The log message is about missing utilization data for **nodes** not **pods**. I agree that you can't predict utilization for new pods but the utilization for existing nodes should be known.
