### ISSUE TITLE
Pod group label has invalid key

### ISSUE THREAD

**Issue by sftim** [kubernetes-sigs/scheduler-plugins#440]
https://github.com/kubernetes-sigs/scheduler-plugins/blob/66dabd41eb42dd6e96e1762c89cf96b4eff05bdd/pkg/coscheduling/README.md mentions a label:
`pod-group.scheduling.sigs.k8s.io`

This label doesn't follow the official format, which should be a DNS domain name, then `/`, then a key string.

For example: `scheduling.kubernetes.io/pod-group`.

This issue is to report that design bug and request that we fix it. We can also support the legacy label indefinitely as a deprecated substitute.

**Comment by sftim** [comment]
Once we fix this, we should file an issue about documenting the new valid label in https://kubernetes.io/docs/reference/labels-annotations-taints/

/kind bug

**Comment by denkensk** [comment]
Thanks. 
/assign

**Comment by cmssczy** [comment]
hi @denkensk , I want to work on it if you haven't started. 
Do you think `scheduling.sigs.k8s.io/pod-group` is a good choice?

**Comment by denkensk** [comment]
>  I want to work on it if you haven't started.

OK Thanks @cmssczy 

> Do you think scheduling.sigs.k8s.io/pod-group is a good choice?

I think it's better to both support `scheduling.sigs.k8s.io/pod-group` and `pod-group.scheduling.sigs.k8s.io` for the compatibility with existing users.

**Comment by Huang-Wei** [comment]
This is completed.
