### ISSUE TITLE
what is controllers used for?

### ISSUE THREAD

**Issue by zffocussss** [kubernetes-sigs/scheduler-plugins#442]
Hi team:
  I am putting my eyes on schedulers only.Curious about the sibling controllers in this repo.Can I just put the controllers aside?

https://github.com/kubernetes-sigs/scheduler-plugins/issues/442#tasklist-block-3d475b8a-57df-4157-9174-abaaec22436e

**Comment by Huang-Wei** [comment]
@zffocussss yes, you can. Controllers are not supposed to be an input of scheduling decisions. They're more reconciling the status and hence display the CR objects nicely. In other words, without controllers, scheduling still functions but the CR objects' state are not well-displayed.
