### ISSUE TITLE
[Coscheduling] The status of PodGroup is not updated

### ISSUE THREAD

**Issue by sshukun** [kubernetes-sigs/scheduler-plugins#446]
After installed Scheduler-plugins as a second scheduler using the Helm chart under `manifests/install/charts/as-a-second-scheduler`, I tried the Coscheduling plugins following the [community document](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md#test-coscheduling).

Although all the pods are in running state, the phase of PodGroup is still scheduling and the number of scheduled pod is 1.
```
[test@worker-1 ~]$ kubectl get pod
NAME                     READY   STATUS    RESTARTS   AGE
pause-7f6b69d8f7-8kwj8   1/1     Running   0          9h
pause-7f6b69d8f7-jsn7j   1/1     Running   0          9h
pause-7f6b69d8f7-xkxmv   1/1     Running   0          9h
[test@worker-1 ~]$ kubectl get podgroup pg1 -o yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  creationTimestamp: "2022-11-07T02:38:56Z"
  generation: 7
  name: pg1
  namespace: default
  resourceVersion: "1178462"
  uid: 5ba3461f-c441-4139-b063-6950eb9b40f4
spec:
  minMember: 3
  scheduleTimeoutSeconds: 10
status:
  phase: Scheduling
  running: 3
  scheduleStartTime: "2022-11-07T02:39:33Z"
  scheduled: 1
[test@worker-1 ~]$
```
The version of kubernetes:
```
[test@worker-1 ~]$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:57:26Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by KunWuLuan** [comment]
I think this is due to multiple pods entering postbind at the same time, causing their patch requests to be based on the same copy.

**Comment by KunWuLuan** [comment]
The problem should be solved by getting first and then updating instead of patching.

**Comment by Huang-Wei** [comment]
@sshukun which scheduler-plugins version are you running?

**Comment by zwpaper** [comment]
https://github.com/kubernetes-sigs/scheduler-plugins/pull/506 could fix this issue

**Comment by zwpaper** [comment]
it should be done as #506 is now merged, and we also had a test for it https://github.com/kubernetes-sigs/scheduler-plugins/pull/549, feel free to reopen the issue if the problem still existed

/close
