### ISSUE TITLE
Scheduling become very slowly when enable preFilter plugin of coscheduling

### ISSUE THREAD

**Issue by shinytang6** [kubernetes-sigs/scheduler-plugins#450]
With coscheduling preFilter enabled:
```
E1116 08:24:00.746178       1 coscheduling.go:133] "PreFilter failed" err="pre-filter pod mnist-worker-0 cannot find enough sibling pods, current pods number: 1, minMember of group: 2" pod="kubedl/mnist-worker-0"
E1116 08:24:00.756216       1 coscheduling.go:133] "PreFilter failed" err="pod with pgName: kubedl/mnist-worker last failed in 3s, deny" pod="kubedl/mnist-worker-1"
E1116 08:24:02.611433       1 coscheduling.go:133] "PreFilter failed" err="pod with pgName: kubedl/mnist-worker last failed in 3s, deny" pod="kubedl/mnist-worker-0"
E1116 08:24:02.618329       1 coscheduling.go:133] "PreFilter failed" err="pod with pgName: kubedl/mnist-worker last failed in 3s, deny" pod="kubedl/mnist-worker-1"
...
I1116 08:25:22.304991       1 coscheduling.go:194] "Pod is waiting to be scheduled to node" pod="kubedl/mnist-worker-0" nodeName="xxx"
...
```

After almost over one minute, the pods can be scheduled successfully.

Obviously, this is unacceptable. The reason for is that when scheduling the first pod of job, there is only one pods of the same podGroup in the cache, which is smaller than podgroup.minMember, resulting in scheduling failure in the first scheduling cycle, so have to wait another scheduling cycle.

l would recommend add optional arguments to `minMember` and `minResource` check in coscheduling Prefilter plugin or just remove `minMember` check in Prefilter check.

**Comment by shinytang6** [comment]
@Huang-Wei @denkensk WDYT? l don't find much necessity to check minMember in coscheduling perfilter extension point

**Comment by shinytang6** [comment]
l am using k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.22.6

**Comment by Huang-Wei** [comment]
Ah, I see the message "last failed in 3s, deny", this deny mechanism was removed in #408, so upgrade to v0.23.10 should be good: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.23.10

**Comment by shinytang6** [comment]
> Ah, I see the message "last failed in 3s, deny", this deny mechanism was removed in #408, so upgrade to v0.23.10 should be good: https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.23.10
> 
> > Below are highlighted changes since the previous release (v0.22):
> > ......
> > 
> > * Optimized coscheduling logic in PreFilter to refrain from early backing off for a PodGroup.

okay thanks! l will have a try
