### ISSUE TITLE
Pod throttling

### ISSUE THREAD

**Issue by buckleyGI** [kubernetes-sigs/scheduler-plugins#453]
I came across Trimaran when looking for a solution to our pressing problem (still not solved) when we bring back a great number of pods after a blackout period.

Let me try to explain our situation. At night we scale all deployments to 0 replicas (and store the original value in an annotation) to reduce costs.
In the morning the replicas are restored to their original values. This is where the problem starts as they overburden the node where the CPU plateaus to 100%.
**The warmup probes start to fail and, if they make it, the liveness probes will start restaring the pods.** Too many pods are trying to get up at the same time...
After about 2 hours the system finally stabilizes. If we startup the pods manually, say 5 per minute, the system comes up in less then 10 minutes (!).
In other domains this is called the thundering herd problem or stampede problem and we haven't found a fix yet for Kubernetes.

Is this where Trimaran can help us? I understand that Trimaran takes into account the CPU utilization but its goal is to be more efficient and not throttle pod creation per se right. **Will we be abusing Trimaran for our use case or is it a good fit you think?**

If not it is time for me to learn Go and the Scheduling Framework as it can't be too hard to install a throttle for pod creation on a node where x pods can be created in a sliding window of x minutes. Am I on the right track? Thank you.

**Comment by Huang-Wei** [comment]
cc @wangchen615 @zorro786 @atantawi

**Comment by atantawi** [comment]
@buckleyGI Need some clarification about the configuration. Are the values of requests and limits for CPU same? or different (values?)? Are there init containers in the pods? What are the requests and limits for those?

**Comment by everpeace** [comment]
FYI: I received an almost identical issue in https://github.com/everpeace/kube-throttler/issues/57. And I proposed two solutions that can throttle the number of starting up pods by kube-throttler or Pod Scheduling Readiness (https://github.com/everpeace/kube-throttler/issues/57#issuecomment-1354719952).
