### ISSUE TITLE
possible flake: topologicalsort_test

### ISSUE THREAD

**Issue by fromanirh** [kubernetes-sigs/scheduler-plugins#457]
It seems this integration test is flaking. Observed with different unrelated PRs, demonstrated with #456, see https://prow.k8s.io/pr-history/?org=kubernetes-sigs&repo=scheduler-plugins&pr=456 for details.

Filing this issue for tracking purposes.

**Comment by Huang-Wei** [comment]
@jpedro1992 could you please take a look at the flake?

**Comment by jpedro1992** [comment]
I will have a look at the integration test. 
/assign
