### ISSUE TITLE
[Trimaran]panic: version string "" doesn't match expected regular expression

### ISSUE THREAD

**Issue by wintle777** [kubernetes-sigs/scheduler-plugins#467]
I'm beginner and I don't know how to fix this error. Do you have any ideas?Thank you.

kubectl logs trimaran-6d9ddd6c9b-knqzm -n kube-system -c trimaran
panic: version string "" doesn't match expected regular expression: "^v(\d+\.\d+\.\d+)"
goroutine 1 [running]:
k8s.io/component-base/metrics.parseVersion({{0x0, 0x0}, {0x0, 0x0}, {0x23b378a, 0x0}, {0x20b5eb1, 0xb}, {0x0, 0x0}, ...})
	/home/nvidia/MY_PROJECT/scheduler-plugins-master/scheduler-plugins-master/vendor/k8s.io/component-base/metrics/version_parser.go:47 +0x274
k8s.io/component-base/metrics.newKubeRegistry({{0x0, 0x0}, {0x0, 0x0}, {0x23b378a, 0x0}, {0x20b5eb1, 0xb}, {0x0, 0x0}, ...})
	/home/nvidia/MY_PROJECT/scheduler-plugins-master/scheduler-plugins-master/vendor/k8s.io/component-base/metrics/registry.go:320 +0x119
k8s.io/component-base/metrics.NewKubeRegistry()
	/home/nvidia/MY_PROJECT/scheduler-plugins-master/scheduler-plugins-master/vendor/k8s.io/component-base/metrics/registry.go:335 +0x78
k8s.io/component-base/metrics/legacyregistry.init()
	/home/nvidia/MY_PROJECT/scheduler-plugins-master/scheduler-plugins-master/vendor/k8s.io/component-base/metrics/legacyregistry/registry.go:29 +0x1d

**Comment by mofanke** [comment]
i faced the same issue ， https://github.com/kubernetes-sigs/scheduler-plugins/blob/release-1.22/doc/release-guide.md
seems need a tag ,not branch 
then
`make local-image`

**Comment by wangchen615** [comment]
@wintle777 , thanks for raising the issue. The log message did not point to a particular line in the trimaran code, so I am unsure if it is just an issue with Trimaran. Have you tried other plugins?

At the same time, could you help share more info about the configuration of your Trimaran plugin? Did you run it as a secondary scheduler? And what metric provider are you using?

**Comment by zwpaper** [comment]
hi @wintle777, I have checked the makefile, we should already handled this, may I ask, do you use `make build` to build your scheduler or `go build` directly?

**Comment by wintle777** [comment]
Sorry, it's been a while, I have tried both `make build-scheduler` and `go build`

> hi @wintle777, I have checked the makefile, we should already handled this, may I ask, do you use `make build` to build your scheduler or `go build` directly?

**Comment by zwpaper** [comment]
hi @wintle777, thanks for the update, it should be ok to use `make build-scheduler`, but `go build` may fail because we should set the `Version` when building (check https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/Makefile#L61).

You could try again or close this issue if there are no more errors.
