### ISSUE TITLE
Official Docker Container Image

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/scheduler-plugins#47]
Several other kubernetes-sigs projects have official container images in `k8s.gcr.io` container registry. It would be convenient for end users if the scheduler-plugins container image was available from the `k8s.gcr.io` container registry.

**Comment by seanmalloy** [comment]
I set this up for the descheduler. I believe I have the bandwidth to set this up for the scheduler-plugins too. Let me know if this is something the project would be interested in and I could start the process to get this setup.

**Comment by denkensk** [comment]
We put the images of scheduler-plugins in `https://hub.docker.com/r/sched/plugins` before.  
I think it's better to put our official container images in `k8s.gcr.io` too.
Thanks so much. @seanmalloy 
/cc @Huang-Wei

**Comment by seanmalloy** [comment]
@denkensk and @Huang-Wei will this repo always create a single container image? Or is there a possibility of multiple container images(one per plugin) in the future?

I'll start working on this soon-ish. It is a multi-step process. I'll ensure both of you are cc'd on all the pull requests. Let me know if you have any questions.

/assign

**Comment by Huang-Wei** [comment]
Thanks @seanmalloy for raising this up. It's essential to have an official container image.

> will this repo always create a single container image?

The repo (we can decide later whether it's dockerhub, gcr, or even [github container registry](https://github.blog/2020-09-01-introducing-github-container-registry/)) will have multiple containers. Some ideas in my mind atm:
- plugins - this serves as an all-in-one scheduler binary which packages all present plugins
- controller - some plugins may need separate CRDs to function, and the controller logic would be better to be packaged as a separate image
- admission webhook - some plugins may need this

> Or is there a possibility of multiple container images(one per plugin) in the future?

That is way too much, at least at this moment. Once an all-in-one binary is available, users can choose to, or not to enable some plugins by configuring the scheduling profiles. The image size _may be_ concerning in the future, but it's now not a big problem (~15MB for the [v0.18.800](https://hub.docker.com/layers/sched/plugins/v0.18.800/images/sha256-b8059bb3fcc688ae572949e9b5a7540b2e41075338e3c6b35bcf21f87063c6d1?context=explore) cut).

**Comment by seanmalloy** [comment]
> The repo (we can decide later whether it's dockerhub, gcr, or even [github container registry](https://github.blog/2020-09-01-introducing-github-container-registry/)) will have multiple containers. Some ideas in my mind atm:
> 
> * plugins - this serves as an all-in-one scheduler binary which packages all present plugins
> * controller - some plugins may need separate CRDs to function, and the controller logic would be better to be packaged as a separate image
> * admission webhook - some plugins may need this

@Huang-Wei thanks for the info. I'll move forward with getting the `k8s.gcr.io` container registry setup. All three of these container images should be able to go into a single registry just fine.

The "plugins" container image would end up working something like what I have below. The important part is the agreement on naming of the registry(`k8s.gcr.io/scheduler-plugins`). The image name and tag(`kube-scheduler:v0.18.800`) are 100% controlled by the build automation in the `kubernetes-sigs/scheduler-plugins` repo(Makefile and Dockerfile).

```
docker pull k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.800
```

I'll go ahead and submit the PR to get the `k8s.gcr.io/scheduler-plugins` registry setup. We can finalize the name as part of the PR review process.

**Comment by seanmalloy** [comment]
PR to complete the first step: https://github.com/kubernetes/k8s.io/pull/1213

**Comment by Huang-Wei** [comment]
Thanks a lot @seanmalloy !

The registry name `k8s.gcr.io/scheduler-plugins` looks good to me.

**Comment by seanmalloy** [comment]
The first step is done.

I will work on the remaining steps in the near future.

Step 2:
Update this repo(Makefile, Dockerfile, documentation), so that project maintainers can build and push container images to the staging registry.

Step 3:
Enable automated container image builds using a Prow job.

**Comment by seanmalloy** [comment]
Pull request for step 2: https://github.com/kubernetes-sigs/scheduler-plugins/pull/51

**Comment by seanmalloy** [comment]
Pull request for step 3: https://github.com/kubernetes/test-infra/pull/19215

**Comment by seanmalloy** [comment]
Final pull request with some small documentation tweaks: https://github.com/kubernetes-sigs/scheduler-plugins/pull/53. Assuming everything is working I'll close this issue once this PR is merged.

**Comment by seanmalloy** [comment]
The good news is the automated container image build jobs are now running.

The bad news is the builds jobs are failing:
https://storage.googleapis.com/kubernetes-jenkins/logs/post-scheduler-plugins-push-images/1306659384692051968/build-log.txt

It is not immediately obvious to me why it is failing. I'll try to figure this out and get it working.

**Comment by seanmalloy** [comment]
I started a thread in k8s slack to try and get some help: https://kubernetes.slack.com/archives/CCK68P2Q2/p1600404122002900

**Comment by seanmalloy** [comment]
@Huang-Wei @denkensk you should be able to view the more detailed build logs here ... https://console.cloud.google.com/cloud-build/builds/ca4ef3b8-98e8-4a61-96cc-c6d07c6c4c50?project=96918712006 using your Google account listed here https://github.com/kubernetes/k8s.io/blob/master/groups/groups.yaml#L1221-L1230.

I'm hoping I can figure this out once I have the logs.

**Comment by seanmalloy** [comment]
@Huang-Wei and @denkensk are you able to see the logs from this URL: https://console.cloud.google.com/cloud-build/builds/ca4ef3b8-98e8-4a61-96cc-c6d07c6c4c50?project=96918712006. Please provide the logs when you get a chance.

Thanks!

**Comment by Huang-Wei** [comment]
@seanmalloy There are 2 logs in the URL you provided:

- build summary - https://gist.github.com/Huang-Wei/6bfa75d0eda7ccae80c4a91db32621b5
- 0: gcr.io/k8s-testimages/gcb-docker-gcloud:v20190906-745fed4
push-release-image - https://gist.github.com/Huang-Wei/1599bd8dcf8ad8b5d20d7b9a4a45dcfd

**Comment by Huang-Wei** [comment]
I think it's due to recent changes on separating Docker files into `build/scheduler` and `build/controller`:

```
docker build -t gcr.io/k8s-staging-scheduler-plugins/kube-scheduler: .
invalid argument "gcr.io/k8s-staging-scheduler-plugins/kube-scheduler:" for "-t, --tag" flag: invalid reference format
```

**Comment by Huang-Wei** [comment]
> I think it's due to recent changes on separating Docker files into `build/scheduler` and `build/controller`:

Oh wait, the changes were [merged 17 hours ago](https://github.com/kubernetes-sigs/scheduler-plugins/pull/52#event-3791327915). Maybe not relevant, at least for the previous failure: https://github.com/kubernetes-sigs/scheduler-plugins/issues/47#issuecomment-694890518.

@seanmalloy do you want the logs for the previous run at https://github.com/kubernetes-sigs/scheduler-plugins/issues/47#issuecomment-694890518?

**Comment by seanmalloy** [comment]
> > I think it's due to recent changes on separating Docker files into `build/scheduler` and `build/controller`:
> 
> Oh wait, the changes were [merged 17 hours ago](https://github.com/kubernetes-sigs/scheduler-plugins/pull/52#event-3791327915). Maybe not relevant, at least for the previous failure: [#47 (comment)](https://github.com/kubernetes-sigs/scheduler-plugins/issues/47#issuecomment-694890518).
> 
> @seanmalloy do you want the logs for the previous run at [#47 (comment)](https://github.com/kubernetes-sigs/scheduler-plugins/issues/47#issuecomment-694890518)?

@Huang-Wei I think the logs you provided give me enough info to try and fix this.

**Comment by seanmalloy** [comment]
Proposed fix for the builds errors https://github.com/kubernetes-sigs/scheduler-plugins/pull/62.

**Comment by seanmalloy** [comment]
The latest build failure for the master branch is here: https://storage.googleapis.com/kubernetes-jenkins/logs/post-scheduler-plugins-push-images/1311031861232799744/build-log.txt

@Huang-Wei and @denkensk could one of you get me the detailed build logs for the latest failure when you get a chance?

Here are the URL for the detailed builds logs: https://console.cloud.google.com/cloud-build/builds/3e838419-baa1-46ed-a980-a95dd21b6147?project=96918712006

Once I have the updated logs I will try to get some help in `#wg-k8s-infra` on Slack to track down the build failure.

**Comment by Huang-Wei** [comment]
@seanmalloy here is the logs:

- build-log.txt: https://pastebin.com/92PDWY92

- Build log: https://pastebin.com/dXRucHea
- 0: gcr.io/k8s-testimages/gcb-docker-gcloud:v20190906-745fed4 push-release-image: https://pastebin.com/S5ZuJaFL

**Comment by seanmalloy** [comment]
I have started the follow up conversation up in `#wg-k8s-infra` on Slack.

https://kubernetes.slack.com/archives/CCK68P2Q2/p1601615022008600?thread_ts=1600404122.002900&cid=CCK68P2Q2

**Comment by seanmalloy** [comment]
I got an answer in Slack. I'm going to try this.

https://github.com/kubernetes/test-infra/tree/master/config/jobs/image-pushing#custom-substitutions

**Comment by seanmalloy** [comment]
I think this is it ... #67.

**Comment by seanmalloy** [comment]
I was able to pull images from the staging registry.
```
docker pull gcr.io/k8s-staging-scheduler-plugins/kube-scheduler:v20201005-v0.18.800-38-g1581a08
docker pull gcr.io/k8s-staging-scheduler-plugins/controller:v20201005-v0.18.800-38-g1581a08
```

**Comment by seanmalloy** [comment]
Last two pull requests are #68 and #69. After these are merged I will close out this issue.

**Comment by seanmalloy** [comment]
It looks like everything is working now. The official containers images can be promoted to k8s.gcr.io once the next scheduler-plugins release is created. @Huang-Wei and @denkensk let me know if you have any outstanding questions or issues with the container images builds when you do the next release. Thanks!

/close
