### ISSUE TITLE
pod group min available is never updated

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#49]
Pod group info is never updated, unless all pods are removed and GC happens.

Because of that scenarios such as scaling up the pod group will not work.

Integration test that should work but fails:

```go
		{
			name: "equal priority, pod group is scaled up",
			pods: []podInfo{
				{podName: "t8-p1-1", podGroupName: "pg8-1", minAvailable: "2", priority: midPriority, memReq: 50},
				{podName: "t8-p1-2", podGroupName: "pg8-1", minAvailable: "2", priority: midPriority, memReq: 50},
				{podName: "t8-p1-3", podGroupName: "pg8-1", minAvailable: "3", priority: midPriority, memReq: 50},
			},
			expectedPods: []string{"t8-p1-1", "t8-p1-2", "t8-p1-3"},
		},
```

**Comment by denkensk** [comment]
We add the check in `prefilter` to keep the value unchanged. @mateuszlitwin 
https://github.com/kubernetes-sigs/scheduler-plugins/blob/affecd7b5664b5ac0c66ffb6f1dee0b25d79795f/pkg/coscheduling/coscheduling.go#L214-L217

**Comment by denkensk** [comment]
And also we will add the CRD for PodGroup recently. 
FYI: https://github.com/kubernetes-sigs/scheduler-plugins/pull/42

**Comment by mateuszlitwin** [comment]
I found a workaround for scaling up/down. 

Basically after scaling up/down relabel existing pods with the new podgroup (new name and new size matching desired number of replicas).

**Comment by yuanchen8911** [comment]
`minAvailable` handling is tricky and error prone. The current implementation in PreFilter just checks if minAvailable defined in each pod spec. is identical.  If we allow an arbitrary update of minAvailable, the gang scheduling semantics  could be violated.  
However, we can probably make an improvement  for PodGroup deletion, update and resubmission cases. 

When a new pod with a PodGroup is submitted, if the PodGroup exists but is to be cleaned up (GC), we just reset its status to active and update its minAvailable using the new Pod's if different.  Thus, we do not need to do GC very frequently. 

@denkensk  @Huang-Wei  WDYT

**Comment by seanmalloy** [comment]
@yuanchen8911 I see #64 is merged, so can this issue be closed?

**Comment by Huang-Wei** [comment]
We will revisit it once the new implementation based CRD is released.

/remove-lifecycle stale

**Comment by denkensk** [comment]
> We will revisit it once the new implementation based CRD is released.

The new implementation based CRD has been released.
/close
