### ISSUE TITLE
Define release and golang vendor strategy

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#5]
Draft a document to clearly define the release and code endorsing strategy (with upstream k8s codebase).

Ref: https://github.com/kubernetes-sigs/scheduler-plugins/pull/3#pullrequestreview-387496431

**Comment by riverzhang** [comment]
![20200627170015492](https://user-images.githubusercontent.com/24387537/85918762-18de8f00-b898-11ea-9be5-7cdbfad85719.png)
I want to know the specific version of kube-scheduler we are running, and hope it can be resolved here.
I read the following parameters added by kubernetes.
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh#L791
https://github.com/kubernetes/kubernetes/blob/master/hack/lib/version.sh#L151

**Comment by Huang-Wei** [comment]
@riverzhang it's 1.18.0 for now, which is specified in 

https://github.com/kubernetes-sigs/scheduler-plugins/blob/47e371acbf54443fba23c5b811be4d5cf97a6907/go.mod#L10

**Comment by xujyan** [comment]
As we add more plugins and formalize the releases, I think we need a version that represents the code in this repo itself? e.g., `v0.0.1-kubernetes1.18.0`?

As the complexity of the codebase grows, the scheme `1.18.1+patch1` probably won't be sufficient to cover something like "this new release of coscheduling plugin is a major enhancement"

**Comment by Huang-Wei** [comment]
@xujyan your point is fair. Another versioning idea is like this:

- use `major` and `minor` to represent the k8s version this repo is compatible with: i.e., `v1.18.<patch>` (we can discuss later, to start with v0.18 or v1.18). However, the `patch` number may not be strictly consistent with the upstream k8s patch version. Say `scheduler-plugin` version v1.18.0 may use upstream k8s version v1.18.3.
- the `patch` version used in this repo is just used to manage the features. For instance, v1.18.0 contains the initial implementation of coscheduling, v1.18.1 contains an enhanced version of scheduling, and the changelog will be documented.

WDYT?

**Comment by xujyan** [comment]
- Will the fact that the plugins version v1.18.3 not correspond to kubernetes v1.18.3 surprise people? Of course if there's precedence in other k8s projects it's probably more acceptable.
- If we use `patch` version to indicate features in this repo, then
  - the version can be large. e.g., would `v1.19.5000` be acceptable? (My intuition is that it's probably fine)
  - For the same plugins feature to migrate to a new kubernetes version, do we keep the `patch` version to establish equivalency? e.g., does `v1.18.10` map to `v1.19.10` (alternatively the `patch` counter resets to `0` and we lose consistency)?
  - If the plugin version itself needs to be semvar then this scheme breaks but I guess it's probably fine since we don't expect some downstream project in turn require semvar for compatibility semantics on the plugins. Right?

**Comment by Huang-Wei** [comment]
> Will the fact that the plugins version v1.18.3 not correspond to kubernetes v1.18.3 surprise people? Of course if there's precedence in other k8s projects it's probably more acceptable.

Probably. I don't see a good pattern in other projects except for those staging repos. I think descheduler also has this problem. Once it's well documented, it should be fine IMO.

> the version can be large. e.g., would v1.19.5000 be acceptable?

That may work, although the implicit assumption needs to be documented as well - the last N digits as scheduler-plugin version.

> For the same plugins feature to migrate to a new kubernetes version, do we keep the patch version to establish equivalency?

Nope, I don't think they're related.

> If the plugin version itself needs to be semvar then this scheme breaks but I guess it's probably fine since we don't expect some downstream project in turn require semvar for compatibility semantics on the plugins. Right?

We just need a bundled version for all the plugins, managing versioning for each plugin is way too much burden IMO.

**Comment by xujyan** [comment]
>> For the same plugins feature to migrate to a new kubernetes version, do we keep the patch version to establish equivalency?

> Nope, I don't think they're related.

In that case when a plugin releases a new feature I'd have say "it's in 1.20.200, 1.19.150 and 1.18.133". With the patch version all different it's a bit. Compared to "it's in 1.20.200, 1.19.200 and 1.18.200", the former is clearer with no obvious drawback?

> We just need a bundled version for all the plugins, managing versioning for each plugin is way too much burden IMO.

Yeah for sure. Agreed.

**Comment by Huang-Wei** [comment]
@xujyan I'm still not a fan of managing patch version that way.

Per https://semver.org/#spec-item-7 and https://semver.org/#spec-item-8:

> Patch version MUST be reset to 0 when minor version is incremented.
> Patch and minor version MUST be reset to 0 when major version is incremented.

We should follow the semver semantics, which is also the convention of Kubernetes releases.

**Comment by xujyan** [comment]
Cool the links are useful. yeah ok if we are sticking to strict semvar yeah then we have to live with it. I am fine with that.

I just thought our usage is "fake semvar", a portmanteau with MAJOR.MINOR representing scheduler version and PATCH representing "plugins version" so I can refer to some change as in "plugins version 200, scheduler version whatever".

But I am not adamant about it. Are you looking for more input or ready to tag a version now? :)

**Comment by Huang-Wei** [comment]
> I just thought our usage is "fake semvar"

Yes, while complying with semver semantics, we have the right to definite the real-world meaning of it.

> Are you looking for more input or ready to tag a version now? :)

Yes, feedback is always appreciated. And we may do the first cut when k8s v1.19.0 is out (end of August).

**Comment by seanmalloy** [comment]
@Huang-Wei and @denkensk are we good to close out this issue, or do we still need to document the versioning scheme somewhere?

**Comment by Huang-Wei** [comment]
We already have a conclusion, but let's keep it open as it needs to be documented clearly as a standalone document.

As a wrap-up, we will use a tag such as `v0.19.0` to cut release in `release-v1.19` branch, which locks the deps to the Kubernetes components. And we create images on demand, for example, suppose we developed some new features and needs a cut on `release-v1.19`:

- if the upstream has a newer version, such as `v0.19.5`, we will update the deps and create a new tag `v0.19.5`.
- if the upstream still stays at `v1.19.0`, we will create a tag like `v0.19.001` for differentiation. (I guess this case would be very rare)

**Comment by seanmalloy** [comment]
> We already have a conclusion, but let's keep it open as it needs to be documented clearly as a standalone document.
> 
> As a wrap-up, we will use a tag such as `v0.19.0` to cut release in `release-v1.19` branch, which locks the deps to the Kubernetes components. And we create images on demand, for example, suppose we developed some new features and needs a cut on `release-v1.19`:
> 
> * if the upstream has a newer version, such as `v0.19.5`, we will update the deps and create a new tag `v0.19.5`.
> * if the upstream still stays at `v1.19.0`, we will create a tag like `v0.19.001` for differentiation. (I guess this case would be very rare)

@Huang-Wei  I attempted to update the end user docs with the relevant bits in #107. I can add additional info to file `doc/release-guide.md` in a separate PR if you think additional details are needed for project maintainers.
