### ISSUE TITLE
noderesourcetopology plugin: implement proper plugin args validation logic

### ISSUE THREAD

**Issue by ffromani** [kubernetes-sigs/scheduler-plugins#507]
TL;DR: address https://github.com/kubernetes-sigs/scheduler-plugins/pull/474#discussion_r1086235462

This plugin should hook in the existing plugin argument validation logic, removing code from the plugin application code itself.

**Comment by PiotrProkop** [comment]
I can tackle this one after https://github.com/kubernetes-sigs/scheduler-plugins/pull/488 will be merged.

**Comment by ffromani** [comment]
> I can tackle this one after #488 will be merged.

that would be awesome. I'd be happy to review.
