### ISSUE TITLE
[Coscheduling] test: need a integration test for PodGroup Status

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/scheduler-plugins#516]
we have an integration test for coscheduling, https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/test/integration/coscheduling_test.go, but it did not test the PodGroup status.

if PodGroup Status is not functionally working, we can not found the issue

**Comment by Huang-Wei** [comment]
We didn't invest too much effort in the controller's quality TBH. We can polish the controller code, along with adequate tests once we finish the migration to ctrl-runtime.

**Comment by Gekko0114** [comment]
Hi @zwpaper ,
Can I work on this issue if you don't plan to work on it?

**Comment by zwpaper** [comment]
Hi @Gekko0114, feel free to take and work on it!

/assign @Gekko0114
