### ISSUE TITLE
[CapacityScheduling] Proposal to Add Warning and Restriction for Multiple elasticQuotas in One Namespace

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/scheduler-plugins#518]
It's currently assumed that developers will create only one `elasticQuota` for each namespace.
However, it is possible to create multiple `elasticQuota`s in a single namespace.

I would like to propose two changes to address this issue:
1. We should add a warning not to create multiple `elasticQuota`s in a single namespace in README.md
2. If possible, we should restrict the creation of only one `elasticQuota` per namespace

If this propose seems reasonable, I would be happy to work on implementing these changes.

**Comment by Gekko0114** [comment]
/assign

I will fix it by using validationwebhook or similar functions after completing this PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/527.

**Comment by Huang-Wei** [comment]
@Gekko0114 we're not deciding to introduce the complexity of having a validationwebhook yet.

I want to hold this until it's a must-have. But it's good to keep it as a good-to-have list that relies on webhook.

**Comment by Gekko0114** [comment]
@Huang-Wei 
Thank you for your response! 
I agree that introducing a `validationwebhook` can make repository more complicated.
However, with the current implementation, it is possible to create multiple `ElasticQuota` in a single `namespace`, but only one of them will actually work.

This could be confusing for developers. In my opinion, we should introduce a `validationwebhook`. Please let me know when the policy for scheduler-plugins is decided!
