### ISSUE TITLE
Request for documentation on "how to change cluster's KubeSchedulerConfiguration"

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/scheduler-plugins#524]
It is very difficult to understand how to apply `KubeschedulerConfiguration` to my cluster. 
I thought `KubeSchedulerConfiguration` was a type of `CRD`, but I couldn't find it by searching for `CRD`s. 
Eventually, after searching for past issues, I understood that I needed to rewrite the command in `kube-scheduler` deployment. 
It is very confusing.

Therefore, I would like to request documentation on how to modify `KubeschedulerConfiguration`.
It would be greatly appreciated.

**Comment by Huang-Wei** [comment]
> I thought KubeSchedulerConfiguration was a type of CRD

Nope, it's not. It's a so-called "ComonentConfig" concept which is a variant over CLI args, aiming to provide a more structured, versioned, migration-friendly configuration struct for easy maintenance.

The "ComonentConfig" concept is widely used across the Kubernetes ecosystem, like controller-manager, scheduler, etc. And IIRC kubebuilder also provides an option to generate a tailored ComponentConfig for controllers. https://book.kubebuilder.io/component-config-tutorial/tutorial.html can be a start to understand the concept generally.

**Comment by Gekko0114** [comment]
Thank you for the information!
This issue can be resolved by reading this document or other resources, so I will close this issue. Thank you for commenting.
