### ISSUE TITLE
Changing all *.k8s.io labels/annotations to *.x-k8s.io

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#525]
Background: https://github.com/kubernetes/website/issues/37589#issuecomment-1446465480

> Kubernetes reserves all labels and annotations in the kubernetes.io and k8s.io namespaces.

This is against this repo's expectations as scheduler-plugins are not part of the vanilla default-scheduler.

**Comment by Huang-Wei** [comment]
We may need to change the CRDs group version to x-k8s.io as well. These 2 changes are breaking changes that need to be documented clearly.

**Comment by Huang-Wei** [comment]
@jpedro1992 FYI: we may need to refrain from using API group containing "k8s.io" and "kubernetes.io".

After @526 gets merged, network aware scheduling related CRDs are the only leftover needs to change:

```
⇒  ag "scheduling.sigs.k8s.io"
kep/260-network-aware-scheduling/README.md
169:  name: appgroups.scheduling.sigs.k8s.io
171:  group: scheduling.sigs.k8s.io
361:apiVersion: scheduling.sigs.k8s.io/v1alpha1
627:  name: networktopologies.scheduling.sigs.k8s.io
629:  group: scheduling.sigs.k8s.io
771:apiVersion: scheduling.sigs.k8s.io/v1alpha1
1149:apiVersion: scheduling.sigs.k8s.io/v1alpha1
1198:apiVersion: scheduling.sigs.k8s.io/v1alpha1

manifests/appgroup/cluster-role.yaml
12:  - apiGroups: [ "scheduling.sigs.k8s.io" ]

manifests/networktopology/cluster-role.yaml
12:  - apiGroups: [ "scheduling.sigs.k8s.io" ]
```

**Comment by jpedro1992** [comment]
Hi @Huang-Wei, Thanks for letting me know. I will have a look and update the manifests accordingly. 

Also, should we modify diktyo.io as well?  

```
- apiGroups: ["appgroup.diktyo.k8s.io"]
  resources: ["appgroups"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
- apiGroups: ["networktopology.diktyo.k8s.io"]
  resources: ["networktopologies"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
```

**Comment by Huang-Wei** [comment]
> Also, should we modify diktyo.io as well?

I think so, we just try not to use *.k8s.io or *.kubernetes.io; otherwise we need to document it in the upstream, which doesn't make sense.
