### ISSUE TITLE
[noderesourcetopology]: remove/simplify the custom indexer

### ISSUE THREAD

**Issue by ffromani** [kubernetes-sigs/scheduler-plugins#552]
now that rebased on top of 1.26 (actually we needed 1.25) we can simplify or hopefully get rid of the custom replacement we had to have for the client-go indexer, and use the standard machinery. See https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/noderesourcetopology/cache/indexer.go#L29 for details.

We should have no regression or change in behavior, just code simplification

**Comment by czybjtu** [comment]
I'd like to try to work on it.
/assign
