### ISSUE TITLE
PodGroupStatus.Scheduled is not updated due to the removal of PostBind

### ISSUE THREAD

**Issue by Gekko0114** [kubernetes-sigs/scheduler-plugins#562]
The removal of the [PostBind](https://github.com/kubernetes-sigs/scheduler-plugins/pull/554) function for `PodGroups` has caused the `podgroupstatus.scheduled` field to no longer update and remain at 0. 
After the [PR of integration test for `PodGroups`](https://github.com/kubernetes-sigs/scheduler-plugins/pull/549) is merged, the `podgroupstatus.scheduled` field can be safely removed as it will no longer be necessary.

**Comment by Gekko0114** [comment]
/assign
I will do it if this issue is correct

**Comment by czybjtu** [comment]
https://github.com/kubernetes-sigs/scheduler-plugins/blob/3d7104edb4b9805b76e42d202ed28cb50d42de13/pkg/coscheduling/core/core.go#L215

maybe we should add this in podgroup controller?

**Comment by Gekko0114** [comment]
As you mentioned earlier, removing this code caused the problem.
However, we can't add https://github.com/kubernetes-sigs/scheduler-plugins/blob/3d7104edb4b9805b76e42d202ed28cb50d42de13/pkg/coscheduling/core/core.go#L215 to `Reconcile` function because `Reconcile` runs regularly. If we were to add this code to the `Reconcile` function, we would not be able to accurately count the number of scheduled pods.

Instead of using `podGroupStatus.Scheduled`, changing [this line](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/controllers/podgroup_controller.go#L125-L126) will fix the bug in the `podGroup` (also we should remove some `podGroupPhase`). Therefore, after merging [this PR](https://github.com/kubernetes-sigs/scheduler-plugins/pull/549), `podGroupStatus.Scheduled` will be removed.

Please let me know if I have misunderstood anything.
