### ISSUE TITLE
[CapacityScheduling] ElasticQuota should support multiple namespaces

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes-sigs/scheduler-plugins#564]
In my cloud scene, we will create different namespaces for every user so that they will not see workloads belong to others.
And we want to create different quota for different departments.
Because these users may belong to different departments, we will use one ElasticQuota to control workloads in different namespaces.
So we think ElasticQuota should support multiple namespaces.

**Comment by denkensk** [comment]
> In my cloud scene, we will create different namespaces for every user so that they will not see workloads belong to others.

Hi. Kun 😄 @KunWuLuan  Are you using namespaces to isolate users: a namespace per user? It's a little strange. Why not a namespace project? Because the users belonging to the same project also need to share something like a dataset or other resources together.

**Comment by KunWuLuan** [comment]
Thanks for replying. ❤️   @denkensk 

> Are you using namespaces to isolate users: a namespace per user

Yes, we will create a namespace for a user.
