### ISSUE TITLE
[Question] Scalability report of coscheduler

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/scheduler-plugins#575]
### Area

- [ ] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [X] Documents

### What happened?

Hello, We want to know if there are any performance tests or scalability report performed for co-scheduler?

### What did you expect to happen?

NA

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
NA
</details>

### Scheduler Plugins version

<details>
NA
</details>

**Comment by zwpaper** [comment]
/remove kind/bug
/kind support

not yet found a report like that, maybe we have to seek @Huang-Wei's help.

**Comment by Huang-Wei** [comment]
If you meant a comprehensive scalability test, nope, we don't have enough resource and $ to run that.

But if you meant some preliminary benchmark number, it's doable. @asm582 which particular scalability test do you want? and are you using this test result to do some technical decision among coscheduling itself, or to other scheduler's coscheduling feature?

**Comment by Huang-Wei** [comment]
> Can you share how preliminary benchmarks could be run?

Due to this is a scalability test, and you only care about scheduler, [kwok](https://kwok.sigs.k8s.io/) is a good tool to setup a bare bone control plane plus thousands of fake nodes. So in this simulated env, you can prepare your testing workloads, and have coscheduler running, and then measure the metrics you care about.

**Comment by asm582** [comment]
@Huang-Wei  Thanks, Are the below step correct to run experiments:
- Create a KinD cluster and install a co-scheduler on it
- Create another KWOK cluster and in it create fake nodes, let's say 50 nodes.
- Submit test jobs to the KinD cluster and let the co-scheduler schedule it on fake nodes created by KWOK using labels

How can the sample mentioned [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/coscheduling/README.md#demo)  run on fake nodes when they done have any real resources?

**Comment by zwpaper** [comment]
hi @asm582, kwok will simulate nodes to the real APIServer, so APIServer and Scheduler will treat fake nodes as real ones.

ref to https://kwok.sigs.k8s.io/docs/user/kwok-manage-nodes-and-pods/#create-a-pod, you can add the toleration and nodeSelector(or nodeAffinity) to let pod run on fake nodes

**Comment by Huang-Wei** [comment]
> How can the sample mentioned [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/coscheduling/README.md?rgh-link-date=2023-04-29T22%3A25%3A58Z#demo) run on fake nodes when they don't have any real resources? should they be converted into fake deployments?

Yes, those are fake workloads indeed, so it's expected for them to land on fake nodes. And we measure the scheduler's metrics like latency.
