### ISSUE TITLE
Question: Any plan to release v0.26.x ?

### ISSUE THREAD

**Issue by yanxiucai** [kubernetes-sigs/scheduler-plugins#586]
Hi @Huang-Wei 

Do we have any plan to release v0.26.x to sync with Kubernetes 1.26?

Thanks！

Yanxiu Cai

**Comment by Huang-Wei** [comment]
The release cadence is 3~4 months, so 1.26 should be in next month.

**Comment by yanxiucai** [comment]
Got it. Thanks!
