### ISSUE TITLE
Supports for K8s 1.26.0

### ISSUE THREAD

**Issue by xfyan0408** [kubernetes-sigs/scheduler-plugins#597]
### Area

- [X] Scheduler
- [X] Controller
- [X] Helm Chart
- [X] Documents

### What happened?

Wait for the scheduler 0.26

### What did you expect to happen?

Hello, how long will K8s 1.26.6 be supported?
I've been using 1.26 for a while and have been waiting for this release.
Thanks for your reply!

### How can we reproduce it (as minimally and precisely as possible)?

0

### Anything else we need to know?

0

### Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:56:58Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.6", GitCommit:"11902a838028edef305dfe2f96be929bc4d114d8", GitTreeState:"clean", BuildDate:"2023-06-14T09:49:08Z", GoVersion:"go1.19.10", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Scheduler Plugins version

<details>
0.26
</details>

**Comment by zwpaper** [comment]
hi @linhil, thanks for asking, the master branch is targeting 1.26.3, but AFAIK, we have no plan for a fixed release schedule.

/remove-kind bug
/kind support

**Comment by Huang-Wei** [comment]
Per this project's release cadence (3~4 months), I will start work on 1.26 release next week.
