### ISSUE TITLE
[NodeResourceTopology] the plugin should be able to list pods in terminal state

### ISSUE THREAD

**Issue by ffromani** [kubernetes-sigs/scheduler-plugins#598]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

A key feature of the NodeResourceTopology plugin is the pessimistic caching, described in detail [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/v0.25.7/pkg/noderesourcetopology/cache/docs/NUMA-aware-scheduler-side-reserve-plugin.md)

In a nutshell, to enable proper resync the scheduler needs to periodically evaluate the set of pods running on a node.
Here "running" however doesn't mean "running" in kubernetes sense (actually doing work) but in general "existing with resources assigned" because these pods consume resources, which can't thus be allocated to other containers until the pods are cleaned.

This includes pods in terminal state which are not immediately cleaned up. Kubernetes jobs are the main way to get in this state.
[The scheduler framework explicitly filters out such pods on its watcher](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/scheduler.go#L505). Thus, the scheduler side will never see pod in terminal phase.

On the node side, the kubelet reports through the podresources API pods in terminal phase until they are cleaned up by the system. The correctness of this behavior is being investigated **also** on kubelet side.

### What did you expect to happen?

To the best of my knowledge, this is the only plugin which requires listing pod in terminal phase.
If so, it seems too risky and invasive to propose any scheduler framework change just to accomodate this need.
The best option seems to optionally allow this plugin to open a separate listwatch (through a new informer probably) to the apiserverver, allowing consumers of the plugin to choose between extra load to the apiserver (albeit arguably limited and predictable) or accepting the risk of scheduler misalignment.

### How can we reproduce it (as minimally and precisely as possible)?

1. deploy nfd-topology-updater to provide NodeResourceTopology data (or also https://github.com/k8stopologyawareschedwg/resource-topology-exporter or any other equivalent tool)
2. deploy a scheduler with a profile with NodeResourceTopology **and the cache** enabled (filter+reserve+cacheResyncPeriod option)
3. run a trivial job which just do "echo something" or sleeps for 0.1s and spans all the node 
4. observe all the pods managed by the profile with NodeResourceTopology **and the cache** enabled stay "Pending" forever, the plugin filters out all the nodes with "invalid topology data"

### Anything else we need to know?

The NodeResourceTopology is meant to tolerate _temporary_ misalignment and _temporarily_ filter out nodes on which the misalignment is detected with "invalid node topology". The problem here is there is no chance to converge ever because the node and the scheduler will observe different set of pods which can never converge, because the scheduler filters out pods in terminal state, which are relevant in this case (and probably _only_ in this case)

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
# Any version >= 1.25
```

</details>

### Scheduler Plugins version

<details>
Any version with the scheduler cache enabled (so >= 0.25.7)
</details>

**Comment by ffromani** [comment]
xref: https://github.com/kubernetes/kubernetes/issues/119423 (including discussion)

**Comment by Tal-or** [comment]
@ffromani In case of a fix such as https://github.com/kubernetes/kubernetes/pull/119553, is it correct to say that this issue is no longer an issue?

**Comment by ffromani** [comment]
@Tal-or yes. We need to make sure the scheduler and the kubelet can get the same picture. We can fix this many ways indeed.
