### ISSUE TITLE
CoScheduling: invoke getOrCreatePodGroupInfo in Permit and Unreserve plugins

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#63]
`getOrCreatePodGroupInfo` creates a new PodGroup or obtains the existing `PodGroupInfo`. It's required for `Less` and `PreFilter` as a PodGroup may not exist when a Pod reaches the two phases. However, PodGroup should already exist in `Permit` and `Unreserve.`  If not (due to GC or PodGroup expiration?),  a new PodGroup should not be created in the two phases. We may need a separate func for read operation `getPodGroupInfo`.

@denkensk  @Huang-Wei WDYT?

**Comment by Huang-Wei** [comment]
@yuanchen8911 We will land a CRD based implementation soon, based on a CRD context, if a Pod specified a non-existing PodGroup, the correct semantics is this Pod shouldn't be created, which can be guaranteed by an admission plugin - it's aligned with the community, e.g., a pod requests for a non-existing PriorityClass won't be created ([link])

[link]: https://github.com/kubernetes/kubernetes/blob/6e3ef0be163566c08398e1e5ff43f87accfb036b/plugin/pkg/admission/priority/admission.go#L187-L189

With that said, the CRD implementation should simplify the scenario a lot.

**Comment by Huang-Wei** [comment]
This has been stale.
