### ISSUE TITLE
Trimaran common function minor bug fix

### ISSUE THREAD

**Issue by knarayan** [kubernetes-sigs/scheduler-plugins#636]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

This issue fixes below minor bugs found during code walk through:

1. Bug-1: Trimaran handler.go function `OnDelete()` needs to delete a node from `ScheduledPodsCache` if the pod being deleted is the last one associated with that node.
>https://github.com/kubernetes-sigs/scheduler-plugins/blob/efddd13fd45d3e35018976ba029f9980a3b77a18/pkg/trimaran/handler.go#L124
2. Bug-2: Trimaran handler.go function `cleanupCache()` deletes older entries. The variable `idx` represents the index of the first element whose timestamp is within the current interval (assuming the entries are in ascending order of timestamps). When `idx == len(cache)`, all the entries are to be deleted as it indicates that all the elements are older. However, the code currently doesn't delete any element if all the entries are older.
>https://github.com/kubernetes-sigs/scheduler-plugins/blob/efddd13fd45d3e35018976ba029f9980a3b77a18/pkg/trimaran/handler.go#L149

### What did you expect to happen?

The issues above are functionality bugs.

1. If we don't fix the cleaning the cache entry map as part of the Bug-1 reported above, then it results into not optimally managing the cache map.
> Function `TestHandlerCacheAddUpdateDelete` with test cases is added to `scheduler-plugins/pkg/trimaran/handler_test.go` to exercise this. The test cases in this function will fail without this source code change.
2. If we don't change the if condition `idx == len(cache)` to address the Bug-2 reported above, then entries outside of the current interval continue to be part of the cache.
> `cleanupCache_deletes_old_pods_and_node_entry_with_empty_cache` added to the function `TestHandlerCacheCleanup()` of scheduler-plugins/pkg/trimaran/handler_test.go to exercise this scenario will fail without this source code change.

### How can we reproduce it (as minimally and precisely as possible)?

Test cases were added to reproduce these issues. Without the changes to the file `scheduler-plugins/pkg/trimaran/handler.go`, the test cases that are added as specified above will fail.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>
</details>

**Comment by Huang-Wei** [comment]
/assign @atantawi @wangchen615 

could you please help take a look at the issue and PR?
