### ISSUE TITLE
netlify CI failure

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#637]
@zwpaper could you take a look at the netlify CI failure? It surfaced in all PRs.

**Comment by zwpaper** [comment]
actually not all PRs, the docs PR seems ok https://github.com/kubernetes-sigs/scheduler-plugins/pull/634#issuecomment-1709424236

let me have a look at the trimaran one

**Comment by zwpaper** [comment]
as we introduced the netlify site recently, PRs may fail if they are not rebased onto the master.

if a netlify build failed in PR, just make sure it is up to date.

/close
