### ISSUE TITLE
A new scheduler plugin for rescheduling scheduled pods which encountered some errors to other nodes

### ISSUE THREAD

**Issue by freelizhun** [kubernetes-sigs/scheduler-plugins#640]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

The current kubernetes scheduler can't support rescheduling already scheduled pods (encounter some errors) to other nodes. for example, a pod may be OOM killed because of the pod's increasing usage of memory and node's insufficient system memory. The in-place restart strategy in pod does not solve the problem of pod exceptions and requires manual intervention to reschedule pods to other nodes. This limits the automatic fault tolerance of the system and reduces the reliability and high availability of the service.

A pod rescheduling plugins  reschedules pods (encounter some errors) to other nodes, excluding nodes that the pod has already scheduled

### What did you expect to happen?

A pod rescheduling scheduler plugin KEP proposal and corresponding implementation

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>

</details>

**Comment by Huang-Wei** [comment]
@freelizhun this problem domain more falls into some external controllers like descheduler rather than scheduler itself. I think separating the concerns work most for both scheduler and descheduler-like remediation solutions.

**Comment by freelizhun** [comment]
Our scheme is to design two components. One is that the controller is responsible for listening to the pods (encounter some errors) in the cluster, and records the node names of the pod that have been scheduled into the annotation.

The other component is the scheduler-plugins that extend the PreFilter phase of the kube-scheduler  to filter out the scheduled nodes recorded in this pod annotation and schedule this pod to other nodes.

**Comment by Huang-Wei** [comment]
> One is that the controller is responsible for listening to the pods (encounter some errors) in the cluster, and records the node names of the pod that have been scheduled into the annotation.

I suppose this component would also clean .spec.nodeName at the same time? and it will also override the previous annotation when it OutOfXYZ?

> The other component is the scheduler-plugins that extend the PreFilter phase of the kube-scheduler to filter out the scheduled nodes recorded in this pod annotation and schedule this pod to other nodes.

SGTM.

**Comment by freelizhun** [comment]
Thank you @Huang-Wei for your reply!

**Comment by freelizhun** [comment]
> I suppose this component would also clean .spec.nodeName at the same time? and it will also override the previous annotation when it OutOfXYZ?

yes，we will delete this pods (encounter some errors) directly to invoke rescheduling, and record this pod.spec.nodeName info in it's controller (like deployment) annotations.
if pods (encounter some errors) without controller (like deployment) after deletion，we will record this pod.spec.nodeName info in memory and resubmit it with code.

**Comment by Huang-Wei** [comment]
Similar work is tracked on https://docs.google.com/document/d/1-wJhiNy84w7tzFdo9HqwTu5DrVSuXFLGTUv8FBiRAAc/edit
