### ISSUE TITLE
[Feature Request] Release version compiled with K8s v1.27

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/scheduler-plugins#651]
IIUC, this project used to be released per three ~ four month
And K8s v1.29 will be coming up soon, the latest scheduler plugins version will be older.

So, I would to request the new schedule plugins release compiled with K8s v1.27.

**Comment by tenzen-y** [comment]
@denkensk @Huang-Wei @zwpaper Do you have any plan for a new release?

**Comment by Huang-Wei** [comment]
@zwpaper do you think we have bandwidth to finish the migration to controller-runtime for all plugins in the near future? (I do want to) If so, I'd like to cut a release after that. If not, I may cut a release earlier.

@tenzen-y are you dependent on a new release? if so, what's the ETA you'd need it?

**Comment by tenzen-y** [comment]
> @tenzen-y are you dependent on a new release? if so, what's the ETA you'd need it?

@Huang-Wei Thanks for the response. I'm working on upgrading my cluster deeply depending on the scheduler-plugins. 
If it is possible, I think that avoid to do fork upstream and build on myself.

My hope is November early. If owners don't have enough time, I may be able to help with releasing slightly.

**Comment by Huang-Wei** [comment]
> If owners don't have enough time, I may be able to help with releasing slightly.

Thanks for offering the help. The release process is semi-automated, so won't take that amount of time. Some of the steps need special privileges like checking the staging build sha1 in gcloud console, so it's hard to delegate to others.

Let's wait for @zwpaper to respond on the plan of controller-runtime migration.

**Comment by tenzen-y** [comment]
> > If owners don't have enough time, I may be able to help with releasing slightly.
> 
> Thanks for offering the help. The release process is semi-automated, so won't take that amount of time. Some of the steps need special privileges like checking the staging build sha1 in gcloud console, so it's hard to delegate to others.
> 
> Let's wait for @zwpaper to respond on the plan of controller-runtime migration.

Yes, sure.

**Comment by zwpaper** [comment]
Sorry for the absence recently, it has been busy days, I could make some time to finish the WIP PR this weekend and it should be faster for the others after having that one migration experience.

**Comment by tenzen-y** [comment]
> Sorry for the absence recently, it has been busy days, I could make some time to finish the WIP PR this weekend and it should be faster for the others after having that one migration experience.

Thank you for the hard work!

**Comment by tenzen-y** [comment]
This is completed.
/close
