### ISSUE TITLE
Multiple informers for the same resource(NodeResourceTopologies) may be serving at the same time

### ISSUE THREAD

**Issue by NoicFank** [kubernetes-sigs/scheduler-plugins#656]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

# Why could this happen?
Once we configure plugin `NodeResourceTopologyMatch` in multi profiles(must more than one), then informers about NodeResourceTopologies may start multi times with different ShardInformerFactory.

Since informer about NodeResourceTopologies is created within this plugin's func New() [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/noderesourcetopology/plugin.go#L121-L125) as following:
```go
func New(args runtime.Object, handle framework.Handle) (framework.Plugin, error) {
	...
	nrtCache, err := initNodeTopologyInformer(tcfg, handle)
	...
```
And, informer about NodeResourceTopologies created from the `brandNew Factory` within func `initNodeTopologyInformer` [here](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/pkg/noderesourcetopology/pluginhelpers.go#L52-L54), as following:
```go
func initNodeTopologyInformer(tcfg *apiconfig.NodeResourceTopologyMatchArgs, handle framework.Handle) (nrtcache.Interface, error) {
	...
	topologyInformerFactory := topologyinformers.NewSharedInformerFactory(topoClient, 0)
	nodeTopologyInformer := topologyInformerFactory.Topology().V1alpha2().NodeResourceTopologies()
	nodeTopologyLister := nodeTopologyInformer.Lister()
        ...
}
```
Then, When we create scheduler profile one bye one, The func `New()` would be called many times, since plugin NodeResourceTopologyMatch exists in multiple profiles. Then multiple informers about NodeResourceTopologies will be produced.

# What are the negative effects?
- Data inconsistencies among those informers, even if the time difference is small.
- Waste of local storage: as multiple same indexer with the same content will exist

### What did you expect to happen?

# How to prevent it?
Creating NewSharedInformerFactory When we create Scheduler instead of creating plugins. And we pass the created Informers about CRD from NewSharedInformerFactory to those needed plugins while it started.

### Anything else we need to know?

@Huang-Wei  Please see if this issue makes sense, thanks.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>

</details>

**Comment by NoicFank** [comment]
This is a rough implementation to better state the solution. #657 

@Huang-Wei PTAL, thanks.

**Comment by Huang-Wei** [comment]
> Please see if this issue makes sense, thanks.

Yes, the issue is generic for plugins that are registered in multiple profiles but want to instantiate particular informers **once** in New().

**Comment by NoicFank** [comment]
> > Please see if this issue makes sense, thanks.
> 
> Yes, the issue is generic for plugins that are registered in multiple profiles but want to instantiate particular informers **once** in New().

Thank you for your speedy reply!

It's always a pleasure to ask you questions.

**Comment by NoicFank** [comment]
PR https://github.com/kubernetes-sigs/scheduler-plugins/pull/655 will fix this.

details:
https://github.com/kubernetes-sigs/scheduler-plugins/pull/657#discussion_r1382429599
