### ISSUE TITLE
Inappropriate error logging in capacity_scheduling.go

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#667]
https://github.com/kubernetes-sigs/scheduler-plugins/blob/fc5b4b296f6725c8ead647b9d9cca32f0118c642/pkg/capacityscheduling/capacity_scheduling.go#L404-L407

`ErrorS` doesn't seem appropriate as once a Pod is unschedulable, it will hit this line and error out. Changing to V(5) InfoS makes more sense.

/good-first-issue

**Comment by googs1025** [comment]
/close 
already fixed
