### ISSUE TITLE
Keep providing typed client/informer libs

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/scheduler-plugins#671]
I found that the scheduler-plugins plans to remove the typed client/informer in the release note:

> ⚠️ generated typed client/informer under [pkg/generated](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/generated) will be removed after 3 releases (v0.30.x). External repos that vendor this repo's typed generation code should either generate typed client/informer themselves or start migrating to generic controller-runtime client.

However, since we (kubeflow training) use the libs in [mpi-operator](https://github.com/kubeflow/mpi-operator/tree/master) based on the client-go, I want to keep using the typed client/informer. 

If the libs are removed, we (kubeflow) will need to generate the libs ourselves or re-architecture the mpi-operator based on the controller-runtime.
What are the blockers to keep providing the libs? If scheduler-plugins maintainers are looking for contributors, I can help maintain the libs. Thanks.

cc: @Huang-Wei @denkensk @zwpaper 
FYI to kubeflow/mpi-operator maintainers: @terrytangyuan @alculquicondor

**Comment by Huang-Wei** [comment]
> What are the blockers to keep providing the libs? If scheduler-plugins maintainers are looking for contributors, I can help maintain the libs.

If kubeflow wants to keep using typed client/informer, I'm ok with keeping them in the codebase actually.

It's just for scheduler-plugins repo, more CRDs are introduced along with new plugins, making a generic (dynamic) client offloads a lot of maintenance burden.

**Comment by tenzen-y** [comment]
> If kubeflow wants to keep using typed client/informer, I'm ok with keeping them in the codebase actually.

Yes, I want to keep using the typed libs. Thanks for your effort!

**Comment by terrytangyuan** [comment]
Yes we'd love to keep using them. Thank you!

**Comment by Huang-Wei** [comment]
Awesome. I updated https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.27.8 to claim the libs will still be maintained. PTAL.

**Comment by tenzen-y** [comment]
> Awesome. I updated https://github.com/kubernetes-sigs/scheduler-plugins/releases/tag/v0.27.8 to claim the libs will still be maintained. PTAL.

Thank you for the updating! That looks great :)
