### ISSUE TITLE
doc: manifest updates to use v1 as scheduler config and multipoint

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#673]
I'd propose the following doc/manifest update:

- [ ] use v1 (instead of v1beta3) as the version of all scheduler config yamls
- [ ] use `MultiPoint` to simplify configuring each plugin

/kind doc
/good-first-issue

**Comment by lianghao208** [comment]
Some plugins are still in v1beta2, do we replace them with v1 as well?

**Comment by Huang-Wei** [comment]
@lianghao208 v1beta2 is gone in v1.28, so https://github.com/kubernetes-sigs/scheduler-plugins/pull/670/commits/d1bf6c59f08a26e10ae42b27234591f7dd402c40 aims to remove it when bumping k8s deps to v1.28. After #670 gets merged, v1beta2 will be removed from this repo.

**Comment by lianghao208** [comment]
/assign 
I will handle this after #670 gets merged.
