### ISSUE TITLE
Cut a new v0.27.9 tag

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#676]
Cut a new 0.27 tag once a newer k8s patch ([v1.27.9](https://github.com/kubernetes/kubernetes/tree/v1.27.9)) is out, so that we can include #675 to have a up-to-date typed client libs to be consumed by external repos like kubeflow.

**Comment by Huang-Wei** [comment]
@tenzen-y could you review #693? After it gets merged, I will cut a tag.

BTW: I assume you'd just need to a tag, not a release, right?

**Comment by tenzen-y** [comment]
> BTW: I assume you'd just need to a tag, not a release, right?

Yes, that's right. I'm ok without a new release.

**Comment by Huang-Wei** [comment]
https://github.com/kubernetes-sigs/scheduler-plugins/tree/v0.27.9 was cut.

**Comment by tenzen-y** [comment]
> https://github.com/kubernetes-sigs/scheduler-plugins/tree/v0.27.9

Thank you!
