### ISSUE TITLE
Multi-tenant Elastic Resource Quota #48

### ISSUE THREAD

**Issue by kaiohenricunha** [kubernetes-sigs/scheduler-plugins#681]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

The current design of the capacity scheduler for elastic quotas doesn't fit a multi-tenant scenario, if I understand it correctly.

If I have the following namespaces:

acme-dev-us-west-2-webhook
acme-dev-us-west-2-kube-janitor
apple-dev-us-west-2-webhook

It would be great if we could configure the "acme" tenant resources to be shared only among namespaces starting with "acme".

### What did you expect to happen?

Tenant's resources not shared with other tenants

### Kubernetes version

1.28

### Scheduler Plugins version

Latest

**Comment by Huang-Wei** [comment]
My 2 cents is that there is no one-size-fit-all quota design. If an ElasticQuota needs to support cross-namespace sharing, there are more areas need to be considered:

- semantics of selector (label selector or regex or mix, etc.)
- how to deal with overlapping selectors
- how it impacts preemption
- ...

If you have a through design and can make it backwards-compatible, I'm happy to review to discuss the next steps.

**Comment by kaiohenricunha** [comment]
> My 2 cents is that there is no one-size-fit-all quota design. If an ElasticQuota needs to support cross-namespace sharing, there are more areas need to be considered:
> 
> 
> 
> - semantics of selector (label selector or regex or mix, etc.)
> 
> - how to deal with overlapping selectors
> 
> - how it impacts preemption
> 
> - ...
> 
> 
> 
> If you have a through design and can make it backwards-compatible, I'm happy to review to discuss the next steps.

Thanks for the ideas. I'll see if I can work on that and submit a PR. Could be an interesting use case.

**Comment by imliuda** [comment]
> > My 2 cents is that there is no one-size-fit-all quota design. If an ElasticQuota needs to support cross-namespace sharing, there are more areas need to be considered:
> > 
> > * semantics of selector (label selector or regex or mix, etc.)
> > * how to deal with overlapping selectors
> > * how it impacts preemption
> > * ...
> > 
> > If you have a through design and can make it backwards-compatible, I'm happy to review to discuss the next steps.
> 
> Thanks for the ideas. I'll see if I can work on that and submit a PR. Could be an interesting use case.

Hi, may I ask if you are working on it? Maybe a new queue based plugin can be introduced.
