### ISSUE TITLE
Ability to add tolerations and nodeSelector on the scheduler-pugins helm chart

### ISSUE THREAD

**Issue by trashadewan** [kubernetes-sigs/scheduler-plugins#696]
### Area

- [X] Scheduler
- [ ] Controller
- [X] Helm Chart
- [ ] Documents

### Other components

-

### What happened?

Unable to deplpy chart on specific nodes in the cluster. 

### What did you expect to happen?

use the chart as is and deploy it with changing values.yaml

### How can we reproduce it (as minimally and precisely as possible)?

The helm chart is missing nodeSelector, affinity and tolerations. Please assist in updating the deployement to allow for it making is usefull to be used off the shelf. 

### Anything else we need to know?

-

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:38:15Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Scheduler Plugins version

<details>
release-1.24
</details>

**Comment by Huang-Wei** [comment]
Not a bug ;) Change the kind to feature.

**Comment by mochizuki875** [comment]
@trashadewan Hi, it's added by #697 :)
thanks
