### ISSUE TITLE
[trimaran] Cpu metric not found in node metrics

### ISSUE THREAD

**Issue by namgizlat** [kubernetes-sigs/scheduler-plugins#702]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

while using the plugin trimaran following error appears in log:
E0212 06:47:01.656601       1 targetloadpacking.go:142] "**Cpu metric not found in node metrics**" nodeName="node01.namgiz.com" nodeMetrics=[{Name:instance:node_memory_utilisation:ratio Type:Memory Operator:AVG Rollup:15m Value:11.70095792210995} {Name:instance:node_network_transmit_bytes:rate:sum Type:Bandwidth Operator:AVG Rollup:15m Value:8.235324565656565e+06} {Name:instance:node_network_receive_bytes:rate:sum Type:Bandwidth Operator:AVG Rollup:15m Value:1.6781439838383835e+07} {Name:instance:node_memory_utilisation:ratio Type:Memory Operator:STD Rollup:15m Value:0.03558027903707252} {Name:instance:node_network_transmit_bytes:rate:sum Type:Bandwidth Operator:STD Rollup:15m Value:502076.00473060855} {Name:instance:node_network_receive_bytes:rate:sum Type:Bandwidth Operator:STD Rollup:15m Value:3.155026755193178e+06}]

### What did you expect to happen?

trimaran will use cpu metric for scheduling pods

### Anything else we need to know?

Running on openshift (Version below)

### Kubernetes version

<details>

```
Openshift Version: 4.12.40
Kubernetes Version: v1.25.14+20cda61
```

</details>

### Scheduler Plugins version

<details>
registry.k8s.io/scheduler-plugins/kube-scheduler:v0.27.8
</details>

**Comment by wangchen615** [comment]
@Huang-Wei this issue is due to some metric name upgrades specific to OpenShift. We have made some changes in load watcher so it supports both OpenShift and Kubernetes, should we push an update on the versions of load watcher for Trimaran?

**Comment by Huang-Wei** [comment]
> should we push an update on the versions of load watcher for Trimaran?

Yes, please. And come up with a release note detailing what metrics are both supported.

**Comment by namgizlat** [comment]
> @Huang-Wei this issue is due to some metric name upgrades specific to OpenShift. We have made some changes in load watcher so it supports both OpenShift and Kubernetes, should we push an update on the versions of load watcher for Trimaran?

Hi,

was it done?

**Comment by Huang-Wei** [comment]
cc @wangchen615

/remove-lifecycle rotten
