### ISSUE TITLE
Move generated client code to a new repo

### ISSUE THREAD

**Issue by KunWuLuan** [kubernetes-sigs/scheduler-plugins#706]
We want to import pod group's api in out project. But go module will import k8s.io/kubernetes if we do this.
Can we create a new repo to maintain all apis in the repo?

**Comment by Huang-Wei** [comment]
> But go module will import k8s.io/kubernetes if we do this

I doubt it. Are you sure it's b/c of vendoring of PodGroup?

mpi-operator actually vendors [PodGroup api ](https://github.com/kubeflow/mpi-operator/blob/79a9b379647cd1d9bcc540f97410cc6a4e94c8aa/pkg/controller/podgroup.go#L29)w/o vendoring [k8s.io/kubernetes](https://github.com/kubeflow/mpi-operator/blob/79a9b379647cd1d9bcc540f97410cc6a4e94c8aa/go.mod#L20).

**Comment by KunWuLuan** [comment]
Hi, thanks for replying.

I think the reason why I met the problem is I'm working on the fork of kubernetes. When I use hack/update-vendor.sh to update my vendor, self reference in go.mod would be broken in k8s 1.22.

> mpi-operator actually vendors [PodGroup api ](https://github.com/kubeflow/mpi-operator/blob/79a9b379647cd1d9bcc540f97410cc6a4e94c8aa/pkg/controller/podgroup.go#L29)w/o vendoring [k8s.io/kubernetes](https://github.com/kubeflow/mpi-operator/blob/79a9b379647cd1d9bcc540f97410cc6a4e94c8aa/go.mod#L20).

Yes, you are right. I will try to vendors the api in 1.28 to see if the problem still exists, thanks very much.
