### ISSUE TITLE
k8s deps version in 1.18-release

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#71]
@Huang-Wei  Any reason to use v1.18.8 instead of v1.18.9 in 1.18-release? Thanks.

**Comment by Huang-Wei** [comment]
sure, please raise a PR, and I will create a tag right after that.

**Comment by yuanchen8911** [comment]
> sure, please raise a PR, and I will create a tag right after that.

PR submitted:  https://github.com/kubernetes-sigs/scheduler-plugins/pull/74
