### ISSUE TITLE
Newer version of Kubernetes support

### ISSUE THREAD

**Issue by patrickshan** [kubernetes-sigs/scheduler-plugins#712]
Hi there, 

Looking at the `Compatibility Matrix`, it seems that currently scheduler-plugins only supports Kubernetes version up to 1.27.8. But when I checked the go modules dependency, it seems that it's already using 1.28.4 library. Does that mean current master already supports 1.28 ? How about 1.29 ? Is there any plan to sync with the Kubernetes [release](https://kubernetes.io/releases/) ?

Thanks,
Patrick

**Comment by Huang-Wei** [comment]
> Does that mean current master already supports 1.28 ?

Yes, `master` vendors 1.28, and we treat `master` as the developer branch.

> How about 1.29 ?

I will cut release 0.28 no late than next week. And meanwhile, bump k8s deps on `master` to 1.29.

> Is there any plan to sync with the Kubernetes [release](https://kubernetes.io/releases/) ?

We are intentionally making `master` one release behind the latest release of k8s release.

**Comment by patrickshan** [comment]
@Huang-Wei thanks for the information. Any link I can read for the reason behind the decision about the third question ? (one release behind the latest release)

**Comment by Huang-Wei** [comment]
@patrickshan One reason is based on users' demands, i.e., how confident the majority of our users would be if master jump onto latest k8s release immediately when it's released.

The other reason is, the latest release may need some time to soak to reveal issues, which is one another issue staying one release behind is a good choice.

The last reason is b/c of maintainer's bandwith, we don't do backport fixes frequently, so developing on a stable k8s base is critical.

**Comment by Huang-Wei** [comment]
It's already completed.
