### ISSUE TITLE
Code generation incorrect since 1.29 bump

### ISSUE THREAD

**Issue by SebMuir-Smith** [kubernetes-sigs/scheduler-plugins#729]
### Area

- [ ] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### Other components

Code Generation

### What happened?

Commit 99de67d moved from `generate-groups.sh`/`generate-internal-groups.sh` to `kube_codegen.sh` for code generation. The former was a callable script, and the latter simply defines functions that should be called separately.

This transition doesn't seem to have been done correctly; `kube_codegen.sh` is being called as if it was an executable script, which does absolutely nothing.

The codegen now looks to be broken and seemingly will not generate anything when it is run. 

### What did you expect to happen?

Migration should have been done according to the new usage of `kube_codegen.sh`, i.e. https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/examples/hack/update-codegen.sh

### How can we reproduce it (as minimally and precisely as possible)?

1. Delete files that were previously generated by `generate-groups.sh`/`generate-internal-groups.sh`.
2. Run `./hack/update-codegen.sh`
3. Observe that files were not replaced

### Kubernetes version

N/A

### Scheduler Plugins version

N/A

**Comment by Huang-Wei** [comment]
Thanks for the report. I created a revert PR #747 to fix this issue.

#747 is created to track the codegen script's migration.
