### ISSUE TITLE
add more meaningful fields to crd objects

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/scheduler-plugins#730]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

Currently, when using `kubectl get` with podgroup and elasticquotas, there are only two fields displayed: name and age. We should provide more meaningful fields to make it more convenient to use.
```bash
root@VM-0-15-ubuntu:/home/ubuntu# kubectl get podgroups.scheduling.x-k8s.io
NAME   AGE
pg1   2d8h
root@VM-0-15-ubuntu:/home/ubuntu# kubectl get elasticquotas.scheduling.x-k8s.io              
NAME   AGE
test    19h
```

### What did you expect to happen?

We should provide more meaningful fields, which will be more convenient to use
as follows:
```bash
root@VM-0-15-ubuntu:/home/ubuntu# kubectl get podgroups.scheduling.x-k8s.io
NAME   PHASE        MINMEMBER   AGE
pg1    Scheduling   3           19h
root@VM-0-15-ubuntu:/home/ubuntu# kubectl get elasticquotas.scheduling.x-k8s.io
NAME   USED                                            MIN                                             AGE
test   {"cpu":"0","memory":"0","nvidia.com/gpu":"0"}   {"cpu":10,"memory":"20Gi","nvidia.com/gpu":1}   27h
```

### Kubernetes version

None
<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

None
<details>

</details>

**Comment by googs1025** [comment]
@Huang-Wei @ffromani WDYT

**Comment by ffromani** [comment]
I think this would be a useful improvement. Perhaps `/kind feature`?

**Comment by googs1025** [comment]
/kind feature  
sure, thanks @ffromani
