### ISSUE TITLE
Migrate to contextual logging

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/scheduler-plugins#743]
### Area

- [X] Scheduler
- [X] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

k/k is migrating to contextual logging, we should also follow up to add more context when logging

https://github.com/kubernetes/enhancements/issues/3077

### What did you expect to happen?

use contextual logging

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Scheduler Plugins version

<details>
v0.28.9
</details>

**Comment by ffromani** [comment]
noderesourcetopology migrated in #710 and #725

**Comment by googs1025** [comment]
@ffromani @zwpaper Do other plugins also need log modification? If necessary, I will take it

**Comment by zwpaper** [comment]
Hi @googs1025, thanks for the interest, I think it would be great if we can migrate all logs to contextual logging since the k/k is working hard on it.

feel free to take it and raise PRs for it!

**Comment by googs1025** [comment]
@zwpaper thanks for reply. I want to confirm some details first. Do we need to replace the original `klog.ErrorS(err, "xxxxx")` with `lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)`?  Is my understanding correct?

The following code
```go
	lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)

	lh.V(4).Info(logging.FlowBegin)
	defer lh.V(4).Info(logging.FlowEnd)

	nodeTopology, ok := tm.nrtCache.GetCachedNRTCopy(ctx, nodeName, pod)
	if !ok {
		lh.V(2).Info("invalid topology data")
		return framework.NewStatus(framework.Unschedulable, "invalid node topology data")
	}
	if nodeTopology == nil {
		return nil
	}
```

**Comment by ffromani** [comment]
> @zwpaper thanks for reply. I want to confirm some details first. Do we need to replace the original `klog.ErrorS(err, "xxxxx")` with `lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)`? Is my understanding correct?
> 
> The following code
> 
> ```go
> 	lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)
> 
> 	lh.V(4).Info(logging.FlowBegin)
> 	defer lh.V(4).Info(logging.FlowEnd)
> 
> 	nodeTopology, ok := tm.nrtCache.GetCachedNRTCopy(ctx, nodeName, pod)
> 	if !ok {
> 		lh.V(2).Info("invalid topology data")
> 		return framework.NewStatus(framework.Unschedulable, "invalid node topology data")
> 	}
> 	if nodeTopology == nil {
> 		return nil
> 	}
> ```

This is how I did it in the noderesourcetopology plugin. The values (`WithValues`) you need to add are likely different, and the idiom
```
lh.V(4).Info(logging.FlowBegin)
defer lh.V(4).Info(logging.FlowEnd)
```
Is something I find useful for debugging but is not universally accepted as good practice. Besides that IMO the general approach should look like that indeed.

**Comment by googs1025** [comment]
> > @zwpaper thanks for reply. I want to confirm some details first. Do we need to replace the original `klog.ErrorS(err, "xxxxx")` with `lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)`? Is my understanding correct?
> > The following code
> > ```go
> > 	lh := klog.FromContext(ctx).WithValues(logging.KeyPod, klog.KObj(pod), logging.KeyPodUID, logging.PodUID(pod), logging.KeyNode, nodeName)
> > 
> > 	lh.V(4).Info(logging.FlowBegin)
> > 	defer lh.V(4).Info(logging.FlowEnd)
> > 
> > 	nodeTopology, ok := tm.nrtCache.GetCachedNRTCopy(ctx, nodeName, pod)
> > 	if !ok {
> > 		lh.V(2).Info("invalid topology data")
> > 		return framework.NewStatus(framework.Unschedulable, "invalid node topology data")
> > 	}
> > 	if nodeTopology == nil {
> > 		return nil
> > 	}
> > ```
> 
> This is how I did it in the noderesourcetopology plugin. The values (`WithValues`) you need to add are likely different, and the idiom
> 
> ```
> lh.V(4).Info(logging.FlowBegin)
> defer lh.V(4).Info(logging.FlowEnd)
> ```
> 
> Is something I find useful for debugging but is not universally accepted as good practice. Besides that IMO the general approach should look like that indeed.

Thank you for your answer, it really helped me understand the background of this issue.

**Comment by googs1025** [comment]
/assign 

i will take this

**Comment by googs1025** [comment]
Contextual logging has been resolved in batches pr, so I closed this issue.
/close
