### ISSUE TITLE
Add support for ppc64le and s390x architectures

### ISSUE THREAD

**Issue by prb112** [kubernetes-sigs/scheduler-plugins#745]
### What would you like to be added

Kubernetes supports multiple architectures - amd64 arm arm64 ppc64le s390x. In order to use scheduler plugins on ppc64le or s390x, I'd like to build the scheduler-plugins container image with support for s390x and ppc64le in the sig.

This would be in addition to the already provided x86_64,arm64 container image.
This request is similar to #113

I suspect only the makefile needs updating:

```
Makefile:15:ARCHS = amd64 arm64
Makefile:46:.PHONY: build.arm64v8
Makefile:57:.PHONY: build-controller.arm64v8
Makefile:69:.PHONY: build-scheduler.arm64v8
Makefile:88:.PHONY: release-image.arm64v8
```

**Comment by Huang-Wei** [comment]
FYI: `linux/ppc64le` failed in latest [image build](https://storage.googleapis.com/kubernetes-jenkins/logs/post-scheduler-plugins-push-images/1816225617260056576/build-log.txt).

```
......
#29 [linux/ppc64le stage-0 4/4] RUN RELEASE_VERSION=v20240724-v0.28.8-71-g9ae8f214 make build-scheduler
TIMEOUT
ERROR: context deadline exceeded
make: *** [Makefile:66: release-image] Terminated
--------------------------------------------------------------------------------
```

**Comment by prb112** [comment]
Oh. just noticed this one, and the extension of the timeout. that makes sense. Thanks, paul
