### ISSUE TITLE
Improve co-scheduling plugins base on framework

### ISSUE THREAD

**Issue by denkensk** [kubernetes-sigs/scheduler-plugins#8]
After the [coscheduling plugin](https://github.com/kubernetes-sigs/scheduler-plugins/pull/4) is merged . The next phase is to improve the performance and configurability of coscheduling. This issue will track all TODOs in coscheduling or schedule framework.

#### Optimize performance
- [ ] 1. expose pods status(assumed or actually scheduled) in the SharedLister of Framework
- [ ] 2. get actually scheduled(bind successfully) account from the SharedLister in coscheduling plugins
https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L163-L166
- [ ] 3. get the total pods from the scheduler cache and queue instead of the hack manner
https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L221-L230
- [ ] 4. Efficient Requeuing of Unschedulable Pods https://github.com/kubernetes/kubernetes/issues/87738
- [ ] 5. Move the pods(rejected by Prefilter or Permit) back activeQ by the new mechanism 

#### PodGroup optimization
- [x] 1. implement a timeout based gc for the PodGroupInfos map
https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L43-L49
- [ ] 2. keep a cache of pod group size to improve reading efficiency
https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L248-L259

#### Waiting time Configurability
- [x] 1. make the waiting timeout configurable https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L61-L62
- [x] 2. Change the timeout to dynamic value depends on the size of the pod group
https://github.com/kubernetes-sigs/scheduler-plugins/blob/ba1a6315a1a43d6d276ddd123b19f127fead2fbc/pkg/coscheduling/coscheduling.go#L171-L172

/cc @ahg-g @Huang-Wei @alculquicondor

**Comment by ahg-g** [comment]
Thanks Alex, for each item, it would be great to link to the part of your plugin's code that would benefit from it, just to get more context.

**Comment by alculquicondor** [comment]
Also link to k/k bugs if they already exist

I see 1,2&3 in first group as the same. Are you sure you need the granularity of 1&2?

**Comment by mateuszlitwin** [comment]
Few ideas that you might find useful:

1. `PodGroupInfos` could potentially be cleaned with finalizers tied to the `PodInfo`, though someone might break it in the future accidentally.

2. I think plugin could reject waiting pods if one of the scheduled pods cannot find fitting nodes after multiple attempts (that is `PreScore` has no nodes candidates). This should help with ensuring we do not keep resources reserved for too long given that it is probably the most common reason for keeping gang waiting.

Also, is there a plan to support PodGroup resource in the future? I think it would allow to better handle pod group that changes in size (e.g. stateful set getting scaled up or down) - it seems like right now there is no one source of truth for the group's min available value.

**Comment by alculquicondor** [comment]
I like 2.

Defining PodGroup in a RD was explicitly put out of the scope for now. I agree that it would be a good idea, though. But we should be looking at other definitions already in place for similar things. I assume kube-batch and kbatch have some.

**Comment by denkensk** [comment]
> 2. I think plugin could reject waiting pods if one of the scheduled pods cannot find fitting nodes after multiple attempts.
thanks for your comments. @mateuszlitwin  I like it. Also I think if we can record the total attempts of pods in the same PodGroup, once it reaches some specified count. It will reject the total PodGroup.

> Also, is there a plan to support PodGroup resource in the future? I think it would allow to better handle pod group that changes in size (e.g. stateful set getting scaled up or down) - it seems like right now there is no one source of truth for the group's min available value. Also this would allow to upgrade the gang without updating every single pod.

I have a plan to support the PodGroup in the future to easier integration with Kubeflow/Spark-operator. And It will be convenient to mange the PodGroup and react to the change for min. But I think we can reuse the definition of PodGroup in other project like Kube-batch as @alculquicondor said.

**Comment by lianghao208** [comment]
@denkensk I checked the TODOs as listed, it seems all the improvements have been done. Are there any  follow up improvements need to be done?
