### ISSUE TITLE
how can I run this plugins in my k8s cluster

### ISSUE THREAD

**Issue by lianghao208** [kubernetes-sigs/scheduler-plugins#80]
KubeSchedulerConfiguration resource seems belong to group  "kubescheduler.config.k8s.io" and version "kubescheduler.config.k8s.io/v1beta1", but in k8s 1.19.2, there is neither group  "kubescheduler.config.k8s.io" nor version "kubescheduler.config.k8s.io/v1beta1", do I need to apply KubeSchedulerConfiguration crd first? I can`t find any doc related.

**Comment by Huang-Wei** [comment]
@lianghao208 Nope, `KubeSchedulerConfiguration` is not a CRD. It's essentially an API for default scheduler to manage the configuration parameters, in a more organized way. It's not persisted anywhere, only horned upon the startup of scheduler.
