### ISSUE TITLE
[Feature Request] Release version compiled with K8s v1.30

### ISSUE THREAD

**Issue by tenzen-y** [kubernetes-sigs/scheduler-plugins#811]
IIUC, this project used to be released every three ~ four months (1.29 was released in July).
The latest scheduler plugins version is slightly older (v1.29) since the latest K8s version is v1.31.

So, I would like to request the release of the new scheduler-plugins compiled with K8s v1.30.

@Huang-Wei, do you have any schedule for releasing the v1.30?

**Comment by Huang-Wei** [comment]
@tenzen-y it will be ~end of this month

**Comment by tenzen-y** [comment]
> @tenzen-y it will be ~end of this month

Thank you for letting me know. Feel free to send a ping if you need help, including lgtm tagging.

**Comment by tenzen-y** [comment]
Is there any update on this?

**Comment by Huang-Wei** [comment]
I will get most of the prs ready in the weekend. And release will be but next week.

**Comment by tenzen-y** [comment]
> I will get most of the prs ready in the weekend. And release will be but next week.

Thanks for your work!

**Comment by Huang-Wei** [comment]
Tracked in #819

**Comment by tenzen-y** [comment]
Thanks!
/close

**Comment by Huang-Wei** [comment]
I will keep #819 open as there are post-release actions to be finished.
