### ISSUE TITLE
Add Branch Name To Staging Registry Container Image Tags

### ISSUE THREAD

**Issue by seanmalloy** [kubernetes-sigs/scheduler-plugins#82]
From https://github.com/kubernetes-sigs/scheduler-plugins/pull/77#issuecomment-712373957 ...

We might want to consider adding the branch name to container image tags in the staging registry.

- if it's on release-v1.x.y, let's keep current logic (i.e., use the tag plus a random string)
- if it's on the master branch, let's use "master" plus a random string - it's b/c we usually don't have a tag on master branch.

We could use the `_PULL_BASE_REF` variable from the `cloudbuild.yaml` to get the branch name. The `Makefile` would need to be updated. See [the line](https://github.com/kubernetes-sigs/scheduler-plugins/blob/d76bec0a76385d834e014c6c1bc678551726f687/cloudbuild.yaml#L15) in `cloudbuild.yaml`.

**Comment by seanmalloy** [comment]
@Huang-Wei and @denkensk I can work on this if you'd like. It will probably be several weeks before I would be able to start looking at this.

**Comment by Huang-Wei** [comment]
@seanmalloy do you think it's more conventional to give a (temporary) tag to master branch?

**Comment by seanmalloy** [comment]
@Huang-Wei in my opinion we should not create a temporary tag. I don't actually expect any end users to use the container images from the staging registry, but I could be wrong. End users will use the official container images from k8s.gcr.io, not the ones from the staging registry.

So from my perspective the tags in the staging registry need to be useful for people responsible for creating releases. Right now that is you. So I'd say you have the final call if you want it changed or not.

**Comment by Huang-Wei** [comment]
@seanmalloy Let's go with the option you proposed:

> We might want to consider adding the branch name to container image tags in the staging registry.
> 
> * if it's on release-v1.x.y, let's keep current logic (i.e., use the tag plus a random string)
> * if it's on the master branch, let's use "master" plus a random string - it's b/c we usually don't have a tag on master branch.

Thanks!

**Comment by seanmalloy** [comment]
Hoping to get to this in the next few weeks.

/assign
/kind cleanup
