### ISSUE TITLE
Official images

### ISSUE THREAD

**Issue by Huang-Wei** [kubernetes-sigs/scheduler-plugins#84]
It seems even after https://github.com/kubernetes/k8s.io/pull/1346 gets merged, `k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.9` is still unable to be downloaded:

```
root@wei-dev:~# docker pull k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.9
Error response from daemon: manifest for k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.9 not found: manifest unknown: Failed to fetch "v0.18.9" from request "/v2/scheduler-plugins/kube-scheduler/manifests/v0.18.9".
```

Not quite sure it's due to missing folder "k8s-staging-scheduler-plugins" under https://github.com/kubernetes/k8s.io/tree/master/k8s.gcr.io/manifests.

**Comment by Huang-Wei** [comment]
@seanmalloy Could you shed some light here?

**Comment by seanmalloy** [comment]
> @seanmalloy Could you shed some light here?

@Huang-Wei I will take a look.

**Comment by Huang-Wei** [comment]
Cool, we can refer to descheduler to check what's missing here.

```
root@wei-dev:~# docker pull k8s.gcr.io/descheduler/descheduler:v0.19.0
v0.19.0: Pulling from descheduler/descheduler
efa56301e3c3: Pull complete
Digest: sha256:c8b2842d35ebcd3c5e8226c95e07bc2a7dee47bfb64150fce12a0541943a3dde
Status: Downloaded newer image for k8s.gcr.io/descheduler/descheduler:v0.19.0
k8s.gcr.io/descheduler/descheduler:v0.19.0
```

**Comment by seanmalloy** [comment]
I think this is the CI job that does the image promotions: https://testgrid.k8s.io/wg-k8s-infra-k8sio#post-k8sio-cip. Looking at the logs I don't see any entries for the scheduler-plugins staging repo. In contrast I do see log entries for the descheduler.

I've started a slack thread in `#wg-k8s-infra` to ask for assistance: https://kubernetes.slack.com/archives/CCK68P2Q2/p1604031380122300

**Comment by seanmalloy** [comment]
Here is the fix https://github.com/kubernetes/k8s.io/pull/1383

**Comment by seanmalloy** [comment]
PR kubernetes/k8s.io#1383 was merged. Looks like it works now.
```
$ docker pull k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.9
v0.18.9: Pulling from scheduler-plugins/kube-scheduler
Digest: sha256:01d1b53bce3c2477ab403b54914ff9229e073d99e9b711f161b796cec73176be
Status: Downloaded newer image for k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.18.9
$ docker images | grep k8s.gcr.io/scheduler-plugins
k8s.gcr.io/scheduler-plugins/kube-scheduler       v0.18.9       d552002571fc       3 weeks ago         49.5MB
```

/close
