### ISSUE TITLE
Add a new tag v0.19.0

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#86]
@Huang-Wei  The K8s API dep was already bumped to 1.19.0 in the master branch. Should we add a new tag `v0.19.0`?  Otherwise, `git describe` and `kube-scheduler --version` just report the outdated information. 

```
$ git describe
v0.18.800-54-gad9f407
```

```
$ kube-scheduler --version
I1029 18:05:37.788957   14935 registry.go:173] Registering SelectorSpread plugin
I1029 18:05:37.789067   14935 registry.go:173] Registering SelectorSpread plugin
Kubernetes v0.18.800
```

**Comment by seanmalloy** [comment]
@yuanchen8911 I need to track down the issue with the scheduler-plugins container image promotion process. See #84. After that I think we should be fine to create the v0.19.0 release.

Although it is up @Huang-Wei as he is the person that creates the releases.

**Comment by Huang-Wei** [comment]
I talked this with @seanmalloy in #82, and we decided to put a `master` prefix for master branch.

Creating a tag for master doesn't sound quite conventional.
