### ISSUE TITLE
User Documentation for deploying scheduler plugins

### ISSUE THREAD

**Issue by denkensk** [kubernetes-sigs/scheduler-plugins#89]
We need some docs to help users deploying the server of scheduler-plugins. 
Our documentation needs to include the following steps
1. How to deploy the scheduler/controller of scheduler-plugins in an existing k8s cluster
2. How to replace existing default-scheduler
3. Deploy the controller of scheduling-plugins
4. Create CRD for PodGroup
5. How to verify that the scheduler starts successfully. 

Different people may deploy cluster in different ways. 
We can take a cluster deployed by kubeadm as an example.

/help

**Comment by Huang-Wei** [comment]
@denkensk This is definitely necessary. Would you mind revealing more details in the PR description?

**Comment by denkensk** [comment]
> @denkensk This is definitely necessary. Would you mind revealing more details in the PR description?

Done

**Comment by vincent-pli** [comment]
@Huang-Wei  @denkensk I agree it's definitely necessary, easy people who want to take a try.
Could we introduce [ko](https://github.com/google/ko) for installation, it's simplest way for installation I ever used.

**Comment by denkensk** [comment]
Thanks @vincent-pli 
I am not sure if ko can  update/operate the pods with static pods? Because the kube-scheduler deployed by kubeadm is static pod.

**Comment by vincent-pli** [comment]
@denkensk 
Why we have to disable default scheduler, user could define `spec.schedulerName` .
The `ko` is only for compile&deployment cloud native resource based on golang, definitely can not handle the static pods, but we can add extral step to let user delete it manually.

**Comment by denkensk** [comment]
> The ko is only for compile&deployment cloud native resource based on golang, definitely can not handle the static pods, but we can add extral step to let user delete it manually.
Thanks, SGTM @Huang-Wei  WDYT?

> Why we have to disable default scheduler
If the users don't disable the default scheduler, the default and our scheduler-plugins will work together at the same time. At this time, there will be resource conflicts or the fight for the scheduler lock.  @vincent-pli 

> user could define spec.schedulerName
Although the user can define spec.schedulerName of pod, But how about other pods like system pod or prometheus?
And also allowing users to modify will increase their cost.  @vincent-pli

**Comment by vincent-pli** [comment]
@denkensk 
That's make sense, thanks for clarification.

**Comment by Huang-Wei** [comment]
> Thanks, SGTM @Huang-Wei WDYT?

`ko` sounds groovy and can definitely be a bonus. But now as we're starting from scratch, I think we should complete the basic support first.

Add some extra note on what @denkensk mentioned on resource conflict, scheduler-plugins derives from default scheduler to keep 100% of upstream scheduler's functionality, so it's very recommended to replace the default scheduler, instead of running X and X' (X + out-of-tree plugins) as two separate scheduler binaries. (X = default scheduler)

**Comment by vincent-pli** [comment]
@Huang-Wei 
Thanks, one more question, 
I saw in `cmd/scheduler/main`, we register/load all plugins(coscheduler, noderesources, qos .etc) in the repo, so that's means we tend to user take a full package with all extra plugin or user should try the plugins one by one?  if it's the former how to handle the configuration(`KubeSchedulerConfiguration` confliction)?

**Comment by Huang-Wei** [comment]
@vincent-pli Plugin registration and configuration are two-folded: you can register any many plugins as you want, while upon scheduler's startup, the `KubeSchedulerConfiguration` determines the scheduler's runtime behavior. If there is any conflict, the validation logic fails the scheduler's start. In other words, you don't need to use all registered plugins.

**Comment by LeoLiuYan** [comment]
I also interested  in making some contributions to the docs.

**Comment by lianghao208** [comment]
@Huang-Wei @denkensk As you mentioned the resource conflict, if users add a new scheduler plugin, does that mean the whole cluster are recommended to use only one of them( the new schduler and default-scheduler) instead of using both? If so, what if I need to add some scheduling logic on top of the default-sheduler( like the old sheduler extender)? Do I need to modify the default-scheduler, add my logic and compile a new plugin to replace it?

**Comment by denkensk** [comment]
>does that mean the whole cluster are recommended to use only one of them( the new schduler and default-scheduler) instead of using both?

Yes. In fact, there is no difference in scheduling logic between default-scheduler and scheduler-plugins.  scheduler-plugins = default scheduler + plugins. `default-scheduler` can be replaced by scheduler-plugins. It doesn't introduce compatibility issues.

> so, what if I need to add some scheduling logic on top of the default-sheduler( like the old sheduler extender)? Do I need to modify the default-scheduler, add my logic and compile a new plugin to replace it?

You mean you changed the code base of default-scheduler or just add an extender by the old extension mechanism？
@lianghao208

**Comment by lianghao208** [comment]
> 
> You mean you changed the code base of default-scheduler or just add an extender by the old extension mechanism？

 I mean changing the code base of default-scheduler, the old extension mechanism seems not a recommended way to extend any more.
@denkensk

**Comment by denkensk** [comment]
> I am also interested in making some contributions to the docs.

Thanks. @LeoLiuYan   Maybe you can start by drafting a document to document your deployment process. Then we can help to review
it.

**Comment by denkensk** [comment]
> > I am also interested in making some contributions to the docs.
> 
> Thanks. @LeoLiuYan Maybe you can start by drafting a document to document your deployment process. Then we can help to review it.

Also /cc @vincent-pli

**Comment by denkensk** [comment]
> I mean changing the code base of default-scheduler, the old extension mechanism seems not a recommended way to extend any more.
----

I see, If you change the code base of default-scheduler. You need to import your version in this scheduler-plugins and re-compile or rebuild it by https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/Makefile.
@lianghao208

**Comment by vincent-pli** [comment]
@denkensk 
Actually, I use `ko`, I can provide a sample for how to deploy `plugin`s with `ko` soon if necessary.

**Comment by vincent-pli** [comment]
@denkensk @Huang-Wei 
See the repo: https://github.com/vincent-pli/coscheduler-same-node-ko
Extra manual step needed to delete default scheduler(with `kubeadm` env):
``` 
rm /etc/kubernetes/manifests/kube-scheduler.yaml
```

**Comment by denkensk** [comment]
> @denkensk @Huang-Wei
> See the repo: https://github.com/vincent-pli/coscheduler-same-node-ko
> Extra manual step needed to delete default scheduler(with `kubeadm` env):
> 
> ```
> rm /etc/kubernetes/manifests/kube-scheduler.yaml
> ```

Thanks.  @vincent-pli 
Another manual step needed to create the config. Because the static pod can't access the configmap.

**Comment by seanmalloy** [comment]
This was partially completed in https://github.com/kubernetes-sigs/scheduler-plugins/pull/142, but I think additional work is needed.

/remove-lifecycle rotten

**Comment by Huang-Wei** [comment]
I think most of the items have been covered in the install doc. @seanmalloy could you please list some items that you think are not covered yet?

**Comment by seanmalloy** [comment]
> I think most of the items have been covered in the install doc. @seanmalloy could you please list some items that you think are not covered yet?

@Huang-Wei I think the docs look good now. The missing parts were taken care of by #163.

/close
