### ISSUE TITLE
The permit logic in coscheduling

### ISSUE THREAD

**Issue by lianghao208** [kubernetes-sigs/scheduler-plugins#90]
I am using cosheduling plugins, but I am a little connfused about the permit logic.
The code is
```go
func (pgMgr *PodGroupManager) Permit(ctx context.Context, pod *corev1.Pod, nodeName string) (bool, error) {
	pgFullName, pg := pgMgr.GetPodGroup(pod)
	if pgFullName == "" {
		return true, util.ErrorNotMatched
	}
	if pg == nil {
		// once we have admission check, a Pod targeting non-exisitng PodGroup won't be created.
		// So here it just serves as a sanity check.
		return false, fmt.Errorf("PodGroup not found")
	}

	bound := pgMgr.calculateBoundPods(pg.Name, pg.Namespace)
	// The bound is calculated from the snapshot. The current pod does not exist in the snapshot during this scheduling cycle.
	ready := int32(bound)+1 >= pg.Spec.MinMember
	if ready {
		return true, nil
	}
	return false, util.ErrorWaiting
}

func (pgMgr *PodGroupManager) calculateBoundPods(podGroupName, namespace string) int {
	nodeInfos, err := pgMgr.snapshotSharedLister.NodeInfos().List()
	if err != nil {
		klog.Errorf("Cannot get nodeInfos from frameworkHandle: %v", err)
		return 0
	}
	var count int
	for _, nodeInfo := range nodeInfos {
		for _, podInfo := range nodeInfo.Pods {
			pod := podInfo.Pod
			if pod.Labels[util.PodGroupLabel] == podGroupName && pod.Namespace == namespace && pod.Spec.NodeName != "" {
				count++
			}
		}
	}

	return count
}
```

it calculate the number of pods have been bound to nodes. If  the number of pods have been bound to nodes are greater than the minMember of the PodGroup, the permit plugin will allow the subsequence scheduling process. 
But lets say if I set minMember in the PodGroup to 3, and the replicas of my deployment is 6. Wouldn`t it be all the pods become pending status because none of them can pass the permit plugin?(Since there is no pod binding among the podGroup because 
 they all stuck in the permit stage)
I am not sure if I comprehend the whole process correctly, can someone help?

**Comment by vincent-pli** [comment]
@lianghao208 
 I guess the `calculateBoundPods` is a little confuse people, the `pod.Spec.NodeName != ""` also include `pod` is already passed step `Reserve` but not passed `permit`(in waiting state), your `pod` are also calculated.  so if they meet the `min`, it will be allowed to run.

**Comment by denkensk** [comment]
The Bound pods means `Reserved/Assumed` status in Scheduling Cycle, not the pods bonded to the nodes. When the count 
 of reserved pods meets the `min`,  they will pass the permit plugin.
@lianghao208

**Comment by lianghao208** [comment]
@vincent-pli @denkensk  Thanks! Now I get it.

**Comment by denkensk** [comment]
@lianghao208  Would you like to submit a PR to add some comments for it to prevent others confuse？

**Comment by lianghao208** [comment]
> @lianghao208 Would you like to submit a PR to add some comments for it to prevent others confuse？

Sure, I'd love to.
