### ISSUE TITLE
`make autogen` does not generate deepcopy and register code for new config args types

### ISSUE THREAD

**Issue by houz42** [kubernetes-sigs/scheduler-plugins#94]
I am writing a scheduler plugin which needs to be coifigured with args. I defined the args type both in `pkg/apis/config/types.go` and `pkg/apis/config/v1beta1/types.go` and then run `make auto`. But nothing happend, no error, no gnerated code, neither did running `hack/update-autogen.sh` work.

I did write the comment `// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
` before the type definition.

```
❯ make autogen
hack/update-vendor.sh
hack/update-generated-openapi.sh
Generating Kubernetes OpenAPI

❯ ./hack/update-codegen.sh
Generating deepcopy funcs
Generating defaulters
Generating conversions
Generating deepcopy funcs
Generating clientset for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/clientset
Generating listers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/listers
Generating informers for scheduling:v1alpha1 at sigs.k8s.io/scheduler-plugins/pkg/generated/informers
```

**Comment by seanmalloy** [comment]
@houz42 can your provide a URL to the code or is it proprietary code? If it's propriety can you provide the simplest example code change the reproduces this error?

/kind support

**Comment by houz42** [comment]
@seanmalloy Thanks for your help.
This is my repo: https://github.com/houz42/scheduler-plugins/tree/node-available-resource

**Comment by Huang-Wei** [comment]
@houz42 It works for me. Please check your GOPATH, did you run `hack/update-codegen.sh` under path `${GOPATH}/src/sigs.k8s.io/scheduler-plugins`?

**Comment by houz42** [comment]
>  did you run hack/update-codegen.sh under path ${GOPATH}/src/sigs.k8s.io/scheduler-plugins?

No, I am using go mod. Should I move it under GOPATH or not?
