### ISSUE TITLE
Does NodeResourcesLeastAllocatable + NodeResourcesMostAllocated == NodeResourcesLeastAvailable ?

### ISSUE THREAD

**Issue by houz42** [kubernetes-sigs/scheduler-plugins#95]
If I enable both "NodeResourcesLeastAllocatable"(from the this repo) and "NodeResourcesMostAllocated"(from the main repo) in one profile, and configure them with same weights, have I gotten the equality of "NodeResourcesLeastAvailable"?

## What I really want
A score plugin that favors nodes with fewer resources left. 

Enabling either "NodeResourcesLeastAllocatable" or "NodeResourcesMostAllocated" alone does not meet my situation, because we may run pods of large differences in requested resources on nodes of also large differences in resources allocatable. I have tried to write another scheduler plugin just list the  "NodeResourcesLeastAllocatable" but scores on available (allocatable - allocated) instead of allocatable resources. But then I realized that this plugin may not to be necessary if I can compose it from other plugins.

**Comment by Huang-Wei** [comment]
It may work, as both NodeResourcesLeastAllocatable and NodeResourcesMostAllocated favor the highly-utilized nodes, while one uses absolute usage, the other use ratio of usage.

**Comment by houz42** [comment]
@Huang-Wei  Thanks for your explaination. 

> while one uses absolute usage, the other use ratio of usage.

Considering this difference. Do you think it is necessary to add a real "NodeResourcesAvailable" plugin into this repo? I have already written a simple implementation by copy-and-edit the "NodeResourceAllocatable" plugin, and I am happy to submit a PR if it's OK.

**Comment by Huang-Wei** [comment]
Maybe that can be a PR/KEP in k/k, so that we have one generalized plugin to represent all the semantics - the PluginArgs can be used to differentiate the mode: ratio, absolute number, or both.

**Comment by houz42** [comment]
Does k/k mean the main kubernetes repo? It seems more work to do than a simple "NodeResourcesAvailable", and may need to change the current PluginArgs type.

**Comment by Huang-Wei** [comment]
> Does k/k mean the main kubernetes repo?

Yes.

> It seems more work to do than a simple "NodeResourcesAvailable", and may need to change the current PluginArgs type.

I think there is no much core logic change as the current NodeResourcesLeastAllocatable plugin copies most implementation from k/k already. The PluginArgs part may be a bit hassling - we need to ensure the new Args backward compatible.

**Comment by houz42** [comment]
> The PluginArgs part may be a bit hassling

How about designing a new "NodeResources" plugin implements all of these functions, and then change those old plugins to a instance of the new one, and mark them deprecated?

may be something like this:
```
type NodeResourcesLeastAllocated struct {
	NodeResources
}

func NewNodeResourcesLeastAllocated(args runtime.Object, h framework.FrameworkHandle) (framework.Plugin, error) {
	return NodeResources{
		// set args and other values
	}
}
```

**Comment by houz42** [comment]
And how about add a new plugin and args like this?

https://github.com/houz42/kubernetes/blob/7dda46d3568b326dcbbdf387f50134514f526668/pkg/scheduler/apis/config/types_pluginargs.go#L53

**Comment by Huang-Wei** [comment]
The implementation details don't concern me. What's concerning me is the API (plugin and pluginConfig) backward compatibility, and if we want to deprecate the old API, how to make the migration efforts as least as possible.

To roll this forward, I think one option is to introduce a feature gate like "GenericNodeResourceScorer", with that, you can develop a new plugin with new args.

- In alpha phase, this plugin is disabled, and "NodeResourcesLeastAllocated" is still activated by default.
- In beta phase, this plugin is enabled with default args, and "NodeResourcesLeastAllocated" should be disabled and marked as deprecated. And in the release note, we should remind users to do manual changes or disable the feature gate if they're not using default config.

/cc @patricklundquist

**Comment by patricklundquist** [comment]
> we may run pods of large differences in requested resources on nodes of also large differences in resources allocatable
@houz42, this sounds similar to our use case. We use NodeResourcesLeastAllocatable (higher weight) + NodeResourcesLeastAllocated. Scoring by resources available is distinct from the other two plugins, and could be a useful addition. Nodes can end up with a tie for Allocatable, a tie for Allocated, and still have a difference in Available. 

@Huang-Wei, that migration plan sounds fine. The new plugin should have options for scoring by one or more of Allocatable, Allocated, and Available. And toggling Most/Least for each. Looks like the args that @houz42 shared covers that.

**Comment by houz42** [comment]
@patricklundquist your solution sounds good considering what we have now, and I believe a similar combination suits my use case well enough too. I could use this solution while developing the proposed "GenericNodeResourceScorer". Do yout think this is suitable as a first contribution as (I think) I have enough knowledge of the language and the scheduler framework but not familar with the development and migration process of the project?

**Comment by patricklundquist** [comment]
Sounds good to me. @Huang-Wei, Let me know if you need help with code review or code changes.

**Comment by Huang-Wei** [comment]
@patricklundquist thanks for offering the help!

@houz42 You're welcomed to submit your idea as a KEP, in https://github.com/kubernetes/enhancements/tree/master/keps/sig-scheduling. So that we can brainstorm the design during KEP review.

BTW: in terms of UX, it's debatable which direction is better: providing a generic plugin differentiating the behavior/combination by its args vs. providing multiple plugins and let user to combine the plugins. Which could be a primary concern during KEP review.
