### ISSUE TITLE
Get kubeconfig and Master from command arguments or scheduler-config file?

### ISSUE THREAD

**Issue by yuanchen8911** [kubernetes-sigs/scheduler-plugins#98]
Some scheduler plugins (e.g. `coscheduling`) need kubeconfigpath and master to create new `clientSet`. Instead of using plugin arguments to set the parameters, can we just get the information from the scheduler command line args or `kubeconfig` defined in the scheduler policy file? 

Thanks.

**Comment by Huang-Wei** [comment]
Totally agree it's a pain point for out-of-tree developers. @yuanchen8911 would you mind creating one issue in k/k, and link back here? Let's discuss this in the upstream.

**Comment by yuanchen8911** [comment]
> Totally agree it's a pain point for out-of-tree developers. @yuanchen8911 would you mind creating one issue in k/k, and link back here? Let's discuss this in the upstream.

will do it.

**Comment by yuanchen8911** [comment]
Opened an issue in upstream repo  https://github.com/kubernetes/kubernetes/issues/96427

**Comment by Huang-Wei** [comment]
This is implemented in the upstream on k8s 1.22 - https://github.com/kubernetes/kubernetes/pull/100644

/remove-lifecycle stale

**Comment by fromanirh** [comment]
Hi folks, I'm following this issue because I'm in the same state playing with the `NodeTopologyMatch` plugin.
I was experimenting with `rest.InClusterConfig` with initial promising results to avoid requiring a kubeconfigpath. I was wondering if there are known drawbacks in using `rest.InClusterConfig` or if it is just another alternative, and a bit less convenient, approach to the one documented in this issue.  Thanks for the feedback!

Snippet of code pretty much identical (bar rename, imports) of what I was playing with:
```
func handleKubeClientConfig(kubeconfig, masterOverride string) (*rest.Config, error) {
	if kubeconfig == "" {
		kubeconfig = os.Getenv("KUBECONFIG")
		klog.InfoS("Using kubeconfig from env", "kubeconfig", kubeconfig)
	}

	var config *rest.Config
	var err error
	if kubeconfig != "" {
		klog.InfoS("Loading kube client config from path", "path", kubeconfig, "masterOverride", masterOverride)
		config, err = clientcmd.BuildConfigFromFlags(masterOverride, kubeconfig)
	} else {
		klog.InfoS("Using in-cluster kube client config")
		config, err = rest.InClusterConfig()
	}
	if err != nil {
		return nil, fmt.Errorf("could not get the client: %v", err)
	}

	return config, nil
}
```

**Comment by damemi** [comment]
@fromanirh I talked to @Huang-Wei about this offline so I could get a little more understanding of the Kubeconfig that's passed through the framework handle.

Essentially, the scheduler framework is initialized either with or without a Kubeconfig explicitly passed to it. If no config is passed, the core will fallback to using the default in-cluster config.

The framework handle field implemented in https://github.com/kubernetes/kubernetes/pull/100644 and carried down by Wei's changes in https://github.com/kubernetes-sigs/scheduler-plugins/pull/287/commits/d7c39cb78f6a4e69446c2ef87f893225a4792f38 (using `handle.KubeConfig()`) will give your plugin whichever Kubeconfig is available to the scheduler itself, abstracting away the need for the logic you shared. I think this is what we need to do for this goal. Does that help?

**Comment by Huang-Wei** [comment]
@damemi makes the point.

@fromanirh duplicating the kubeConfig path in plugin argument was an ugly workaround as the kubeConfig scheduler framework employs is not propagated until k8s version 1.22.

Also note I will author a cleanup PR after #287 to get rid of the old kubeConfig arguments, in a new v1beta2 config.

**Comment by fromanirh** [comment]
@damemi @Huang-Wei yes, this helps a lot, thanks. I will just wait for https://github.com/kubernetes-sigs/scheduler-plugins/pull/287 to land. Actually, if I'd be happy to help with that, if needed.

**Comment by Huang-Wei** [comment]
#287 and #290 resolve this issue. Close it.
